### ISSUE TITLE
Highlight rooms with unread notifications in the rooms list

### ISSUE THREAD

**Issue by giomfo** [element-hq/element-x-ios#1037]
## Description ##
Highlight rooms with unread notifications
- add a green bullet for rooms with unread notifications
- add a green @ icon if at least one of these notifications is a mention

## Suggested Design ##
<img width="520" alt="image" src="https://github.com/vector-im/element-x-android/assets/8969772/0b74cc7e-ca1a-4277-858b-2ed223ede00a">

**Comment by sempruijs** [comment]
Yes this would be handy! I think it is important that VoiceOver announces this too. Something like this, "Unread, mentioned, {group name}, {last send message}, {time last send message}"
Also adding an option in the context menu so you can mark it as read.

**Comment by ara4n** [comment]
I can't believe that we've got this far without being able to identify unread rooms (other than by guessing based on where they are in the roomlist).  @amshakal, @VolkerJunginger: am I missing something on why we're hiding which rooms have new messages?  (iMessage, WhatsApp, Telegram, Signal, etc all flag the rooms with new messages...)

**Comment by ara4n** [comment]
oh, hang on. this issue is talking about unread notifs, which we /do/ flag already. but unread msgs which don’t notify are completely unmarked.

**Comment by giomfo** [comment]
@langleyd @nimau FYI the green bullet for rooms with unread notifications is already implemented in EX.
I'm worried about the second point "add a green @ icon if at least one of these notifications is a mention". You will have to implement locally the detection of these potential mentions. Indeed the client will have to handle them itself (even in unencrypted rooms). The server doesn't provide any count related to the mentions
