### ISSUE TITLE
Unsupported event: m.sticker

### ISSUE THREAD

**Issue by Helvio88** [element-hq/element-x-ios#1047]
### Steps to reproduce

I'm running a Synapse Matrix server + SyncV3 + Element X

My Matrix is WhatsApp Bridged with mautrix-whatsapp

Whenever I receive Stickers (a WhatsApp 'webp' image), when bridged to X, I get the following:
![sticker](https://github.com/vector-im/element-x-ios/assets/650183/bdde3c82-b51b-466f-8214-2f8d9ef0f3b8)

Element works fine.

#### What did you expect?
Image to be shown
#### What happened instead?
Error message:
`Unsupported event: m.sticker`

### Your phone model

iPhone 12

### Operating system version

iOS 16.5

### Application version

Version: 1.1.1 (48)

### Homeserver

Synapse (docker:latest)

### Will you send logs?

No

**Comment by pixlwave** [comment]
As described in the [spec](https://spec.matrix.org/v1.7/client-server-api/#msticker), the URL should exist. The error seems to indicate that it is missing.

Can you confirm by sharing the source of the event that this is the case?

**Comment by Helvio88** [comment]
This is the decrypted source. I changed my server to a generic URL:

{
  "type" : "m.sticker",
  "content" : {
    "body" : "image.webp",
    "info" : {
      "size" : 806410,
      "mimetype" : "image\/webp",
      "thumbnail_file" : {
        "hashes" : {
          "sha256" : "PAhQz\/77F3Ked6XY9Al+nrA8Kcmyaj5nioGy7BmdryQ"
        },
        "iv" : "QL3WgMg0k+AAAAAAAAAAAA",
        "key" : {
          "k" : "X--AYMhBpqqkuxJR3Um_r7r8EsRf6KiXQbZHEGQ3yEI",
          "ext" : true,
          "key_ops" : [
            "encrypt",
            "decrypt"
          ],
          "alg" : "A256CTR",
          "kty" : "oct"
        },
        "url" : "mxc:\/\/matrix.my.tld\/RcNUsEJIpSLFwGYgvSlsmudy",
        "v" : "v2"
      },
      "w" : 190,
      "h" : 190,
      "thumbnail_info" : {
        "size" : 806410,
        "mimetype" : "image\/webp",
        "w" : 190,
        "h" : 190
      }
    },
    "file" : {
      "hashes" : {
        "sha256" : "PAhQz\/77F3Ked6XY9Al+nrA8Kcmyaj5nioGy7BmdryQ"
      },
      "iv" : "QL3WgMg0k+AAAAAAAAAAAA",
      "key" : {
        "k" : "X--AYMhBpqqkuxJR3Um_r7r8EsRf6KiXQbZHEGQ3yEI",
        "ext" : true,
        "key_ops" : [
          "encrypt",
          "decrypt"
        ],
        "alg" : "A256CTR",
        "kty" : "oct"
      },
      "url" : "mxc:\/\/matrix.my.tld\/RcNUsEJIpSLFwGYgvSlsmudy",
      "v" : "v2"
    }
  },
  "origin_server_ts" : 0
}

**Comment by pixlwave** [comment]
Linking this to the issue on the bridge: https://github.com/mautrix/whatsapp/issues/662

**Comment by pixlwave** [comment]
Looks like this was fixed in Ruma.
