### ISSUE TITLE
Perform connection test after selecting server (matrix.org can get blocked)

### ISSUE THREAD

**Issue by nisbet-hubbard** [element-hq/element-x-ios#1099]
#### Where are you starting? What can you see?
The startup screen. In a geography where matrix.org is blocked.
#### What do you click?
’Continue’

#### What did you expect?

The server selection screen should be shown first, before any connection test is performed on a server selected by user (this is the workflow in FluffyChat).

If a connection test must be done before a server is selected, do it on a domain known to not have been blocked anywhere instead of matrix.org.

#### What happened instead?
Frozen screen with a spinner saying ‘Loading’ continued for half a minute before the next screen eventually loaded.

This tends to make unsuspecting users believe that the whole app is getting blocked, and give up before the next screen has a chance to load. In reality, it’s only individual homeservers that can ever get blocked. Which is why Matrix is such a blessing for people living under authoritarian regimes: if one doesn’t need to reply on one centralised server, no govt will manage to block (or even find) all the homeservers in order to render a Matrix client unusable.

### Your phone model

iPhone SE2

### Operating system version

iOS 16.3.1

### Application version

1.1.1

### Will you send logs?

No

**Comment by pixlwave** [comment]
Fixed by #3316 (and seemingly had a dupe issue)
