### ISSUE TITLE
‘Leave room’ is broken (Conduit)

### ISSUE THREAD

**Issue by nisbet-hubbard** [element-hq/element-x-ios#1122]
### Steps to reproduce

The ‘Leave room’ functionality is broken. Leaving an existing room shows white screen with a top-left back arrow. Clicking on the arrow crashes the app. After reopening the app the room is still there, and trying to leave it again leads to the error shown in the accompanying screenshot.

A room that one has left in another app (Element iOS or FluffyChat) remains in Element X. Trying to leave it again also leads to the same error message. 

#### What did you expect?
Normal behaviour as in Element iOS or FluffyChat
#### What happened instead?
Rooms one has left remain stubbornly in the app.

Trying to leave | Trying to leave again
:-------------------------:|:-------------------------:
![DDC4215B-AFC1-47FA-88DA-16A33FE2A458](https://github.com/vector-im/element-x-ios/assets/87453615/a4fbc338-f10d-4418-b4fd-3be61d726af0) | ![EFA063C6-FFFA-42D5-9958-686F2F264412](https://github.com/vector-im/element-x-ios/assets/87453615/c6762934-ee57-40fd-b600-de9b26dd8bcc)

### Your phone model

SE2

### Operating system version

16.3.1

### Application version

1.1.1(48)

### Homeserver

Conduit next (v0.6)

### Will you send logs?

No

**Comment by stefanceriu** [comment]
Whatever the error is the app shouldn't crash. Let's at least try to do a static analysis of the involved code.
