### ISSUE TITLE
Previously rejected invites appear in the invite list. 

### ISSUE THREAD

**Issue by neilisfragile** [element-hq/element-x-ios#1137]
### Steps to reproduce

Navigate to the invites list

#### What did you expect?
To see no active invites (since I have none)
#### What happened instead?
I see invites that I previously rejected in other clients, those invites do not appear on those clients. 

### Your phone model

iphone 11 

### Operating system version

16.5

### Application version

1.1.5 246

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by stefanceriu** [comment]
Most likely fixed in https://github.com/matrix-org/matrix-rust-sdk/pull/2567

**Comment by stefanceriu** [comment]
@neilisfragile I was really hoping that fixed it. If you're running nightly can you try clearing your cache from the Developer Options? If it still doesn't work can you submit another rageshake and point out the invite id please?

**Comment by neilisfragile** [comment]
Clearing the cache did not clear the invites, but I have manually rejected them via EX and they have disappeared. So that is definitely a change in behaviour.

**Comment by manuroe** [comment]
This is an old issue that should no more exists.
