### ISSUE TITLE
Resend should be included also in the actions menu for failed echoes

### ISSUE THREAD

**Issue by Velin92** [element-hq/element-x-ios#1186]
Given the discussion started here: https://github.com/vector-im/element-x-ios/issues/1151
Some users may lean more forward long pressing a failed message then tapping on the red alert/timestamp to try resending a failed message.

Also we already provide the removal of a failed message in the message actions menu through the "Remove" action

We should then include a "Resend" action also in the menu.

**Comment by Velin92** [comment]
@amshakal  what should be the icon and the ordering of such action in the menu actions?

**Comment by amshakal** [comment]
It should be the first one on the list IMO.

**Comment by Velin92** [comment]
> It should be the first one on the list IMO.
> 
> Retry and then Remove. I can create a screen with icons etc

we just need the Resend icon, we already have the remove one, what should the icon be then?

**Comment by amshakal** [comment]
We haven't tested th retry mechanism enough to add this functionality just yet. I would suggest lets park this for now and come back to it after testing the retry interaction the way it's been designed. Sorry for the back and forth.

**Comment by pixlwave** [comment]
Closing this as we no longer show retry for network based failures (and crypto ones have a sheet with an explainer that can be opened from the menu).
