### ISSUE TITLE
No way to view the replied message in a reply

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#1209]
### Steps to reproduce

1. View a room with replies in it
2. The copy of the replied event shown in the reply is often a preview (truncated if text, or a tiny thumbnail if image or video)
3. The natural reaction, especially if it's an image or a video, is to tap on the preview to go to the replied message to see what it is.
4. There is no way to do so.

#### What did you expect?

Ability to jump to replied messages from the reply to see what they are - especially if they're an image or video, as the thumbnail is so small you can't see what it is otherwise, or what's being replied to.

#### What happened instead?

No way to jump.

### Application version

257

### Will you send logs?

No

**Comment by manuroe** [comment]
It will happen with permalink support

**Comment by pixlwave** [comment]
Closing as completed by #2748.
