### ISSUE TITLE
Syncing and notifications slow 

### ISSUE THREAD

**Issue by alekslyse** [element-hq/element-x-ios#1222]
### Steps to reproduce

I have been running the normal element client on ios but wanted to try this one, but noticed the sync speed is quite slow (about 5-10 seconds, vs 1-2 on the regular iOS client, as well as notifications is coming later, again about 5-10 seconds delay.

I tried to update sliding sync to the current latest release 0.9.9.3

### Outcome

Using the element X iOS is running very slow, triggering the “sync” notification extremely often

#### What did you expect?

Instant update. If I compare to for example FluffyChat element X is very slow

#### What happened instead?

Long load times make the experience low

### Your phone model

IPhone 12 Pro, IPad Pro, MacBook Pro M1 (same result on all devices)

### Operating system version

Tried on 16 and 17

### Application version

1.1.7 (53)

### Homeserver

Synapse 1.86.0

### Will you send logs?

How can it be exported, and I can attach it

**Comment by kittykat** [comment]
@alekslyse Can you please update the issue to include which version of the app you're testing against and other details requested in the template?

**Comment by alekslyse** [comment]
> @alekslyse Can you please update the issue to include which version of the app you're testing against and other details requested in the template?

I did update it now. Please ask if any other questions

**Comment by stefanceriu** [comment]
As far as I'm aware we haven't had any other complaints like this so I'm inclined to say it's either something in your configuration or you were just unlucky and caught a buggy app version. Did anything change in the past months?

**Comment by pixlwave** [comment]
Closing this as stale (plus we now have SSS which changes everything anyway).
