### ISSUE TITLE
Verification Request from other devices

### ISSUE THREAD

**Issue by ghost** [element-hq/element-x-ios#1227]
### Steps to reproduce

1. Be signed in and verified in Element X on Device A (Element X 1.1.7 (269) on iPhone 12 mini)
2. Be signed in and verified in Element on Device B (Element 1.5.32 Android on Fairphone 4)
3. Sign in on Element X Android on Device C (Element X 0.1.0-nightly June 30, 2023 build)
4. Tap Continue to request verification on the _Access your message history_ prompt

#### What did you expect?
Verification request from Device C should show up on both Device A and Device B

#### What happened instead?
Only Device B showed the request, Device A running Element X iOS did not.

### Your phone model

iPhone 12 mini

### Operating system version

iOS 16.5

### Application version

1.1.7 (269)

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by ashughes1** [comment]
Rageshake:
https://github.com/vector-im/element-x-ios-rageshakes/issues/534

**Comment by manuroe** [comment]
The feature is currently not implemented. It will be done later.

**Comment by ara4n** [comment]
i can't find a tracking bug for this, so reopening this one.

**Comment by richvdh** [comment]
See also https://github.com/element-hq/element-x-android/issues/3120

**Comment by richvdh** [comment]
Underlying rust-sdk issue: https://github.com/matrix-org/matrix-rust-sdk/issues/3595
