### ISSUE TITLE
Timeline flashes stale messages on entering a room (especially after SS expiration)

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#1234]
### Steps to reproduce

1. Enter a room that you haven't viewed before in the current session (you may potentially need to wait for SS expiration)
2. As the room history syncs, watch the timeline flicker / spasm for a few frames (showing stale messages from ~20 messages ago), and recover again.

This video shows what the flashing looks like (in this instance it's triggered by a proxy misconfiguration bug causing SS to expire every few seconds):

https://github.com/vector-im/element-x-ios/assets/1294269/36164c6f-977a-41c4-86fd-790d1882c773

#### What did you expect?

Timeline that doesn't flicker horribly 

#### What happened instead?

Flickering spasming timeline

### Application version

271

### Will you send logs?

No

**Comment by ara4n** [comment]
This now manifests itself as a an abrupt bouncing animation rather than a flash thanks to the timeline animations, which is slightly less undesirable but still a problem.

**Comment by ara4n** [comment]
this still happens loads.

**Comment by ara4n** [comment]
still happens.

**Comment by manuroe** [comment]
I haven't seen it for a while
