### ISSUE TITLE
Holes in the room list, when filtered

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#1245]
### Steps to reproduce

1. Was in room list
2. Filtered on Element
3. two entirely blank entries in the filtered room list showed up.

#### What did you expect?

no holes, especially when filtered (how can it filter in holes?)

#### What happened instead?

holes

### Application version

271

### Will you send logs?

No

**Comment by manuroe** [comment]
probably related to https://github.com/vector-im/element-x-ios/issues/1157.
