### ISSUE TITLE
Unread state doesn't look to be local-echoed in the roomlist

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#1285]
### Steps to reproduce

1. Go into an unread room
2. Immediately go back to the roomlist
3. Observe that the room is marked as unread for a bit, until it subsequently updates as read.
4. Assume the lag is because we don't model local echo for unread state.

#### What did you expect?

If I read a room by joining it, I expect the room to immediately be marked as read, rather than hang around as unread until it slowly updates - as remote echo feels slow and clunky, especially on bad connections or with overloaded/slow servers.

#### What happened instead?

Perception of clunkiness.

### Application version

279

### Will you send logs?

No

**Comment by ara4n** [comment]
see also https://github.com/vector-im/element-x-ios/issues/639

**Comment by manuroe** [comment]
Should be fine now
