### ISSUE TITLE
Room timelines flash raw matrix IDs before showing the profile displayname 

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#1287]
### Steps to reproduce

1. Open a largeish room
2. At least some of the senders are shown with raw mxids and default avatars (i.e. without profiles) for a second or so
3. And then the mxids resolve to actual displaynames.
4. Feel unsettled at the clunkiness.

Looks like this:

https://github.com/vector-im/element-x-ios/assets/1294269/5406fe6b-006f-45bc-a9ca-610cf6e6583a

#### What did you expect?

We should have the correct profiles available to us from the m.room.member events in the room already; we shouldn't be "fixing up" the profiles in retrospect and thus the 'flash of markup' shouldn't be happening.

#### What happened instead?

flash of raw mxid, which is ugly and clunky and makes everything feel unpolished.

### Application version

279

### Will you send logs?

No

**Comment by pixlwave** [comment]
This is a consequence of not including `m.room.members` in the sliding sync request to reduce its size. We load the `m.room.members` events upon creating the `RoomProxy` just before showing the room.

Maybe this will be fixed by having a cache again.

**Comment by stefanceriu** [comment]
Having seen this in quite some time now, closing until hearing different
