### ISSUE TITLE
Local echo for file upload.

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#1288]
### Steps to reproduce

1. Upload an image
2. Nothing appears in the timelime until remote echo of the event has bounced off the server.

#### What did you expect?

Local echo of the thing you're trying to send, both while you're sending it (see https://github.com/vector-im/element-x-ios/issues/1283) and after it's sent.

#### What happened instead?

Upload appears like it's fallen into the void (especially if server is slow, overloaded, or bad network) - or, alternatively, suddenly unexpectedly pops the timeline a second or so later once the remote echo comes in.

### Application version

279

### Will you send logs?

No

**Comment by Velin92** [comment]
Requires: https://github.com/matrix-org/synapse/pull/15503.

**Comment by manuroe** [comment]
I removed the scheduled labels. We want to it later in this epic: https://github.com/vector-im/element-internal/issues/433

**Comment by manuroe** [comment]
Was done cross-platform in https://github.com/element-hq/element-meta/issues/2549.
