### ISSUE TITLE
Bad error handling when alone in a room

### ISSUE THREAD

**Issue by kittykat** [element-hq/element-x-ios#1349]
### Steps to reproduce

1. In a room where you're on your own
2. Reply to a message
3. See a popup saying "You are alone in this chat, would you like to invite them back?"
4. Click "Invite"

#### What did you expect?
String is "You are alone in this chat, would you like to invite someone?" - there was never anyone else in that room before
I can invite people after clicking "Invite"

#### What happened instead?
Error after clicking "Invite"

### Your phone model

iPhone 11

### Operating system version

16.5.1

### Application version

1.2.1 (293)

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by VolkerJunginger** [comment]
cannot reproduce.
