### ISSUE TITLE
Read marker incorrectly shown

### ISSUE THREAD

**Issue by germain-gg** [element-hq/element-x-ios#1438]
### Steps to reproduce

1. Send a message in a thread from Element Web
2. Make sure it's the last event in the room 
3. Open EX and view the room 

#### What did you expect?

For the message to appear and that's it...

#### What happened instead?

I had a read marker line saying that the message I sent was "new
I would not expect to see that for messages I sent from other devices 

### Will you send logs?

No

**Comment by kittykat** [comment]
@germain-gg I can't reproduce this, please attach a rageshake and app version details :+1:

**Comment by germain-gg** [comment]
Done, you'll be able to find the app version in the rageshake

**Comment by pixlwave** [comment]
Is this only when the message is inside a thread?

**Comment by germain-gg** [comment]
I'm not quite sure, I have noticed that with a threaded message, but have not actively spent time to reproduce in all other scenarios

**Comment by VolkerJunginger** [comment]
Cannot reproduce
