### ISSUE TITLE
Ability to select & copy text from messages.

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#1478]
**Is your feature request related to a problem? Please describe.**

As a user, I often want to reply to specific sections of long messages rather than the whole message.  However, I can't select specific text from bubbles as long-tap == context menu, not selecting text.

**Describe the solution you'd like**

Have an "Info" or "View message" option on the context menu which displays the message fullscreen (as a card popup perhaps), with selectable text, to let users select and copy-paste partial bits of it.  The same view could also display metadata about the message, as well as viewing source for developers.

**Describe alternatives you've considered**

I'm not suggesting we figure out how to make long-tap select text instead (we did this in Amdocs UC, and it caused reliability nightmares in terms of being able to reliably tap on links).

@stefanceriu points out that a workaround could be to copy the whole message and paste it into the RTE, and then edit it fullscreen there, but the fact that you'd have to trim away the bits you *don't* want (having pasted the whole thing) rather than just selecting the bits you *do* want in the first place feels even clunkier than a 'View message' button, which is not dissimilar to how you view thumbnails for images/videos etc fullscreen.

**Additional context**
Literally none of the other apps appear to provide this functionality, so this could be a really nice differentiator, as well as scratching an itch i hit at least once a day.

**Comment by pixlwave** [comment]
This was implemented in #2925 (although admittedly there is now a conflict of gestures on iOS 18, but that's a separate issue).
