### ISSUE TITLE
Room is stuck as unread if the most recent event is not visible.

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#1479]
### Steps to reproduce

1. Find a room where the most recent events are not visible (e.g. i have one here with a reaction and then an edit)
2. The room is shown as unread in EIX in the room list
3. View it
4. Go back to the room list
5. Room is still shown as unread

==> stuck unread. EW would be proud.

#### What did you expect?

No stuck unread messages.

#### What happened instead?

Stuck unread.

### Application version

339

### Will you send logs?

Yes

**Comment by ara4n** [comment]
p.s. i only started seeing these in the last few days, so it may be a recent regression.

**Comment by ara4n** [comment]
@pixlwave says this is because started sending read receipts when we thought the user read a message, to match EAX (rather than as soon as the room is opened). so we need to be smarter about when to send them.

**Comment by bnjbvr** [comment]
https://github.com/matrix-org/matrix-rust-sdk/pull/3119 should help with this, as it provides a method to mark a room as read (that sends a read receipt to the latest event, be it visible or not in the timeline). Let's see how it goes after the apps update the SDK.

**Comment by Velin92** [comment]
Fixed in the latest nighty

**Comment by manuroe** [comment]
Reopened because there is still a case where we have the bug. If the last event is a threaded message, the room stays unread. See the last rageshake.

**Comment by bnjbvr** [comment]
@manuroe The rageshake doesn't include any `compute_unread_counts` logs, which is weird because it says it should, so I can't investigate the failure further, unfortunately.

**Comment by bnjbvr** [comment]
The latest rageshake from @manuroe (thanks!) shows it's the issue solved by [MSC4102](https://github.com/matrix-org/matrix-spec-proposals/pull/4102). in https://rageshakes.element.io/api/listing/2024-02-16/140348-MQXGNP3J/logs-0001.log.gz :

> 2024-02-16T13:59:28.720777Z TRACE matrix_sdk_ui::timeline: sending receipt | crates/matrix-sdk-ui/src/timeline/mod.rs:721 | spans: mark_as_read{receipt_type="m.read" room_id="!mQphBNsunwlFWImZCg:matrix.org"} > send_single_receipt{receipt_type="m.read" thread=Unthreaded event_id="$yFQnSiMXamdyhLHPocwFWzrIWfIFocEM6iTdzL8iNKA" room_id="!mQphBNsunwlFWImZCg:matrix.org"}

We're sending an unthreaded read receipt for `$yFQnSiMXamdyhLHPocwFWzrIWfIFocEM6iTdzL8iNKA`.

The next sync returns:

> 2024-02-16T13:59:31.176781Z [...]
> "$yFQnSiMXamdyhLHPocwFWzrIWfIFocEM6iTdzL8iNKA":{"m.read":{"@Manu:matrix.org":{"ts":1707322244119,"thread_id":"$iYu51tMDt1g35qqgLPc5fs1jLDQYfNPdiucWoHIWjaM"}}}}}

So the unthreaded receipt is not forwarded, and we get the threaded receipt instead, which EX ignores, resulting in the stuck unread.

**Comment by anoadragon453** [comment]
A [fix for this](https://github.com/element-hq/synapse/pull/16927) has merged into Synapse and is expected to be included in the v1.102.0 release. [v1.102.0rc1](https://github.com/element-hq/synapse/releases/tag/v1.102.0rc1), which includes the fix, has been deployed to matrix.org as of yesterday.

**Comment by manuroe** [comment]
We should be good on this now
