### ISSUE TITLE
Rapidly reacting to msgs can apply the reaction to entirely the wrong msg

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#1485]
### Steps to reproduce

1. Try to react to the last two messages in a room (first the penultimate one, then the most recent one)
2. Second reaction ends up applied to the topmost(!) visible message on the timeline, not the bottommost.
3. Feel very confused; remove the spurious reaction and try again in the right msg; this time it works.

It’s possible the echo had not yet been received for the first reaction when the second was sent.

#### What did you expect?

reactions should apply to the msg you react to; not the one ~10 events previous.

### Application version

340

### Will you send logs?

No

**Comment by VolkerJunginger** [comment]
Cannot reproduce
