### ISSUE TITLE
Edits are not locally echoed.

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#1493]
### Steps to reproduce

1. Open app on slowish data
2. Edit a message
3. Observe the edit doesn’t show up in the UI, it looks like it just fell into the void
4. Notice the app is still showing a Syncing… spinner
5. Wait for the spinner to eventually go away
6. See the edit show up in the timeline

#### What did you expect?

edits should be locally echoed immediately (and show an unsent->sent receipt on the msg in question) rather than be invisible until remote echo kicks in.

#### What happened instead?

had to wait for remote echo, which makes the app feel slow and flakey.

### Application version

341

### Will you send logs?

No

**Comment by ara4n** [comment]
empirically edits echo locally now

**Comment by ara4n** [comment]
this has regressed around build 691

https://github.com/user-attachments/assets/282130fd-58e8-474b-946a-a83852619683

**Comment by stefanceriu** [comment]
I think this is working properly now.

**Comment by ara4n** [comment]
alas, it is not, on 834 with persistent event cache at least: this video shows an edit failing to be reflected in the timeline after reopening a room (although after a few seconds it fixes itself)

https://github.com/user-attachments/assets/a00bc13c-0101-4c3c-bd83-06dfb2029c0a
