### ISSUE TITLE
Separate tab for rooms and DMs

### ISSUE THREAD

**Issue by ShadowJonathan** [element-hq/element-x-ios#1531]
#### Is your feature request related to a problem? Please describe.

Right now, EX is not too usable, due to the high amount of rooms I've joined causing the room list to constantly update, and DM rooms not being easily filter able in there, together with no easy view/filter for unread rooms.

#### Describe the solution you'd like

At least, a tab that separates rooms with DMs, then I can use EX to quickly reply and participate in DMs, as the sliding sync has a definite benefit over the normal element apps, and I want to take advantage of that.

#### Additional context

I understand that a full-fledged spaces integration is not yet attainable this early in development, but I'd at least like to be able to use this app for DMs, so that it's more usable in the testing phase

**Comment by s3ase** [comment]
I think this might have been solved
