### ISSUE TITLE
Rooms with unread messages are not flagged in the room list.

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#1616]
### Steps to reproduce

* Open the app for the first time in a little while
* Look at the roomlist on a busy account 
* All the rooms have unread messages
* Some of them have green dots, some of them don't.
* The pattern looks to be that rooms which have triggered notifications get a green dot, but others do not, so the user has to guess based on the room list order which rooms are unread and which aren't.
* According to @amshakal all rooms with unread messages should have a green dot (unless they are explicitly muted).

#### What did you expect?

Users should never have to guess or infer which rooms have unread messages (e.g. by inferring based on the room list order, or by having to play spot-the-difference on room previews)

#### What happened instead?

Users are forced to jump through hoops to try to keep track of which rooms they have read or not.

### Application version

371

### Will you send logs?

No

**Comment by kittykat** [comment]
@amshakal Can you please confirm what the markup should be like for rooms with new messages which do not notify the user? If we mark all new messages with green dots, then it will be impossible to find rooms we care about.

Having reviewed the designs, it's not clear if there are two different greens for unread rooms and if the rooms without a marker are all read

**Comment by amshakal** [comment]
Kat the rooms user cares about is defined by what setting they use for that room. So I am not sure what's not clear in the designs. If they "care about a room" they will get a dot, if they only care about mentions, they will only be notified for mentions and if they dont care about a room, that room will be muted.

**Comment by ara4n** [comment]
Proposal: in order to rapidly unblock this before Ignition and gather more data we could:
 * Highlight timestamps for rooms whose timestamp has changed (i.e. has unread msgs)
 * Give a setting to disable this to see if users dislike it so much they disable it.

cc @amshakal

**Comment by stefanceriu** [comment]
Had a look at this from the techincal point of view. We currently do not have any way of knowing if a room has any unread messages. Neither the Rust SDK nor the proxy have that information. What we would need to do is compute that based on read receipts but that's non-trivial.
Started 2 discussions about it [here](https://matrix.to/#/!qSsPTKDfMGYqhgiLPJ:flipdot.org/$c8DyoC-92FAq5agxbnI-TB-5LPL-z3eDnuVI1VPWa0w?via=flipdot.org&via=matrix.org&via=element.io) and [here](https://matrix.to/#/!kCCQTCfnABLKGGvQjo:matrix.org/$QVqH6x6xPiPdhOoLyR2ircBWsiB85qD-JuQA5-UhSF0?via=matrix.org&via=element.io&via=ergaster.org) but the conclusion is that this is not doable in such a short timeframe if we want good results.

Implementing this properly should be done as a stand alone project and will most likely touch on 3 key parts:
* compute if a room is unread or not, without considering notification settings
* compute notifications and mentions properly (highlighs)
* mark the correct event as read (e.g. missing edits, poll responses etc as their hidden from the timeline)

We should learn from the lessons web gathered and converge on a solid solution rust side.

**Comment by tezlm** [comment]
This would be great, but does [the spec](https://spec.matrix.org/v1.8/client-server-api/#actions) even support it? It looks like there's only `highlight_count` and `notification_count`, but there's no way of incrementing either counter without `notify`?

**Comment by ara4n** [comment]
Only clients know when they have unread messages, because only clients know a) what event types they can render, b) what event type a given message is, if that message is E2EE. So the server can't calculate it; instead the algorithm is:

 * for each room, iterate backwards through the timeline from the most recently received event, until you hit the event for which you last sent a read receipt, and as soon as you find a displayable event, mark the room as unread.
 * if you don't have the full timeline available (because your client has only loaded 1 page of msgs, having just synced) and  that timeline is all invisible messages, you could assume that the room should be considered unread rather than continuing to backpaginate to find a visible message: after all, a room with pages worth of invisible messages is clearly active, so it's not unreasonable to flag it as needing attention. This is what Element Web does (or did, pre-threads). However, it's an optional optimisation; the alternative is to keep paginating the room until you either find a visible event or you hit your read marker.

The common case is that most event types are visible (with the exception of floods of invisible live-location sharing beacons), so this will typically very rapidly determine if a given room is unread or not.

Now, it seems that threaded matrix clients send read receipts for threaded messages which aren't backwards compatible with normal read receipts.  So, the act of reading a message on a thread will not mark that room as read on a unthreaded client - which will therefore see a false positive unread notification on that room if that message was the most recent one in the room.  This will feel a little flakey, but also inevitable until EX becomes thread-aware.

**Comment by ara4n** [comment]
i think these mean "you have overridden notifications in this room to only push you if you are mentioned".

**Comment by kongo09** [comment]
> i think these mean "you have overridden notifications in this room to only push you if you are mentioned".

If that's the case, I feel they shouldn't be there. This pattern feels novel and makes the screen more busy then necessary. It also breaks with the pattern of

- either show a notification -> bubble
- or show that a notification cannot happen -> strike through loudspeaker

There is no concept I'm aware of of a "notification will happen here" symbol, so this doesn't fit any mental model.

I'm a big fan of how simple WhatsApp and Telegram do this. If you get a notification, it's shown (in brand color). If the channel / room is muted, you get the crossed out loudspeaker and Telegram in addition tunes down the volume of the bubble from brand color to grey (plus place the loudspeaker in a different place from WhatsApp).

In my view it's really easy to extend this to our "overridden mentions" case: you leave the loudspeaker as the base setting is mute, but the low volume Telegram notification would change to a high volume brand color notification again for a mention.

Combine this with sorting all "mentions" to the top in their own section, we could even eliminate the third red color and get even more structure and accessibility in.

**Comment by manuroe** [comment]
The app has now a true implementation of the unread status and a filter to check unread rooms. We are working on a next iteration with https://github.com/element-hq/element-meta/issues/2358 but it is going further than this original issue.

Can we say we are happy with the current behavior of the app? 
I chose the happiness path and I am closing this issue. Please reopen if we are not aligned.
