### ISSUE TITLE
"Invite user to Element X" button doesn't invite users to EX.

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#1627]
### Steps to reproduce

1. Hit "start a chat" button
2. Select "Invite people to Element X"
3. App tries to send a matrix.to link... which will not invite people to EX (until we add EX to matrix.to, hook up matrix.to URL deeplinking for user IDs, add registration to EX, and hook up a [copy this link](https://github.com/vector-im/element-meta/issues/248) flow like Google Photos to guide the new user into the flow of DMing their inviter.  Or alternatively do a 3PID invite by email).

#### What did you expect?

"Invite user to Element X" should either share a link out of band to the target user which will mean the user ends up onboarded into Element X, or send a 3PID invite by email to the target user which has the same effect.

Given there's a lot of work needed to make this smooth, it might be easiest to change the label on the button? "Invite user to talk"? Rather than explicitly saying it's going to invite them to EX, when it isn't.

#### What happened instead?

The link will onboard the user into Matrix, not EX per say.

### Application version

373

### Will you send logs?

No

**Comment by Velin92** [comment]
@VolkerJunginger yeah actually this might require a lot of work, but in the meantime @ara4n is at least a better way to communicate that we are inviting to matrix and not to element X the other user

> Given there's a lot of work needed to make this smooth, it might be easiest to change the label on the button? "Invite user > to talk"? Rather than explicitly saying it's going to invite them to EX, when it isn't.

**Comment by VolkerJunginger** [comment]
Yes, lets change the copy to "Invite users to talk".

**Comment by manuroe** [comment]
There is no more button
