### ISSUE TITLE
New avatar colours should only be the 6 from the extended palette

### ISSUE THREAD

**Issue by callumu** [element-hq/element-x-ios#1631]
### Steps to reproduce

Viewing avatar and user name colours in the room list and timeline

### Outcome

It seems like we're using all colours from the design system for avatar colours and user names but we should only use the 6 from the extended palette, see: https://www.figma.com/file/iIjwDl9HjaaF1vlDU96h8K/INBOX-%C2%B7-Compound-iOS%2FAndroid-Components?type=design&node-id=713%3A31043&mode=design&t=1DfqXLrkB905dK6c-1

### Will you send logs?

No

**Comment by pixlwave** [comment]
This was a deliberate compromise for now to align with Web which is also using 8 colours on `develop`. We will switch all the platforms to use 6 at the same time for consistency.

**Comment by callumu** [comment]
Oh okay that makes sense. Thanks for the explanation

**Comment by pixlwave** [comment]
Fixed by #2438.
