### ISSUE TITLE
Don't lose app context when tapping on (unimplemented) pills

### ISSUE THREAD

**Issue by nadonomy** [element-hq/element-x-ios#1645]
**Is your feature request related to a problem? Please describe.**

Tapping on a pill (stylised as a link, presumably fallback) takes you out of context to browser.

https://github.com/vector-im/element-x-ios/assets/4626865/279032d5-6993-4f1a-8bd1-6570666fb119

**Describe the solution you'd like**
Stay in context in the app.

**Comment by pixlwave** [comment]
This has now been implemented.
