### ISSUE TITLE
Don't show redundant controls when previewing media

### ISSUE THREAD

**Issue by nadonomy** [element-hq/element-x-ios#1646]
**Is your feature request related to a problem? Please describe.**

![image](https://github.com/vector-im/element-x-ios/assets/4626865/7edb3cc7-bd5e-4eab-9ac0-618e028cc683)

Redundant controls shown when sending media:

1. Title bar with file name. iOS works hard to abstract file names away. Drop-down doesn't have anything useful. Little utility. 
2. Share interaction prompting native share sheet. Redundant while sharing in EX. 
3. Play button (bottom right) redundant given main play button in centre.

**Describe the solution you'd like**
To just preview the media I'm sending, and cancel or continue.

**Comment by NoFr1ends** [comment]
What throws me off about the play button in the bottom right is that most apps place the send button there when you want to sent media, so I always press it instead of Continue in the Top Right (which is also harder to reach)

**Comment by stefanceriu** [comment]
Similar to #1647 everything you see in there is Apple's own QLPreviewController.

The best I can do in this case is completely hide the top file name bar and hide the bottom share button but I cannot remove the bottom play button as we will lose both the pause button and the timeline

**Comment by nadonomy** [comment]
@stefanceriu I think we'll need to think beyond Apple's QLPreviewController in that case. Most other apps, for good reason, hide anything redundant or distracting to the core user goal trying to be accomplished.

I guess we can pick this up in detail when it get's scheduled.

**Comment by pixlwave** [comment]
This is now much better overall
- The preview is fullscreen, not a sheet
- On iOS 18 the preview starts in the "tapped" mode where all window chrome is hidden and the background is black.
