### ISSUE TITLE
VoIP unsupported event error 

### ISSUE THREAD

**Issue by germain-gg** [element-hq/element-x-ios#1661]
### Steps to reproduce

![IMG_67FE2474B32B-1](https://github.com/vector-im/element-x-ios/assets/769871/1599f19f-2e00-48c8-9640-a75e61c16845)

#### What did you expect?

For the events to not throw

#### What happened instead?

Not that

### Will you send logs?

No

**Comment by stefanceriu** [comment]
Fixed in https://github.com/element-hq/element-x-ios/pull/2531 and https://github.com/ruma/ruma/issues/1739
