### ISSUE TITLE
Send receipt is shown on remote echo, not /send 200 OK

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#1668]
### Steps to reproduce

1. Send a message in a large room like Matrix HQ
2. Stare at the “empty circle” sending status for ~5s
3. Eventually it gets a tick
4. Conclude the app is slow

#### What did you expect?

I’m assuming that we’re waiting to see a remote echo from the server before we declare a message sent, which is why it is so slow. Instead, we can mark the msg as sent as soon as we receive a 200 OK from the /send.

#### What happened instead?

Perception of app talking >2x longer to send messages than it really does.

### Application version

380

### Will you send logs?

No

**Comment by pixlwave** [comment]
> I’m assuming that we’re waiting to see a remote echo from the server before we declare a message sent

This isn't what is what we're doing code-wise:
https://github.com/vector-im/element-x-ios/blob/bd4ee92124b17ce428c6ebfb894ba6b19f6bb3bf/ElementX/Sources/Screens/RoomScreen/View/Supplementary/TimelineItemStatusView.swift#L47-L51

**Comment by unclejay80** [comment]
is this still relevant or already fixed

**Comment by pixlwave** [comment]
Yeah you're right. I don't think this was actually the case at the time and it isn't now. I'll close this issue.
