### ISSUE TITLE
There is no way to copy a user’s matrix id from their member info page

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#1669]
### Steps to reproduce

1. Need to access a user’s matrix id (eg to enter it into moderation tooling)
2. Open their member info by tapping on their avatar or from the member list (yay!)
3. See their mxid shown
4. Try to long-tap or tap on it to select it to copy it
5. …Instead see a zoomed form of their avatar.
6. …wince, especially if you were trying to ban an abusive user.
7. have to manually remember their mxid and type it back in, instead

#### What did you expect?

Copyable text field; only tapping on the avatar should zoom it, not the whole member info.

#### What happened instead?

Zoomed avatar

### Application version

380

### Will you send logs?

No

**Comment by ara4n** [comment]
this has regressed (build 722 on iOS18)

**Comment by pixlwave** [comment]
Seems like this was replaced by https://github.com/element-hq/element-x-ios/issues/3405
