### ISSUE TITLE
Retry behaviour is unusable; messages should always send in the order they were written, and should not have to be individually retried by the user.

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#1670]
### Steps to reproduce

1. Send some messages when on bad connectivity (e.g. wifi whose router is disconnected, or when server is being restarted)
2. Some of them may show as red (failed to send)
3. Some of them may go through.
4. Messages are not sent in the right order, and there's nothing you can do about it.
5. You then have to manually re-send each message which has failed.
6. To make matters even worse, the re-send button is inexpliably hidden from the context menu: https://github.com/vector-im/element-x-ios/issues/1186
7. ...and the hit mask on the bubble to trigger the re-send button is fiddly.

Here's a video of me spending a full minute trying to get messages to send in the right order.

https://github.com/vector-im/element-x-ios/assets/1294269/b8f6401c-4571-4cfc-bea3-e2f8828ab310

#### What did you expect?

1. Messages should ALWAYS send in the order they were typed. Whether they are in state sending or unsent in a given room, they should sit in a single ordered queue.  If you type three messages and message 1 and 2 fail but 3 sends, then the current behaviour, which the user can do *NOTHING* about, is that the messages will be sent in order 3,1,2 (or 3,2,1 if they retry them in the wrong order).  I.e. message 3 will always be out of order, making the user look like they are talking gibberish.
2. @kongo09 makes a good case that the user should never need to explicitly trigger a resend; the app should do it automatically whenever it comes back into connectivity (or do so in the background), and if the user decided in retrospect that stuck messages are no longer relevant they can go through deleting them.
3. That said, given the user might know better than the app when to retry to send messages and "kick" the retry queue, I would personally still give an affordance to the user to let them kick the app to (re)send a message. This could be simply by sending a new message to flush the queue, or by having a "retry now" button on the context menu for messages which are stuck in sending/failed state.

#### What happened instead?

Extreme frustration at the app sending my messages in the wrong order, and forcing me to manually retry them one by one.  Especially given this was identified last year on the legacy apps as a Chronic Bug... and fixed there on all 3 platforms.

### Application version

380

### Will you send logs?

No

**Comment by Velin92** [comment]
We only have a single message re-send API as of right now, we would need a global re-send function to solve this probably.

**Comment by ara4n** [comment]
we now have a msg queue that works, i think.
