### ISSUE TITLE
Signing out sometimes crashes the app.

### ISSUE THREAD

**Issue by pixlwave** [element-hq/element-x-ios#1717]
Have personally only seen this during debug, I checked the object and its a `ClientProxy` instance.

Version 1.2.9 on `develop`

<img width="1064" alt="Screenshot 2023-09-15 at 10 15 26 am" src="https://github.com/vector-im/element-x-ios/assets/6060466/5c4fab68-5a4f-4a3d-9230-6301b0bf3cb4">

**Comment by pixlwave** [comment]
Based on the log message, seem likely this is due to the deinit:

```
deinit {
    client.setDelegate(delegate: nil)
    stopSync()
}
```

**Comment by manuroe** [comment]
Should be fixed now
