### ISSUE TITLE
RichTextEditor fails editing message 

### ISSUE THREAD

**Issue by stefanceriu** [element-hq/element-x-ios#1746]
The rich text editor fails configuring itself to edit mode and stays empty

STRs:
* send yourself a message the contains both normal text and a code block
* try editing that message
* see the composer not pick up the original text

Example
"""
123

```
123
```
"""

**Comment by manuroe** [comment]
@stefanceriu will check it.

**Comment by stefanceriu** [comment]
This is still a problem but only when the RTE is in markdown mode

**Comment by giomfo** [comment]
@stefanceriu I don't reproduce this issue even by disabling the "Text Formatting" option. What do you mean by "RTE in markdown mode"?

**Comment by stefanceriu** [comment]
As in, Settings -> Advanced settings -> Rich text editor: Off


https://github.com/element-hq/element-x-ios/assets/637564/9bfb58b3-5152-4a29-932e-33d783ceefdb

**Comment by Velin92** [comment]
seems to be fixed on the latest versione
