### ISSUE TITLE
RichTextEditor code block editing artefacts

### ISSUE THREAD

**Issue by stefanceriu** [element-hq/element-x-ios#1747]
Try editing a message that only contains a codeblock

1) Cancelling the editing leaves the cursor in the wrong position. Entering a character fixes it

<img width="261" alt="Screenshot 2023-09-19 at 08 46 16" src="https://github.com/vector-im/element-x-ios/assets/637564/b0be4c9b-fbac-4599-84f1-7813340a78fa">

2) Delete everything within the code block before cancelling the edit. The codeblock background box remains in the composer

<img width="334" alt="Screenshot 2023-09-19 at 08 47 04" src="https://github.com/vector-im/element-x-ios/assets/637564/6ded2beb-12b0-4351-b0bb-9befb1b88321">

**Comment by alfogrillo** [comment]
2. should be fixed by https://github.com/matrix-org/matrix-rich-text-editor/pull/829

**Comment by Velin92** [comment]
duplicate of https://github.com/element-hq/element-x-ios/issues/2656
