### ISSUE TITLE
Replies silently can entirely disappear if sent on bad connectivity

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#1758]
### Steps to reproduce

1. Get on a bad network
2. Send a reply
3. Observe no local or remote echo, or failed msg; msg is silently not sent.

#### What did you expect?

Reliable sending

#### What happened instead?

Messages falling into the void

### Application version

390

### Will you send logs?

Yes

**Comment by jplatte** [comment]
SDK issue: https://github.com/matrix-org/matrix-rust-sdk/issues/2582

**Comment by ara4n** [comment]
this still happens once every few days for me:

![image](https://github.com/element-hq/element-x-ios/assets/1294269/b74b3adc-6467-4743-a6e4-610c81b8f0f4)

**Comment by Hywan** [comment]
This issue is already fixed by https://github.com/element-hq/element-x-ios/issues/1758 even if the `SendQueue` has no persistent storage and lives only in-memory for the moment. We can close this issue 🙂.
