### ISSUE TITLE
Duplicate date markers when you send messages rapidly into a room

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#1763]
### Steps to reproduce

1. Open a room where nothing's happened yet today
2. Send two messages rapidly (not waiting for the remote echo on the first one)
3. See duplicate data marker on both messages:

![IMG_2962](https://github.com/vector-im/element-x-ios/assets/1294269/a5555b6f-0b53-43b1-b562-ab8b46fbab6b)

This is https://github.com/matrix-org/matrix-rust-sdk/issues/2590 - tracking here for EXI triage porpoises

#### What did you expect?

No dup date markers

#### What happened instead?

Dups

### Application version

390

### Will you send logs?

No

**Comment by ara4n** [comment]
see also https://github.com/element-hq/element-x-ios/issues/1763

**Comment by bnjbvr** [comment]
https://github.com/matrix-org/matrix-rust-sdk/pull/3254 should fix all issues related to redundant date separators (note there can still be spurious date separators, if the app decides to hide some events the SDK timeline returns).

It will require an update of the SDK in apps. If you observe any issues with it, please enable the following log level: `matrix_sdk_ui::timeline::day_dividers=TRACE` as this will make rageshakes super useful.
