### ISSUE TITLE
Ability to override OS light/dark theme settings

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#1766]
**Is your feature request related to a problem? Please describe.**
Many people prefer the dark theme to the light theme (e.g. the bloom effect works) - but they don't want to turn their whole OS dark.

**Describe the solution you'd like**
Provide ability to override the theme to dark theme for the app.

**Describe alternatives you've considered**
Shame iOS doesn't let this do this automatically

**Comment by stefanceriu** [comment]
Handled in https://github.com/element-hq/element-x-ios/pull/2084
