### ISSUE TITLE
Empty Room appears in Element X room list

### ISSUE THREAD

**Issue by BertramBassett** [element-hq/element-x-ios#1781]
### Steps to reproduce

1. Where are you starting? What can you see?

The room named Empty Room appeared at the bottom of the room list after the last update. It has zero users. It constantly says "Failed loading messages". This extra room doesn't appear in the standard Element iOS app. I have one space with 15 rooms.

2. What do you click?

No click required.

3. More steps…

I attempted to leave the room but it appears to be indestructible.

#### What did you expect?

I didn't expect to see an empty room.

#### What happened instead?

I saw an empty room.

btw, this probably reads even more stupid than it does when I typed it.

### Your phone model

iPhone 11

### Operating system version

<del>iOS 16.6.1</del>. I just updated to 17.0.1 and the issue persists.

### Application version

The version number is not available in Settings.

### Homeserver

matrix.org

### Will you send logs?

Yes.

**Comment by manuroe** [comment]
We received no complaints about it for a time. Please reopen if it is still an issue.
