### ISSUE TITLE
Profiles missing after accepting invite

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#1789]
### Steps to reproduce

1. Accept an invite for a DM
2. Note the room is named correctly with the user’s displayname and avatar
3. However, messages are shown as coming from a raw mxid without an avatar

#### What did you expect?

Accurate profiles

#### What happened instead?

No profiles

### Application version

393

### Will you send logs?

No

**Comment by giomfo** [comment]
I don't reproduce this issue even by inviting the user in a DM with a new contact (v1.5.9). The severity may be decreased
