### ISSUE TITLE
When installed as a macOS app, EXI intercepts EC URLs, but can't render them.

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#1794]
### Steps to reproduce

1. Install EXI as a macOS app
2. Click on an call.element.io link in your calendar
3. It opens in EXI, which say "WebRTC unavailable"

#### What did you expect?

Either EX should work on macOS (given Safari supports WebRTC!) - or we shouldn't try to intercept EC URLs on macOS until it does.

#### What happened instead?

Unexpected breakage.  Given we're not stopping users from installing EXI on macOS (and nor should we, as it works really very well, especially relative to the lumbering beast that is EW), i think we should at least support basic use cases (e.g. not breaking EC calls)

### Your phone model

Macbook Pro :P

### Operating system version

macOS Ventura 13.6 (22G120)

### Application version

393

### Will you send logs?

No

**Comment by ara4n** [comment]
<img width="848" alt="Screenshot 2023-09-25 at 17 18 03" src="https://github.com/vector-im/element-x-ios/assets/1294269/7bb1945f-111a-414c-9d06-4c55c858a8d2">

this is the 10th time i've seen this today :D

**Comment by stefanceriu** [comment]
> Either EX should work on macOS (given Safari supports WebRTC!)

Unfortunately that's not the case, [navigator.mediaDevices](https://github.com/vector-im/element-call/blob/c62a9be2e98f3f5a38eb81cae11928b601239f16/src/main.tsx#L47) isn't available on iOS apps running on Apple Silicon or on Mac Catalyst. 

>  we shouldn't try to intercept EC URLs on macOS until it does.

This is not an option either as we can't tell universal links to ignore just the Mac app.

The only option is to make it redirect to your default browser, but the Mac app will still be launched first.
