### ISSUE TITLE
UTDs should be called “please wait for keys”

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#1796]
### Steps to reproduce

1. Receive a UTD due to federation lag on sending keys
2. Stare at scary UTD msg
3. Instead, shouldn’t it be: “Waiting for keys from the sender…” or something?

#### What did you expect?

nice utd language

#### What happened instead?

utd

### Application version

393

### Will you send logs?

No

**Comment by stefanceriu** [comment]
As part of the key backup work it has been decided to go with `Waiting for this message`
