### ISSUE TITLE
Unable to take photo in landscape mode

### ISSUE THREAD

**Issue by wrjlewis** [element-hq/element-x-ios#1815]
### Steps to reproduce

open EX on ios 
tap a chat 
tap the + icon
tap camera
turn iPhone horizontally
result: lose half the viewfinder and shutter buttons disappear 

#### What did you expect?
To be able to take a photo in horizontal orientation

#### What happened instead?
Buggy visuals, lack of ability to take a photo. 

**Screenshot and video below**

![IMG_9025](https://github.com/vector-im/element-x-ios/assets/1543626/65801ae0-679f-439d-8db4-0868be9a344c)

https://github.com/vector-im/element-x-ios/assets/1543626/b51824a4-7993-4753-817e-040412dd6b0a

### Your phone model

iPhone 12 Pro

### Operating system version

iOS 17.0.1

### Application version

1.3.0 (72)

### Homeserver

Synapse v1.92.3

### Will you send logs?

No

**Comment by stefanceriu** [comment]
I had a look at this a couple of days ago and there's no good way to block a particular screen from rotating (as in this case the controls themselves rotate, not the whole screen). We need to figure out how to work around this particular SwiftUI limitation

**Comment by HealsCodes** [comment]
As a workaround for the time being you can use the volume buttons to take a picture.

There's a number of ways for SwiftUI to block rotation of a specific view or scene. For convenience a few are even listed on SO: https://stackoverflow.com/questions/59140440/swiftui-disable-auto-rotation-of-views#59142675
