### ISSUE TITLE
1:1 VoIP calls are silently discarded

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#1837]
### Steps to reproduce

1. Someone calls you 1:1 from classic Element
2. There is zero evidence of them doing do.

#### What did you expect?

At least a notif and a timeline entry to warn you someone is trying to get in touch.

#### What happened instead?

Nothing.

### Application version

397

### Will you send logs?

No

**Comment by manuroe** [comment]
One proposal in matrix chat was to have a timeline item saying "Bob tried to call you, but Element X does not support legacy 1:1 calls" or similar

**Comment by amshakal** [comment]
I agree, something is needed to let the user know that someone is calling you. Ideally, we would need a notification and a timeline event for - incoming call and a missed call.

**Comment by amshakal** [comment]
I am happy to discuss a bare minimum solution with the team, given the time constraints.

**Comment by ara4n** [comment]
This just bit me with a customer call. The workaround is *so* easy here: "Bob tried to call you, but Element X does not support legacy 1:1 calls" - please can we do it and iterate after if needed, rather than have it get stuck for another month?

**Comment by ara4n** [comment]
@amshakal please can you unblock this? i missed multiple customer calls last week due to EX silently dropping the calls.

**Comment by ara4n** [comment]
@amshakal please (please) can you unblock this? i'm still missing multiple customer calls whenever i'm on the move thanks to EX discarding them.

**Comment by ara4n** [comment]
just missed another customer call due to this; the customer's calling me while i'm chatting to them on EX and it just looks to them as if i'm ghosting their call >:(
