### ISSUE TITLE
Spurious date separators everywhere still

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#1839]
### Steps to reproduce

1. Scroll back in a given room
2. See spurious redundant date separators, potentially related to invisible events?

#### What did you expect?

stable date separators

#### What happened instead?

flakey unstable date separators

### Application version

396

### Will you send logs?

Yes

**Comment by ara4n** [comment]
see rageshake

**Comment by bnjbvr** [comment]
Managed to write a test for this.

**Comment by bnjbvr** [comment]
https://github.com/element-hq/element-x-ios/issues/1763#issuecomment-2013388682
