### ISSUE TITLE
Displayname disambiguation

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#1845]
### Steps to reproduce

1. Two users called Alice join a room with the same avatar; a benign one and and a malicious one
2. The only way to spot messages from the malicious one is to tap on their avatar and read their mxid in the membership list.
3. Instead, when two users have the same (homomorphic) displayname, they should be disambiguated from each other by appending the mxid (in a different text format) so you can spot impersonation attacks.

#### What did you expect?

disambiguated displaynames

#### What happened instead?

no disambiguation; security flaw

### Application version

396

### Will you send logs?

Yes

**Comment by VolkerJunginger** [comment]
@pmaier1 Is this something we will solve once we have decoration / rolled out the tofu concept?

**Comment by ara4n** [comment]
this is nothing to do with tofu or e2ee verification. it's simply to ensure that if someone joins a chat with a displayname of Volker and the same avatar as you, then they are labelled as a potential imposter by also decorating them with a matrix id or similar.

**Comment by timokoesters** [comment]
The sdk side of this seems to be implemented, but the element-x-ios and android don't use it yet: https://github.com/matrix-org/matrix-rust-sdk/blob/3e17fc207246329d6aee928a960ac5cd8dbb5b4f/crates/matrix-sdk-base/src/rooms/members.rs#L66-L67

I've also noticed that the current implementation looks for exact matches. Should the comparison be fuzzier? For example Ignoring whitespace, allowing similar characters like I and l, 0 and O (maybe use a library because unicode is hard). Perhaps even case insensitive?

**Comment by manuroe** [comment]
thanks @timokoesters . We need to implement it on Android too cc @bmarty .
We need to be careful in all the places where disambiguation is needed.

**Comment by bmarty** [comment]
For Member List, we do not have parity on the app, so we need to fix the issue first (iOS on left, Android on right):

<img width="826" alt="image" src="https://github.com/element-hq/element-x-ios/assets/3940906/43c1e48b-828c-4ac7-bce4-395a5ca91957">

If we want to keep the version with Matrix ID (Android), there is no need to disambiguate on this screen.

@VolkerJunginger can you take a decision here?

**Comment by VolkerJunginger** [comment]
Yes, please add the info to iOS.

**Comment by bmarty** [comment]
Also as per the description, we need some design about the rendering. The Matrix Id must have a different format, else anyone can set a displayname to `Matthew (@matthew:matrix.org)` and so impersonate the user. See current status on EXA, i.e. without a different format (from  https://github.com/element-hq/element-x-android/pull/2221#issue-2079051752):
<img width="676" alt="image" src="https://github.com/element-hq/element-x-ios/assets/3940906/87e37142-5445-4838-af87-8487b9b5a473">

Web does:

<img width="631" alt="image" src="https://github.com/element-hq/element-x-ios/assets/3940906/2edee386-0e79-4da6-b494-ee004f1a08ab">

**Comment by bmarty** [comment]
> Yes, please add the info to iOS.

I just realize that Element Web is not showing the MatrixIds in the room member list (except for disambiguation ofc). So it's maybe too technical, and we should instead remove it from Android?

**Comment by Velin92** [comment]
Removed ambiguity in the room members screen and aligned the iOS app to Android here:
https://github.com/element-hq/element-x-ios/pull/2332

Only left to handle notifications (just exposed a way to check that in the SDK [here](https://github.com/matrix-org/matrix-rust-sdk/pull/3011)) and in the timeline

**Comment by Velin92** [comment]
> Also as per the description, we need some design about the rendering. The Matrix Id must have a different format, else anyone can set a displayname to `Matthew (@matthew:matrix.org)` and so impersonate the user. See current status on EXA, i.e. without a different format (from [element-hq/element-x-android#2221 (comment)](https://github.com/element-hq/element-x-android/pull/2221#issue-2079051752)): <img alt="image" width="676" src="https://private-user-images.githubusercontent.com/3940906/296282718-87e37142-5445-4838-af87-8487b9b5a473.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzcwODQsIm5iZiI6MTcwNTA3Njc4NCwicGF0aCI6Ii8zOTQwOTA2LzI5NjI4MjcxOC04N2UzNzE0Mi01NDQ1LTQ4MzgtYWY4Ny04NDg3YjliNWE0NzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTJUMTYyNjI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmM3OTRkMGExYTFhMGQ3ZTA3NjNlMDg3YmM4NDJiNjUyN2E2N2YyNzE1YjkxODI0MWFlZThkNjE1MzUwNjViMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pf_CW09NsxUoBv2j4RxpsSvOALE0E0p19A7xHApnDh4">
> 
> Web does:
> 
> <img alt="image" width="631" src="https://private-user-images.githubusercontent.com/3940906/296282792-2edee386-0e79-4da6-b494-ee004f1a08ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzcwODQsIm5iZiI6MTcwNTA3Njc4NCwicGF0aCI6Ii8zOTQwOTA2LzI5NjI4Mjc5Mi0yZWRlZTM4Ni0wZTc5LTRkYTYtYjQ5NC1lZTAwNGYxYTA4YWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTJUMTYyNjI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTQ3OTZjNWI5MzQzZDZmMjJkOTIzYmQ1NjkwZGQ1NTBhN2Y4ZDE3Mzc2YjY0ZGFiOTRlYmM2MzllYzM4Y2FkOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.s8Mt2GXQLLKGv0L-TmKIISpTcaSPUr-tHqBkrVd4mxY">

@manuroe  @VolkerJunginger do we have an idea on how we want to display the user ID in case of ambiguous display name in the timeline?

**Comment by pixlwave** [comment]
We have this now.
