### ISSUE TITLE
No way to use EX when in an EC call without hanging up the EC call.

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#1882]
### Steps to reproduce

1. Click on an EC link
2. It opens in EX, hooray
3. Want to look at a chatroom in EX while on the call, e.g. to get a link for a document to click on to collaborate
4. Discover that swiping the EC UI away terminates the call.

#### What did you expect?

Call should continue in bg, with some ability to resume (or fully kill it).

If the answer here is "wait until proper huddles land" that's fine by me, ftr.

#### What happened instead?

Call terminates the second you move away from it.  Ironically, it'd be better to have been on the call in MobileSafari.

### Application version

407

### Will you send logs?

Yes

**Comment by pixlwave** [comment]
Fixed by #3190 etc.
