### ISSUE TITLE
I unlocked the bouncing and dancing message easter egg

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#1884]
### Steps to reproduce

1. Go offline
2. View a room which hadn't loaded scrollback yet
3. Watch the timeline reset in a tight loop:

https://github.com/vector-im/element-x-ios/assets/1294269/67bf0feb-1932-4c85-b087-84451095ceab

#### What did you expect?

No reset tightloop; just show the history which was loaded, and a warning that you're offline.

#### What happened instead?

Reset tightloop causing bouncing & dancing message easter egg.

### Application version

407

### Will you send logs?

Yes

**Comment by manuroe** [comment]
It was fixed at some point.
