### ISSUE TITLE
Autofocus composer field when changing room on Desktop

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#1911]
### Steps to reproduce

This is probably specific to running under macOS as an iPad app, but it's annoying:

1. Change room in the room list
2. Start typing in the room
3. Discover the composer isn't focused
4. Manually click on composer every time you change room.

#### What did you expect?

Autofocus composer

#### What happened instead?

No focus

### Your phone model

MBP

### Operating system version

Ventura

### Application version

410

### Will you send logs?

No

**Comment by SpyHoodle** [comment]
This is also the behavior on my iPad Pro. So this is not due to macOS Catalyst exactly, if the iPad version was updated I would suggest this should be fixed too.
