### ISSUE TITLE
Toolbar icons disappear after hiding app on iPad

### ISSUE THREAD

**Issue by marwing** [element-hq/element-x-ios#1918]
### Steps to reproduce

1. Open app on iPad
2. Go back to home screen
3. Wait a few seconds 
5. Open app
6. Notice the toolbar being empty and the view being scrolled up for the title to be in the toolbar

https://github.com/vector-im/element-x-ios/assets/29716248/d7cb2a21-d7c0-4c29-8a94-87549c4d8bf9

#### What did you expect?
![IMG_0122](https://github.com/vector-im/element-x-ios/assets/29716248/ee758913-5631-4501-9dea-abf90bbdeee6)
or at least
![IMG_0124](https://github.com/vector-im/element-x-ios/assets/29716248/65067bd5-386e-482d-b0dc-117e4fdafc2b)

In my opinion, hiding the app should never update the scroll position, so the first image is the actually expected one. 

#### What happened instead?
![IMG_0125](https://github.com/vector-im/element-x-ios/assets/29716248/5811af99-1dd8-45dc-8b06-846137fd7876)

This can be fixed by restarting the app or resizing it small enough to show the room list and the room timeline on different screens (like on the iPhone), e.g., by entering split screen or in stage manager.

### Your phone model

iPad Pro

### Operating system version

iPadOS 17.0.3

### Application version

1.3.3 (76)

### Homeserver

Synapse 1.94.0

### Will you send logs?

No

**Comment by pixlwave** [comment]
As noted by #2604 this also affects the detail's toolbar when a room is selected.

**Comment by kenrachynski** [comment]
Just updated to 1.7.3 and this is still an issue. 

Makes it really hard to report bugs on iPadOS when I can't get to the menus.

**Comment by stefanceriu** [comment]
Well the good news it that Apple introduced [new APIs](https://developer.apple.com/documentation/swiftui/navigationsplitview/init(preferredcompactcolumn:sidebar:detail:)) that would allow us to rewrite a bunch of the code around this. The bad news is that we need to wait until we switch over to iOS 18

**Comment by ledlamp** [comment]
there is not a simple fix for this without rewriting and loosing support for ios 16?

**Comment by pixlwave** [comment]
> there is not a simple fix for this without rewriting and loosing support for ios 16?

To directly answer the question, the new iOS 18 APIs we'd like to use back-deploy to iOS 16, so this change wouldn't directly result in 16 being cut off (although it's possible to use different APIs on different OS versions so it wouldn't necessarily be cut off if the back-deployment wasn't there).

Unrelated to this change, we only intend to guarantee support for the 2 most recent major iOS versions in Element X. There will always be a bit of a "migration" period where we support 3 while we figure out the right point at which we cut off support for the older one.

**Comment by stefanceriu** [comment]
> Well the good news it that Apple introduced [new APIs](https://developer.apple.com/documentation/swiftui/navigationsplitview/init(preferredcompactcolumn:sidebar:detail:)) that would allow us to rewrite a bunch of the code around this. The bad news is that we need to wait until we switch over to iOS 18

As it turns out that's not quite as magical as we hoped but I do *think* I managed to fix the problem in a different way. Let us know if you still see it please.

**Comment by stefanceriu** [comment]
That's great news, thank you for checking!
