### ISSUE TITLE
Session verification fails after transfering phones

### ISSUE THREAD

**Issue by stefanceriu** [element-hq/element-x-ios#1947]
We're receiving reports that the app stops responding to verification attempts after transfering phones (using apple's own magic transfer flow described [here](https://support.apple.com/en-gb/HT210216) at step 5.

What we believe happens is that:
* the keychain gets transferred over (doesn't in a normal backup as per https://developer.apple.com/forums/thread/93373)
* the app group application support directory (including the crypto db) isn't, possibly because it's in an app group or maybe because [we mark it as excludedFromBackup](https://github.com/vector-im/element-x-ios/blob/develop/ElementX/Sources/Other/Extensions/URL.swift#L73)
* the app the uses the token stored in the keychain to restore the old session
* a new crypto db, keys and everything else gets created
* verification stops working as the keys don't match

**Comment by pixlwave** [comment]
Copying a set of steps from #2169

### Steps to reproduce

1. Make an iTunes backup
2. Restore to another device (maybe works with same too, I didn't test)
3. Open Element X
4. Try verifying the new device
5. Verification will always say you cancelled it
