### ISSUE TITLE
Room previews in the roomlist seem much frequently stale than before

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#1977]
### Steps to reproduce

1. Go back to roomlist after having been using app for a while
2. Notice that room previews are very stale
3. Open room; view stale history for a while, until it backpaginates in.

It feels like we're no longer maintaining room previews in the room list sensibly.

#### What did you expect?

Reliable room previews

#### What happened instead?

Somewhere around build 420 it seems to have regressed (not that it was perfect before - https://github.com/vector-im/element-x-ios/issues/1775)

### Your phone model

iPhone 12 Pro Max

### Operating system version

iOS 16.7

### Application version

421

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by manuroe** [comment]
Dup of https://github.com/element-hq/element-x-ios/issues/1775
