### ISSUE TITLE
Accept new invites fails (especially if you have lots of invites in your list?)

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#1979]
### Steps to reproduce

1. Get invited to a room
2. Tap on the push notif for the invite
3. Hit accept on the invite
4. Nothing happens.
5. Wait for the rest of the invites list to load
6. Hit accept a few more times
7. Nothing happens.

Much later (perhaps on the next launch?) accepting the invite works.

#### What did you expect?

Accepting invites should work instantly, with instant local echo, and/or give sensible progress and feedback if it doesn't.

#### What happened instead?

No feedback, pressing the button did nothing.

### Your phone model

iPhone 12 Pro Max

### Operating system version

iOS 16.7

### Application version

41x

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by manuroe** [comment]
We do not have anymore the room invite list.
