### ISSUE TITLE
Ability to continue recording a voice message without having to press and hold the mic icon

### ISSUE THREAD

**Issue by Avi0n** [element-hq/element-x-ios#2023]
It's frustrating to have to press and hold the voice message icon to record a message. 
It would be great to implement the same system that exists in Element iOS into Element X, where you can slide up to continue recording without having to press and hold.

p.s. Thank you for removing the 2m voice limit!! I'm loving it <3

**Comment by manuroe** [comment]
It is no more mandatory to keep pressing the button. The first tap on the icon will start the recording. The second tap will stop it.
