### ISSUE TITLE
Lack of feedback on “setting up account” is very frustrating

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2027]
### Steps to reproduce

1. Try to log in on EX after setting up SS for the first time
2. Get your SS setup wrong somehow
3. Stare at the setting up screen for 4 hours because you don’t know any better

#### What did you expect?

Some kind of feedback if initial sync etc fails.

#### What happened instead?

Staring at a setting up screen forever

### Application version

428

### Will you send logs?

No

**Comment by stefanceriu** [comment]
One can now access the app settings and look at the logs.

**Comment by Richigeht** [comment]
That doesn't work on iPhones, does it?

**Comment by Richigeht** [comment]
Thanks! I just found it as well since I ended up wanting to report it as bug .... 😂
