### ISSUE TITLE
Autocomplete in composer on macOS sonoma corrupts text

### ISSUE THREAD

**Issue by lampholder** [element-hq/element-x-ios#2059]
### Steps to reproduce

- MBP 14.0 (23A344)
- Advanced composer on
- Version 1.4.0 (77)  (I wish this text were copyable on the Element X settings page)
- Inline predictive text enabled on OS
    - <img width="419" alt="image" src="https://github.com/vector-im/element-x-ios/assets/1922197/90d864d8-53e3-4931-a9fa-0736d8aeb4b6">

When you type a word for which the OS has a predictive suggestion (I think anything longer than a few characters), the next key you press after the inline suggestion has appeared will vape most of the word.

I'm talking here about the inline suggestion (the greyed out end of the suggested word appearing after the characters you've already typed), not the pill suggestion that also sometimes appears (what are you doing Apple I don't need one way to autocomplete words on a computer never mind two).

#### What did you expect?
OS typing suggestions to work as they do natively elsewhere

#### What happened instead?
Deleting the word I'm halfway through typing

### Your phone model

MBP 14.0 (23A344)

### Operating system version

MBP 14.0 (23A344)

### Application version

Version 1.4.0 (77)

### Homeserver

lant.uk

### Will you send logs?

Yes

**Comment by ara4n** [comment]
Having upgraded to Sonoma, i'm bitten by this too:


https://github.com/element-hq/element-x-ios/assets/1294269/21bbebce-284f-4433-9ff4-559f4ff7aca3
