### ISSUE TITLE
Crash after scrolling back a lot

### ISSUE THREAD

**Issue by HarHarLinks** [element-hq/element-x-ios#2116]
### Steps to reproduce

Endure the pain of scrolling back 2 weeks in an active room without having „jump to date“ support yet

#### What did you expect?
Use the app normally to view old messages 
#### What happened instead?
Crashes either during scrolling or a bit later even after having stopped scrolling 

### Your phone model

iPhone 12

### Operating system version

iOS 17.1.1

### Application version

1.4.1 (78)

### Homeserver

Matrix.org

### Will you send logs?

Yes

**Comment by giomfo** [comment]
I don't reproduce this crash on v1.6.2(559)
@HarHarLinks Hi, do you still observe the crash on your side?

**Comment by pixlwave** [comment]
Closing as stale, please re-open if you still observe this issue.
