### ISSUE TITLE
Old messages not shown

### ISSUE THREAD

**Issue by HarHarLinks** [element-hq/element-x-ios#2124]
### Steps to reproduce

1. use element x
2. Some room is created
3. Messages are posted to the room
4. A few days later, visit the same room 
5. the messages are not shown

#### What did you expect?
Messages are shown back to the start of the room
#### What happened instead?
Messages are NOT shown back to the start of the room

### Your phone model

iPhone 12

### Operating system version

iOS 17.1.1

### Application version

1.4.1 (78)

### Homeserver

Matrix.org

### Will you send logs?

Yes

**Comment by pixlwave** [comment]
@HarHarLinks Sorry just found this issue un-triaged. Do you still have this issue?
