### ISSUE TITLE
Offline messaging improvements

### ISSUE THREAD

**Issue by wrjlewis** [element-hq/element-x-ios#2127]
As someone who uses ElementX while having low or no mobile reception, usually while travelling, I have lots of messages that don’t send. 

In such scenarios it may be helpful to:

- Be able to resend multiple ‘failed to send’ messages at once
    - It’s cumbersome to resend all messages one by one
    - Often only a few messages are successfully resent. A side bonus in such instances is that messages you resend subsequently are out of order. 
- Not get disappearing messages, I had two separate instances this morning of disappearing messages, during the course of messages not sending and going back to try to resend them. Such messages remove themselves from the timeline somehow. Note that the app wasn’t force closed. 
- (subjective) The red warning icon by a ‘failed to send’ message is quite small to tap, on my iPhone 12 I find myself tapping more than once to hit it successfully (so I can resend), adds up when you have multiple messages to resend.
- Notifications for failed to send messages, this may exist already and I haven’t seen them, since notifications aren’t perfect for me. Can such failed to send notifications come even when offline? 

Just a collection of thoughts from me this morning while I was messaging a lot offline. 

Can separate these into issues, if any suggestion warrants that let me know. Perhaps some of these points exist elsewhere already.  

Thanks for all the development on EX already, it’s a pleasure to use! 

Build 1.4.1
iOS 17.0.3
iPhone 12 Pro

**Comment by manuroe** [comment]
We have covered this work cross platform in https://github.com/element-hq/element-internal/issues/312.
