### ISSUE TITLE
Red dot on user profile menu icon

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2138]
### Steps to reproduce

1. I have a red dot on my user profile menu:

![image](https://github.com/vector-im/element-x-ios/assets/1294269/991a25fa-3d7a-4738-97f9-226c546a2abb)

3. I don't know why. When i enter the menu, there are no red dots
4. I guess it's something to do with E2EE backup? But there are no red dots there either.

#### What did you expect?

Breadcrumb trail of red dots to follow to find out what the alert is for

#### What happened instead?

Flakey lost red dot

### Application version

440

### Will you send logs?

No

**Comment by stefanceriu** [comment]
This is probably fixed at this point.
