### ISSUE TITLE
"Foo mentioned you." in push notifications reduces the amount of useful information in the push notification by a line, and is confusable with the msg contents

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2139]
### Steps to reproduce

1. Receive a push with a mention:

![image](https://github.com/vector-im/element-x-ios/assets/1294269/98974fe5-06dc-4fac-b93c-8e178ffc20d0)

2. Wince that the "Travis mentioned you." text occupies a whole line, meaning that (without long-tapping further) the push has 25% less useful info on it. On apple watch, it's even more annoying, as you no longer get *any* preview of the message as it only shows the first line of the push.

#### What did you expect?

To be able to read as much contents of the push notif as possible.

If you really think it's useful to tell me that I was explicitly mentioned in the message, perhaps:
 * prefix the sender/room name with 🔔
 * suffix the sender/room name with " mentioned you"
 * ...etc

#### What happened instead?

I lost a line's worth of visible message, and the "Travis mentioned you." is ambiguous and confusable with the rest of the contents of the message itself.

### Application version

440

### Will you send logs?

No

**Comment by VolkerJunginger** [comment]
We modified the push. Hope this works better now. We believe that notifying the user that they have been mentioned is important because one reason to mention users is to generate extra awareness and urgency.

**Comment by ara4n** [comment]
Looking at the PR: https://github.com/vector-im/element-x-ios/pull/2144/files#diff-820dd031991c61213a1d080e54adb928764207a7e040523ead2060db18e08558R241 it seems like we're going from "Foo mentioned you" on a dedicated line to "Mentioned you: $msg" (which is grammatically incorrect thanks to the capital letter, and the fact that it follows after the room name, not the sender name; plus it will get confused with the message body). For instance, in the example in this bug, it'll render as: 

```
TravisR
Office of the Spec Core Team
Mentioned you: Hey all it's Tuesday
```

The end result is similar: the fact that a message is a mention ends up taking higher priority than telling you what the actual message actually is (especially on apple watch, or other UIs which only show the beginning of the message).

I agree that it's somewhat useful to tell the user that they have been explicitly mentioned *but not at the expense of truncating the push contents*, which is surely way more important. Would it be possible to come up with a more discreet indicator (e.g. prepending with 🔔)?
