### ISSUE TITLE
Double read receipt

### ISSUE THREAD

**Issue by HarHarLinks** [element-hq/element-x-ios#2156]
### Steps to reproduce

1. receive messages from another account

#### What happened instead?
![IMG_0203](https://github.com/vector-im/element-x-ios/assets/2803622/c7671f46-2d41-488f-a515-5ee7e4a8efb7)

### Your phone model

iPhone 12

### Operating system version

iOS 17.1.1

### Application version

1.4.2 (79)

### Homeserver

Matrix.org

### Will you send logs?

Yes

**Comment by HarHarLinks** [comment]
![image](https://github.com/vector-im/element-x-ios/assets/2803622/2c9911bd-60af-404e-ad05-884df734ff11)

**Comment by HarHarLinks** [comment]
![image](https://github.com/vector-im/element-x-ios/assets/2803622/ecb2a1c8-5b0c-46e4-8eff-c26b357630a9)

**Comment by manuroe** [comment]
It was fixed in the SDK some time ago. See #1784
