### ISSUE TITLE
Accepting invite on another client doesn’t show up in EX

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2181]
### Steps to reproduce

1. Get invited to a room
2. Accept invite on EW
3. Look at EX
4. See unaccepted invite there.

### Application version

445

**Comment by HarHarLinks** [comment]
not sure what version 445 is, but i can repro in 1.5.3 (86). Which made me notice that 1.5.4 is available which was not auto-updated. After applying the update, the invite is gone, but it might be due to the update process itself and might not have otherwise.

**Comment by giomfo** [comment]
I don't reproduce this issue with v1.5.9(527). I tested with an invite for a group chat and another for a DM.

**Comment by ara4n** [comment]
folks are still seeing it (cc @EdGeraghty)

**Comment by ara4n** [comment]
![Screenshot 2024-05-20 at 12 48 46](https://github.com/element-hq/element-x-ios/assets/1294269/d255dd23-a78c-41cb-a0a1-64fead501eb2)

(admittedly on android, but i suspect the bug also exists on EXI)

**Comment by manuroe** [comment]
Has anyone encountered this issue since we moved to SSS?

**Comment by manuroe** [comment]
> Has anyone encountered this issue since we moved to SSS?

Seems not. I am closing the issue.
