### ISSUE TITLE
Don't show editing options for pictures in detail view.

### ISSUE THREAD

**Issue by VolkerJunginger** [element-hq/element-x-ios#2192]
### Steps to reproduce

Send or receive a picture.

In the timeline tap on the picture.

The user has the option to edit the picture.

Remove the option to edit the picture.

### Will you send logs?

No

**Comment by pixlwave** [comment]
Summarising a discussion with @VolkerJunginger about this as there is one useful flow here that we would lose:

https://github.com/vector-im/element-x-ios/assets/6060466/15cb4e27-2d2e-4699-8d98-e4723dab9c97

With editing disabled, this flow becomes

- Save the file to your device
- Open the Files app
- Navigate to the directory you saved the file to and open it
- Edit the file
- Come back to Element
- Select the file and send it.

However from a product perspective the flow in the video recording isn't ideal as you have to copy and paste your edited file. When you compare this to using Markup in Mail, they are able to add extra items to the Done menu:

https://github.com/vector-im/element-x-ios/assets/6060466/f60f41f3-2063-40f0-ac1f-b3e0278e41ff

From what I can tell there isn't a public API to do this. @amshakal Any thoughts on this?

**Comment by amshakal** [comment]
@pixlwave I am unable to see the videos :/

**Comment by VolkerJunginger** [comment]
Its ok. We decided not to change this.
