### ISSUE TITLE
Event IDs are not logged for sent events

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-x-ios#2216]
I *believe* that https://github.com/vector-im/element-x-ios-rageshakes/issues/1179 contains the transmission of Event ID `$j1b1BiZ9mzTB7Mi15pgDVHC0l6Np6k4Vy6mEjfEHqNU`, but I can't find it because it appears we don't log the ID of events we send.

**Comment by richvdh** [comment]
obviously, this makes it hard to debug UISIs from EX senders.

**Comment by pixlwave** [comment]
@richvdh: This is probably a todo for SDK as the app sends items off to be queued in the SDK and then they basically get mixed into the timeline diffs like any other item meaning the app never directly sees the response with the event ID.

**Comment by richvdh** [comment]
Yes indeed! Filing the issue here wasn't meant to indicate any particular prejudice about the best way to solve the problem - just that the net result is that Element X iOS doesn't log the event ID.

**Comment by richvdh** [comment]
Thanks for the fix @BillCarsonFr!

Does this need an update to the Element X to use the new rust-sdk version, or will it get picked up automatically?
