### ISSUE TITLE
"Confirm your recovery key" doesn't explain you can enter your passphrase

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2217]
### Steps to reproduce

1. Enable key backup
2. View the "Confirm your recovery key" prompt

<img width="457" alt="Screenshot 2023-12-08 at 18 58 12" src="https://github.com/vector-im/element-x-ios/assets/1294269/a675c183-a609-4703-ab22-ea43a77ae6b0">

3. Panic vaguely that you don't have a recovery key - you only have a "security passphrase".
4. Discover that despite it explicitly asking you for a 48 character recovery key, the passphrase works too.

#### What did you expect?

For the prompt to acknowledge that over the years Element/Riot has encouraged users to store/set a "security key", "security passphrase", "recovery key" and "recovery passphrase" - and any of them are valid here.

E.g. "If you don't have a 48 character recovery key, you can also enter a recovery or security passphrase or key." in small print rather than "Enter the 48 character code"

#### What happened instead?

It sits on a throne of lies.

### Application version

451

### Will you send logs?

No

**Comment by pixlwave** [comment]
@pmaier1 Assigning this to you as I believe the passphrase wording was omitted intentionally.

**Comment by kenrachynski** [comment]
I just got pointed at this issue after having the dialog to correct my recovery key showed up without me doing anything at all.

I suspect this came from TestFlight updating my copy of Element X and this feature is now active. So I didn't even do step 1 of the reproduction; I went straight to step 2 when I opened the app for the first time today.

**Comment by pmaier1** [comment]
Agreed. We should provide guidance for legacy terminology (security key) and functionality (passphrase). The passphrase continues to work in EX and we should tell the user.

@americanrefugee can you make a proposal?

**Comment by pmaier1** [comment]
This is done on EIX/EAX, thanks!
