### ISSUE TITLE
Doesn’t let me sign in to my account

### ISSUE THREAD

**Issue by sallyFoster** [element-hq/element-x-ios#2220]
### Steps to reproduce

Choose the server genzedong.xyz 

#### What did you expect?

The app to allow me to connect to my server 

#### What happened instead?

I got the following error

![IMG_0583](https://github.com/vector-im/element-x-ios/assets/104597302/afc729b9-ea95-4a0f-a996-44776ccf7d53)

### Your phone model

iPhone 11 Pro Max

### Operating system version

iOS 17.2.1

### Application version

1.4.2

### Homeserver

genzedong.xyz

### Will you send logs?

No

**Comment by pixlwave** [comment]
Element X requires a homeserver with sliding sync configured, which hasn't happened for that entered homeserver. Tapping the Learn more button on that alert will give you or your admin instructions on how to configure it.
