### ISSUE TITLE
Can't recover your history if there are no other session.

### ISSUE THREAD

**Issue by BillCarsonFr** [element-hq/element-x-ios#2240]
## Step to reproduce

1. create an account on web
2. Set up recovery,
3. Create a room add a few messages
4. Log out the session

5. Now login with EIX

## Actual

![image](https://github.com/element-hq/element-x-ios/assets/9841565/e32fb478-378a-4fa6-886b-00152624eb03)

EIX is asking to verify with another device, but there are no other devices.

I can't read history and message sent with this device have a red warning saying `send by a device not verified by its owner"

## Expected

Should ask me to enter my recovery key to recover my account

**Comment by pmaier1** [comment]
You can meanwhile enter your recovery key on EX.
