### ISSUE TITLE
"Confirm your recovery key" prompt keeps spuriously popping back up.

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2243]
### Steps to reproduce

1. I set up backup on EXI on iOS and it worked (yay!) and started pulling in my keys on demand from the backup (double yay!)
2. However, ever few days, it spuriously pops up a "Confirm your recovery key" prompt in the roomlist still, which is disquieting and confusing, and presumably indicates a bug or possibly something worse? It then disappears after relaunching the app.

#### What did you expect?

Only prompt me to enter my recovery key when I need to set up backup for the first time

#### What happened instead?

Randomly prompting feels phishy at best.

### Application version

460

### Will you send logs?

Yes

**Comment by BillCarsonFr** [comment]
It will always happen after a verification.
It will appear and then disappear a few seconds after.

It's because EIX request the secrets to the other session, and this take sometime before you get them back from the other session.

**Comment by ara4n** [comment]
i'm not doing any verifications tho?
