### ISSUE TITLE
Filtered room list doesn't always react to taps

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2254]
### Steps to reproduce

1. Filter the roomlist
2. Tap on the top room
3. About 10% of the time, nothing happens

#### What did you expect?

responsive roomlist

#### What happened instead?

unresponsive roomlist

### Application version

465

### Will you send logs?

Yes

**Comment by stefanceriu** [comment]
I've seen this once or twice myself but found no way to reproduce it. It feels more like a system level regression than something we did

**Comment by ara4n** [comment]
fwiw one can fix it by slightly scrolling the list, at which point it starts reacting to taps again

**Comment by ara4n** [comment]
i see this roughly once a day, fwiw

**Comment by stefanceriu** [comment]
I haven't seen this in a while, I'm thinking unpinning the room list filters fixed it. Please reopen if reproducible.
