### ISSUE TITLE
'Waiting for this message'

### ISSUE THREAD

**Issue by wrjlewis** [element-hq/element-x-ios#2263]
### Steps to reproduce

Messages with the text 'Waiting for this message' appear instead of the actual message. 

When it happens it affects all subsequent messages until you sign out and sign in again. 

Occurring maybe once or twice a week to me (will rageshake when I next see it and attach to this issue).

Other chat clients are unaffected, for example the same message appears ok in Element or Fluffychat. 

There have been a couple of similar reports in #element-x-ios:matrix.org, eg [here](https://matrix.to/#/!amwlFMejXQcoCxNYHH:matrix.org/$l9hD8EfwSVUFe0vzbcC-Y6nMbBYhqLiiGfhwrSTNFl0?via=matrix.org&via=tchncs.de&via=element.io). 

#### What did you expect?
Messages to appear successfully

#### What happened instead?
All messages from an individual appear as 'Waiting for this message', from the point of the bug showing up. 

### Your phone model

iPhone 12 pro

### Operating system version

17.1.2

### Application version

1.4.3

### Homeserver

Synapse 1.98 @ wi11.co.uk

### Will you send logs?

Yes

**Comment by wrjlewis** [comment]
https://github.com/element-hq/element-x-ios-rageshakes/issues/1217

**Comment by stefanceriu** [comment]
There's thousands of errors in those logs, ranging from `Socket is not connected` to `IncompleteMessage`, `Operation timed out` and `404 Event not found`. 
I would say it's not surprising that something broke but what **is** really surprising is that it needs a full logout for it to start working again. We'll need someone from the crypto team to have a look at this I guess.

**Comment by wrjlewis** [comment]
> There's thousands of errors in those logs, ranging from `Socket is not connected` to `IncompleteMessage`, `Operation timed out` and `404 Event not found`. I would say it's not surprising that something broke but what **is** really surprising is that it needs a full logout for it to start working again. We'll need someone from the crypto team to have a look at this I guess.

Oh dear.. 
Despite my best efforts I do have a lot of issues with federation spikes on my homeserver, causing freezes/instability across my network.

**Comment by pr0ton11** [comment]
I have the same issues, but no error messages from logs both the server and sliding sync proxy.

**Comment by wrjlewis** [comment]
I haven't seen this problem for the last couple of weeks now.
