### ISSUE TITLE
Crash when pasting XML into the RTE

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2265]
### Steps to reproduce

1. Was running EXI on macOS
2. RTE disabled
3. Paste XML (see rageshake)
4. App crashes

#### What did you expect?

no crash

#### What happened instead?

big badda boom

### Application version

465

### Will you send logs?

Yes

**Comment by stefanceriu** [comment]
This is trivial to reproduce with the XML from the rageshake and is a problem on iOS too. The RTE reports its content as empty on sending and the app fatalErrors [here](https://github.com/element-hq/element-x-ios/blob/develop/ElementX/Sources/Screens/RoomScreen/RoomScreenViewModel.swift#L466) (which is correct)

I tracked it down to this plainTextMode check on the RTE side but I'm not sure what it means https://github.com/matrix-org/matrix-rich-text-editor/blob/main/platforms/ios/lib/WysiwygComposer/Sources/WysiwygComposer/Components/WysiwygComposerView/WysiwygComposerViewModel.swift#L113

Can you please have a look @Velin92 ?

**Comment by Velin92** [comment]
https://github.com/matrix-org/matrix-rich-text-editor/issues/910 this is a rust side issue of the markdown content parsing opened up an issue for it
