### ISSUE TITLE
Your own sent msgs can be marked as “unread” if you lock app before getting remote echo

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2272]
### Steps to reproduce

1. Send some messages
2. Immediately lock the app (presumably before you get a remote echo)
3. Later reopen it
4. Discover that your last msg(s) are underneath the read up to marker:
![image](https://github.com/element-hq/element-x-ios/assets/1294269/cd789051-0fea-41ed-93b8-e78331b06c2f)

#### What did you expect?

Obviously messages you’ve sent yourself should be marked as read

#### What happened instead?

Perceived flakiness that it doesn’t know which msgs are unread or not

### Application version

465

### Will you send logs?

Yes

**Comment by pixlwave** [comment]
I'm closing this bug as we don't send an `m.fully_read` receipt and never have. Somewhere there's an issue for opening the room at the unread marker, and I believe this is where we've got it scheduled to implement that.
