### ISSUE TITLE
In-progress messages do not persist if you view room info or navigate away from composer

### ISSUE THREAD

**Issue by wrjlewis** [element-hq/element-x-ios#2275]
### Steps to reproduce

1. Where are you starting? What can you see?
Any room, type something in the composer but don't send it. 
3. What do you click?
The room icon to view details about the room (eg to get to the people list)
5. More steps…
Return to the main chat pane and your half-written message is gone

#### What did you expect?
For the message to persist when clicking room info, or even visiting a different room in the meantime. 
#### What happened instead?
The message disappeared. 

https://github.com/element-hq/element-x-ios/assets/1543626/5f8b45a7-0a0c-436e-a62b-49248d54eb19

### Your phone model

iPhone 12 Pro

### Operating system version

iOS 17.1.2

### Application version

1.4.3

### Homeserver

Synapse 1.98 @ wi11.co.uk

### Will you send logs?

No

**Comment by stonerl** [comment]
This also happens when leaving the app. E.g. switching between Element X and Safari.

**Comment by stefanceriu** [comment]
> This also happens when leaving the app

While the original report is a known unimplemented feature I can't reproduce yours. Do you do anything else apart from just switching apps? 🤔

**Comment by stonerl** [comment]
@stefanceriu It occurs on an iPad. Here is a GIF, that illustrates it:

![RPReplay_Final1704288197](https://github.com/element-hq/element-x-ios/assets/2091312/9d8bb93a-a824-4e96-9b0e-1606b46996dc)

**Comment by stefanceriu** [comment]
Tracked it down to [here](https://github.com/element-hq/element-x-ios/blob/develop/ElementX/Sources/Screens/ComposerToolbar/ComposerToolbarViewModel.swift#L106) and [here](https://github.com/matrix-org/matrix-rich-text-editor/blob/main/platforms/ios/lib/WysiwygComposer/Sources/WysiwygComposer/Components/WysiwygComposerView/WysiwygComposerViewModel.swift#L176) but I don't understand why that's necessary. Do you happen to know @Velin92?

**Comment by wrjlewis** [comment]
@Velin92 The original report here was not the iPad issue (albeit thankful for fixing that 🙌), should we keep this issue open to cover what was originally raised? Or is that covered elsewhere

**Comment by stefanceriu** [comment]
> is that covered elsewhere

No no, let's keep this one open, I'll convert it to a feature

**Comment by Velin92** [comment]
We also fixed the issue of the composer keeping its content when navigating within the room details, which should be the intended.

https://github.com/element-hq/element-x-ios/assets/34335419/48858416-98a8-4258-9a0e-e873dd062321

Keeping the content while navigating to other rooms instead is feature we have not developed yet

**Comment by wrjlewis** [comment]
Thats awesome! Thanks

Just to be pedantic, the issue also mentioned keeping content when navigating to different rooms, has that also been added?

**Comment by stefanceriu** [comment]
Okay, we're just going to open a different ticket for the feature and keep this one just for the bugs

**Comment by stefanceriu** [comment]
Found one on element-meta https://github.com/element-hq/element-meta/issues/1776
