### ISSUE TITLE
"We couldn't reach this homeserver"

### ISSUE THREAD

**Issue by domoritz** [element-hq/element-x-ios#2280]
### Steps to reproduce

I reinstalled element x on Mac OS and just wanted to log in. 

### Outcome

<img width="595" alt="Screenshot 2023-12-21 at 15 57 36" src="https://github.com/element-hq/element-x-ios/assets/589034/41ace019-9d9d-4395-9b47-3deab605f065">

### Your phone model

macbook pro

### Operating system version

Mac OS 14

### Application version

1.4.3 (80)

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by domoritz** [comment]
Switching to https://matrix.org also doesn't work.

<img width="565" alt="Screenshot 2023-12-21 at 16 01 01" src="https://github.com/element-hq/element-x-ios/assets/589034/49e0bc01-e2a5-407d-97e0-51130b67f280">

**Comment by stefanceriu** [comment]
Just tried this now and I can login just fine. Works with both `https://matrix.org` and just plain `matrix.org`

**Comment by stefanceriu** [comment]
I'm going to close this as it feels like a local issue (per the comment above) and we haven't had any similar reports.
