### ISSUE TITLE
Large Timeline entries tight-flicker/rerender/grey-out on load

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2286]
### Steps to reproduce

1. Open a room with a big msg (esp with lots of mentions)
2. Watch it flicker and fade through various shaded of grey (presumably as the display flickers on and off at 120Hzas it rerenders in tight loop, resulting in weird greyscale)

See rageshakes for examples

#### What did you expect?

Responsive crisp timeline

#### What happened instead?

Fading flakey unresponsive timeline 

### Your phone model

12 Pro Max

### Operating system version

17.2.1

### Application version

471

### Will you send logs?

Yes

**Comment by ara4n** [comment]
https://github.com/element-hq/element-x-ios/issues/2286

https://github.com/element-hq/element-x-ios/assets/1294269/952019f1-2121-4ee1-82dc-9df7e3a4ba4c

![image](https://github.com/element-hq/element-x-ios/assets/1294269/f4f02dfa-7c12-4022-8acb-7a59cb92402f)

![image](https://github.com/element-hq/element-x-ios/assets/1294269/8778e106-b1f5-41c8-9593-28ab92b40073)

**Comment by stefanceriu** [comment]
Completely reproducible on my side, it's a side effect of mention pills loading sequencially and re-rendering the message bubble
