### ISSUE TITLE
Share option for media to element not available

### ISSUE THREAD

**Issue by pmffromspace** [element-hq/element-x-ios#2293]
### Steps to reproduce

1. Where are you starting? What can you see?
- bad decision
3. What do you click?
- „share“
5. More steps…
- can’t believe that the developer isn’t using his app himself because he would have noticed already

#### What did you expect?
From a messenger all I generally expect the share option to be enabled (Photos, Links etc).

I already found this unbelievable issue: https://github.com/element-hq/element-ios/issues/7618

so I thought there will be a good reason - let’s adapt to the progress and download element x. Did so, used my matrix.org account for login and was just expecting to see a share feature:

#### What happened instead?
Yeah well it seems the feature isn’t implemented yet. (I understand, element x is still in beta and stuff..)

BUT: there are people out there using element as daily driver. If you remove a core feature without a alternative way (like enabling it in the successor app) it IS DRIVING PEOPLE AWAY FROM ELEMENT! It’s so frustrating and I am by far not alone. I can’t even install a old version of the app with the share feature still enabled. I’m so sad to see so many people turn their back to element because the devs are apparently not using the app themselves as daily driver..?

### Your phone model

iOS

### Operating system version

All

### Will you send logs?

No

**Comment by stefanceriu** [comment]
Closing in favor of #1477
