### ISSUE TITLE
Context menu for a msg suddenly changes under you when that msg remote-echoes

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2294]
### Steps to reproduce

1. Send a msg on a slowish connection
2. Long-press on it to bring up the context menu to edit it
3. Just as you're about to press the edit button in the context menu... the remote echo of the msg comes in, and the menu changes shape, so you end up pressing the wrong button.

#### What did you expect?

Menus which don't pop around from under you.  Perhaps show all the options, greying out the ones you can't do on non-echo'd msgs, and then ungrey them when the echo arrives

#### What happened instead?

https://jsfiddle.net/9CDtE/4/

### Application version

475

### Will you send logs?

No

**Comment by pixlwave** [comment]
The context menu no longer updates based on the local/remote echo state.
