### ISSUE TITLE
Element X fails to validate empty m.identity_server

### ISSUE THREAD

**Issue by GovanifY** [element-hq/element-x-ios#2310]
### Steps to reproduce

1. Try to login to a matrix server using this client well-known

```
{
   "m.homeserver":{
      "base_url":"https://matrix.tld"
   },
   "m.identity_server":{
      
   },
   "org.matrix.msc3575.proxy":{
      "url":"https://sliding.matrix.tld"
   }
}
```

2. See incorrect error reporting that this server does not support sliding sync

#### What did you expect?

Element X fails to parse a client well-known with an empty m.identity_server. 
This leads to the user seeing an error about their homeserver not supporting sliding sync, since it was unable to parse `org.matrix.msc3575.proxy`.
This well-known format seems to be accepted by the other clients I've tested and is valid JSON, so I'd wager it should either be accepted or the error message shouldn't report an error with sliding sync support.

#### What happened instead?

well-known fails to be parsed, see log:
```
2024-01-08T15:44:28.086419Z DEBUG matrix_sdk::http_client: Error while sending request: Api(Deserialization(Json(Error("missing field `base_url`", line: 1, column: 81)))) | crates/matrix-sdk/src/http_client/mod.rs:186 | spans: build{homeserver=ServerName { server: "govanify.com", protocol: Https }} > send{server_versions=[V1_0] config=RequestConfig { timeout: 30s, retry_limit: 3 } request_id="REQ-0" method=GET uri="https://govanify.com/.well-known/matrix/client" status=200 response_size="155 B"}
```

### Will you send logs?

No

**Comment by pixlwave** [comment]
Thanks for opening the issue @GovanifY. Looking at the [spec](https://spec.matrix.org/v1.9/client-server-api/#getwell-knownmatrixclient) for the well-known, it says that the `base_url` is required if you have an `m.identity_server` so whilst you are right, the error is slightly misleading, the behaviour is expected.

**Comment by GovanifY** [comment]
Ah indeed, thanks for checking up! 
This error never popped up in alternate clients, so I didn't knew whether spec compliance really mattered in this case, as this issue seemed to have happened in the past looking at older synapse & riot/element issues.

**Comment by pixlwave** [comment]
Closing this issue as the app is behaving as expected and we have scheduled some either as part of https://github.com/matrix-org/matrix-rust-sdk/pull/3049 or in a follow-up to improve the error messages we're presenting.
