### ISSUE TITLE
Cache avatars

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2314]
### Steps to reproduce

1. Launch app
2. Scroll room list
3. Observe that avatars incrementally load and haven’t been cached

#### What did you expect?

Maintain a cache of room & user avatars

#### What happened instead?

Looks like they get pulled in from scratch from the server every time, wasting network and server resources and making the app feel sluggish/amnesiac.

### Application version

484

### Will you send logs?

No

**Comment by stefanceriu** [comment]
> Looks like they get pulled in from scratch from the server every time

That is not the case, the images are cached on disk rust side and, empirically, the sdk storage is just as fast as ours for this use case. Avatars start loading as soon as rooms are displayed and the fade in animation is making it feel worse than it is. We removed animations for avatars and kept it for everything else (e.g. timeline images). Let's see if this makes things appear better
