### ISSUE TITLE
Switching between EC SPA calls doesn’t work

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2325]
### Steps to reproduce

1. Click on a link for an EC call; it opens in EX
2. Close the call when it’s over
3. Click on a link for another call; it opens in EX… but dials into the previous SPA, not the new one.

#### What did you expect?

SPA calling to take you to the right call.

#### What happened instead?

SPA calling took us to the wrong call.

### Application version

1.5.1

### Will you send logs?

No

**Comment by stefanceriu** [comment]
@ara4n I can't seem to reproduce it. Please check the attached video, am I missing something in the flow?


https://github.com/element-hq/element-x-ios/assets/637564/c1037182-6d9d-4a0d-b002-c4f6bd222aa9

**Comment by ara4n** [comment]
I just reproduced it. I think it happens if you click on the new link but you don't close the previous call window by swiping it away after hanging up (or if you don't hang it up, or if it's sitting in the lobby)
