### ISSUE TITLE
[RoomList Filters] Implement the filters horizontal scroll view

### ISSUE THREAD

**Issue by manuroe** [element-hq/element-x-ios#2339]
- Create a horizzontal scroll view that only appears if the room list setting/FF is turned on below the search bar
- This should include the following filters: "Rooms" "People" "Unreads" "Low Priority" "Favourites" (check design for the ordering and naming)
- These filters can be selected and unselected and should change their color according to the selection state
- An X button should appear when at least one filter is selected, to unselected them all at once.

**Comment by Velin92** [comment]
Kamino cloned this issue to [vector-im/element-x-android](https://github.com/element-hq/element-x-android/issues/2232)
