### ISSUE TITLE
Using speech to text crashes El X

### ISSUE THREAD

**Issue by Avi0n** [element-hq/element-x-ios#2344]
Crashes both when RTE is enabled and disabled.

### Steps to reproduce

1. Press iOS keyboard's text to speech button
2. Use voice to write a message of any length
3. Press iOS keyboard's mic button again to stop speech to text mode
4. Observe El X crashing to the home screen

#### What did you expect?
El X not crashing
#### What happened instead?
El X crashed and my draft was not saved

### Your phone model

iPhone 15 Pro Max

### Operating system version

iOS 17.2.1

### Application version

1.5.2 (85)

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by jacotec** [comment]
Can confirm the above, TTS is fully broken in the Testflight version 1.5.2 and crashes as soon as you end the dictation. **Please do not release this build** officially as it'll make thing more than worse!
@Velin92 @pixlwave

**Comment by Velin92** [comment]
Thanks for flagging the issue, there was a mistake during the deployment of the dictation fix, that caused this, but we have already a PR with the fix for the crash ready
