### ISSUE TITLE
Double tapping space to insert a period doesn't work when at the end of an existing word that is not on the last line

### ISSUE THREAD

**Issue by Avi0n** [element-hq/element-x-ios#2345]
### Steps to reproduce
Issue happens regardless of whether RTE is enabled or not.

1. Write a message of any length, press return twice, write a word or two.
2. Put cursor back up to the end of the first line. 
3. Double tap space bar to insert a period
4. See that no period is inserted and a blank space is inserted instead

The same issue happens while editing a message. 
Double tapping space to insert period in other situations works as intended. 

#### What did you expect?
A period to be inserted
#### What happened instead?
No period was inserted

### Your phone model

iPhone 15 Pro Max

### Operating system version

iOS 17.2.1

### Application version

1.5.3 (86)

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by Velin92** [comment]
I just tested this with RTE on, and seems to work fine on my side, can we get more info on how you are able to reproduce this issue?

https://github.com/element-hq/element-x-ios/assets/34335419/f13e8fa6-104e-48f1-9489-610300e6856b

**Comment by Avi0n** [comment]
@Velin92 Sorry about that, it was happening to me on one message I was editing so I assumed that was the problem. Narrowed it down to the actual issue and updated the title and body accordingly.

**Comment by Velin92** [comment]
Yeah checked the issue seems to happen when you are trying to insert the period, on the end of an existing word that is not on the last line.

**Comment by Velin92** [comment]
fixed on develop
