### ISSUE TITLE
Refresh tokens aren't supported and break badly (without OIDC)

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2365]
### Steps to reproduce

Based on [doug's msg](https://matrix.to/#/!amwlFMejXQcoCxNYHH:matrix.org/$Z2FO2QLsS7zARvGrYIqAJrcDKvpqludnXiMxL8-N7ks?via=matrix.org&via=beeper.com&via=element.io) it sounds like EX doesn't support refresh tokens [MSC2918](https://github.com/sandhose/matrix-doc/blob/sandhose/msc/refresh-token/proposals/2918-refreshtokens.md) unless the server is talking full OIDC.  So if you enable it in synapse at https://element-hq.github.io/synapse/latest/usage/configuration/user_authentication/refresh_tokens.html then all sorts of things break in mysterious ways.

#### What did you expect?

Break hard, or not at all, if the server has refresh tokens configured.

#### What happened instead?

Break in mysterious ways.

### Will you send logs?

No

**Comment by pixlwave** [comment]
Should be a relatively simple tweak to have the authentication service proxy check after `/login` that the client's session doesn't contain a refresh token when there isn't any OIDC data, and in that scenario, immediately call `/logout` and present an error to the user to tell them refresh tokens from the homeserver aren't supported.
