### ISSUE TITLE
Tapping on the room list doesn't always take you to the right room

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2386]
### Steps to reproduce

1. I kept tapping on one room in the roomlist
2. It kept taking me to the room immediately above it.
3. No, i didn't miss.
4. I then scrolled the roomlist slightly, and it got it right.

#### What did you expect?

If I tap on something i expect it to react, not the thing next to it.

#### What happened instead?

Gaslighting

### Application version

503

### Will you send logs?

Yes

**Comment by stefanceriu** [comment]
Still a problem, had it today. I was hoping unpinning the filters with fix but no, feels like a pure SwiftUI problem.

**Comment by fuomag9** [comment]
Happened to me as well today

**Comment by ara4n** [comment]
Still a problem on 645, and particularly common on macOS.
