### ISSUE TITLE
Invited user has no profile

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2392]
### Steps to reproduce

1. Invite danielle to a room
2. her profile comes up in the user search ui
3. but not in the pending invite list

![image](https://github.com/element-hq/element-x-ios/assets/1294269/639e8217-83ce-410f-b033-dab0e3de2953)

#### What did you expect?

consistently visible profiles

#### What happened instead?

ugly missing profiles

### Application version

508

### Will you send logs?

Yes

**Comment by stefanceriu** [comment]
Fixed in https://github.com/matrix-org/matrix-rust-sdk/pull/3286
