### ISSUE TITLE
The settings context menu is not doing anything useful

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2393]
### Steps to reproduce

1. Tap on your avatar in top left to open the settings menu
2. There’s nothing in it other than Settings and Logout
3. 99.99% of the time you then tap Settings again
4. Wonder why the app bothered and didn’t just take you to the settings card (which could have logout buried in it, given users almost never logout).

#### What did you expect?

One tap to get to settings

#### What happened instead?

Two taps to get to settings and a weirdly ugly 2 item menu, exposing a destructive and rare action (logout) as a first class citizen

### Application version

508

### Will you send logs?

No

**Comment by Velin92** [comment]
@VolkerJunginger @amshakal  couldn't we just get rid of this menu and just put the Log Out directly in the settings screen? I actually feel too that having a context menu with only 2 feels a bit off.

**Comment by manuroe** [comment]
@Velin92 , I checked with product and design, we can kill this intermediate context menu. There is no short term usage of it.

**Comment by Velin92** [comment]
> @Velin92 , I checked with product and design, we can kill this intermediate context menu. There is no short term usage of it. Also, EAX does not have it.

perfect I am going to remove it then, since the Sign out is also inside the settings.
