### ISSUE TITLE
Settings context menu flickers slightly grey while roomlist updates

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2394]
### Steps to reproduce

1. Open settings context menu by tapping on profile
2. Watch it carefully
3. Whenever any contents in the roomlist updates it flickers grey (or black?) for a frame or so - similar to the flickering effect we had/have on bubbles as they rerender lots of mentions:

https://github.com/element-hq/element-x-ios/assets/1294269/77462cb5-e07c-44ae-8269-80e644fc6b0f

This was visible live (over screenshare) on mauro’s demo at the monthly wrap of mentions & RRs

#### What did you expect?

Rock solid stable UI

#### What happened instead?

UI which flickers subtley, like an filament lightbulb which is about to break 

### Your phone model

iphone 12 pro max 

### Operating system version

17.3

### Application version

508

### Will you send logs?

No

**Comment by stefanceriu** [comment]
We no longer have a settings context menu
