### ISSUE TITLE
Replies to redactions don’t render sensibly

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2396]
### Steps to reproduce

1. reply to a msg
2. redact the original msg
3. reply ends up looking like this:

![image](https://github.com/element-hq/element-x-ios/assets/1294269/3e398336-8567-45b3-96b9-5053162f4353)

#### What did you expect?

redacted msgs are shown as “deleted message” or something rather than just showing blank, which makes it look like the reply has failed to load.

### Application version

508

### Will you send logs?

No

**Comment by ara4n** [comment]
actually, this reply wasn't a redaction - it was a reply to an event that matrix.org didn't have, apparently

**Comment by frebib** [comment]
EXA has a similar problem in that it renders an empty box given the same scenario
![Screenshot_20240130-122343.png](https://github.com/element-hq/element-x-ios/assets/775104/e5ae5d57-9abc-4569-9fc0-c2ee7fd091e2)

**Comment by manuroe** [comment]
@VolkerJunginger what text should we display for the deleted message?

**Comment by VolkerJunginger** [comment]
Same string as for deleted message.
