### ISSUE TITLE
Room previews are blank after restoring from backup

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2398]
### Steps to reproduce

Based on @pmaier1 demoing E2EE backups on EX in the monthly wrap...

1. Connect backup to a new login
2. Room previews are blank until someone speaks in the room.

#### What did you expect?

Room previews should reflect messages restored from backup

#### What happened instead?

They ignore them, until someone speaks in the room

### Will you send logs?

No

**Comment by ara4n** [comment]
I just saw this again as Amandine logged into EXI on macOS for the first time - having verified her device, most of the room previews were blank until something happened in the room, which felt like a really flakey FTUE

**Comment by bnjbvr** [comment]
I _think_ https://github.com/matrix-org/matrix-rust-sdk/pull/3018 should help with this.

**Comment by ara4n** [comment]
this is entirely reproduceable btw, so should be easy to check :)

**Comment by manuroe** [comment]
We first need to create an integration test to verify this (complexity: S). Then, we may need to fix the problem itself.

**Comment by bnjbvr** [comment]
We do have an [integration test for this](https://github.com/matrix-org/matrix-rust-sdk/blob/aaccfdfea51accbd94955717468733d07b46e1e3/testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs#L724), so it should really be fine — if it's not please reopen.
