### ISSUE TITLE
Device verification: Emoji names are not translated

### ISSUE THREAD

**Issue by manuroe** [element-hq/element-x-ios#2402]
### Steps to reproduce

1. Configure the app to use another language than English
2. Log in the app
3. Start verification with another matrix client
4. The emoji names in the verification screen is in English instead of using the app language you selected

#### What did you expect?
Emoji names should be translated

#### What happened instead?
Emoji are in English

![IMG_9648](https://github.com/element-hq/element-x-ios/assets/8418515/8a82b5cb-51d3-444b-a09f-0e87f74798ea)

### Will you send logs?

No

**Comment by Velin92** [comment]
Okay so I checked how El-iOS legacy solves the issue, and is actually quite simple.
The emojis have a `name` value (which is equivalent to the `description` value that the Rust SDK returns to us for the emoji) and the project itself contains all the translations for all the 64 possible emojis, which we could add directly using localazy.
Then is just a matter of using that description value to fetch the specific translation for that emoji directly from the project.
