### ISSUE TITLE
Notifications at mentions in encrypted rooms

### ISSUE THREAD

**Issue by anym001** [element-hq/element-x-ios#2411]
### Steps to reproduce

Settings -> Notifications -> Groupchats -> Mentions and key words
(Your home server does not support this option in encrypted rooms. You may not be notified in some rooms.)

#### What did you expect?
It would be great if you could also be notified of mentions in encrypted rooms.

#### What happened instead?
No notifications for mentions in encrypted rooms.

### Your phone model

iPhone 14 Pro

### Operating system version

iOS 17.3

### Application version

1.5.4 (88)

### Homeserver

matrix.minenet.at

### Will you send logs?

No

**Comment by Velin92** [comment]
A homeserver needs to implement the following MSC which is experimental:
https://github.com/matrix-org/matrix-spec-proposals/pull/4028

Matrix.org is working on implementing it on their server, but if you have a server of your own you might need to update it or use a development version to support this

**Comment by ich777** [comment]
> but if you have a server of your own you might need to update it or use a development version to support this.

...in response to that what needs to be updated or better speaking which development version needs to be used, this answer is a bit vague to me and the linked PR is blocked for merging

**Comment by Velin92** [comment]
> > but if you have a server of your own you might need to update it or use a development version to support this.
> 
> ...in response to that what needs to be updated or better speaking which development version needs to be used, this answer is a bit vague to me and the linked PR is blocked for merging

If your server is using Synapse, it should have already been implemented in it (but I am not sure if a stable release with the implementation is already available, or if you might need to use a development/unstable version), you can get more info directly on [Synapse](https://github.com/element-hq/synapse)

**Comment by ich777** [comment]
@Velin92 sorry but I've now found conflicting information on how to enable experimental features, some say you have to create a file called `synapse.config.experimental` with the contents from below and some say that you just have to put the contents from below into your `homeserver.yaml`
```
experimental:
  msc4028_push_encrypted_events: true
```

As far as I can tell synapse [v1.100.0](https://github.com/element-hq/synapse/releases/tag/v1.100.0) should have that built in but I seem to can't get it to work with either methods since `/_matrix/clients/versions` always returns: `{"errcode":"M_UNRECOGNIZED","error":"Unrecognized request"}`

**Comment by anym001** [comment]
Reopening.

**Comment by Velin92** [comment]
> @Velin92 sorry but I've now found conflicting information on how to enable experimental features, some say you have to create a file called `synapse.config.experimental` with the contents from below and some say that you just have to put the contents from below into your `homeserver.yaml`
> 
> ```
> experimental:
>   msc4028_push_encrypted_events: true
> ```
> 
> As far as I can tell synapse [v1.100.0](https://github.com/element-hq/synapse/releases/tag/v1.100.0) should have that built in but I seem to can't get it to work with either methods since `/_matrix/clients/versions` always returns: `{"errcode":"M_UNRECOGNIZED","error":"Unrecognized request"}`

Sorry but I don't know if I can help you, could you try asking or opening an issue on the [synapse repo](https://github.com/element-hq/synapse/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)?

**Comment by ich777** [comment]
> Sorry but I don't know how I can help you

Thanks for the response.

No worries, I now implemented everything that MSC4028 is supported on my homeserver and it even reports that it's enabled but on Element X it shows it's not supported by the homeserver, so isn't this related to Element X for iOS?

The homeserver now responds properly with:
`"org.matrix.msc4028":true`

**Comment by Velin92** [comment]
> > Sorry but I don't know how I can help you
> 
> Thanks for the response.
> 
> No worries, I now implemented everything that MSC4028 is supported on my homeserver and it even reports that it's enabled but on Element X it shows it's not supported by the homeserver, so isn't this related to Element X for iOS?
> 
> The homeserver now responds properly with: `"org.matrix.msc4028":true`

Could you try to check if this is also enabled for the push rules by default on your accounts? Since El-X checks also if the push rule for the account data has MSC 4028 enabled

**Comment by ich777** [comment]
I assume you are after that:
```
...
      {
        "conditions": [
          {
            "kind": "event_match",
            "key": "type",
            "pattern": "m.room.encrypted"
          }
        ],
        "actions": [
          "notify"
        ],
        "rule_id": ".org.matrix.msc4028.encrypted_event",
        "default": true,
        "enabled": false
      },
...
```

Good to know that this is the issue, I've now changed it and it seems to be resolved, at least the app doesn't list the message anymore!  
I hope that was the correct way to change it:
`curl -X PUT -H "Authorization: Bearer <YOURTOKEN>" -d '{"enabled":true}' http://<YOURHOMESERVER>:8008/_matrix/client/r0/pushrules/global/override/.org.matrix.msc4028.encrypted_event/enabled`

**Comment by ich777** [comment]
@Velin92 sorry again a question, do all users have to change that setting on their own? This would be a huge bummer since with the command from above I changed it only for me correct?

**Comment by Velin92** [comment]
@ich777 Okay I double checked, as of right Synapse implements the configuration as an experimental/unstable setting. But it does not support yet that when enabled, it automatically adds as default global push rule for all the users, there is in fact an issue open about it:
https://github.com/element-hq/synapse/issues/16846

So yeah as of right now users need to change this manually to support it.
But in the future it will be automatically added to the push rules of the users by default if the server has it enabled.

**Comment by ich777** [comment]
> So yeah as of right now users need to change this manually to support it.

Thanks for confirming.

**Comment by alecdwm** [comment]
For anyone who finds themselves looking for a way to enable experimental [msc4028](https://github.com/matrix-org/matrix-spec-proposals/blob/giomfo/push_encrypted_events/proposals/4028-push-all-encrypted-events-except-for-muted-rooms.md) support on their homeserver:

1. Add this section to your `homeserver.yaml` and restart synapse
```yaml
experimental_features:
  msc4028_push_encrypted_events: true
```

2. Check if https://github.com/element-hq/synapse/issues/16846 has been merged.
If not, obtain your access token from `Element Desktop -> Settings -> Help & About -> Advanced` and run this curl command:
```bash
curl -H 'Authorization: Bearer <access-token>' \
  https://<homeserver-url>/_matrix/client/r0/pushrules/global/override/.org.matrix.msc4028.encrypted_event/enabled \
  -XPUT \
  -d'{"enabled":true}'
```

You can check that it worked by removing `-XPUT -d'{"enabled":true}'` and running the command again, which will return `{"enabled":true}`.

You can also confirm that the following command includes `"org.matrix.msc4028":true` in the response:
```bash
curl -H "Authorization: Bearer <access-token>" https://<homeserver-url>/_matrix/client/versions                                                                                           
```

At this point, Element X should stop showing the `does not support this option in encrypted rooms` warning.
