### ISSUE TITLE
No way to verify acct or enable backup if you have no other devices

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2424]
Currently locked out of my `@matthew:element.io` acct history on EX because i have no logged in sessions, so can’t verify myself against them to get at my backup. EX provides no way to enter your recovery key or passphrase to get at the history (and meanwhile my history is awol on EW too, as I need to reset the passphrase there, and it won’t let me
due to OIDC…)

**Comment by ara4n** [comment]
Just saw this bite someone horribly: they signed up on classic Element on mobile; switched to EX (and deleted Element); and then got prompted to verify themselves.  Except they no longer have any devices, so are completely hosed and will be constantly nagged about verifying the device (short of reinstalling Element in order to verify the EX login...)

**Comment by sandhose** [comment]
> (and meanwhile my history is awol on EW too, as I need to reset the passphrase there, and it won’t let me due to OIDC…)

You can do that by going to https://mas.element.io/account/ and click "Allow crypto identity reset". We hadn't had the chance to properly hook up clients to this screen yet

**Comment by ara4n** [comment]
that said, the core problem here is still a HUGE problem - the current FTUE on EX is catastrophic for users who don't have a device to verify against.

**Comment by pmaier1** [comment]
Coincidentally we have made a [concept](https://github.com/element-hq/element-meta/blob/develop/docs/FTUE.md) for this. Now we _just_ need to find space on the roadmap for it.

**Comment by ara4n** [comment]
blocking this behind a big FTUE project feels like an error.

right now, there is literally no way for a user in EX to enter their recovery key to get into their account history (unless they already have another session around they can verify with).

however, we *do* have the UX to actually receive recovery key/passphrase (when configuring backup).  But we're in the nightmare situation that you can't get to that UX to enter your recovery details... until you've verified with an existing device.

So, all i'm proposing is, as a stopgap, to provide the ability to enter recovery details at the "verify your account" stage - **after all, users will /always/ need the option to do this, no matter whether verification is done by QR login, or SAS verification, for situations where they have no other login**.

**Comment by pmaier1** [comment]
> blocking this behind a big FTUE project feels like an error.

Nobody said that we need to implement this concept as a whole. It's my _perfect world_ solution for FTUE. I found it important that this gets considered and thought-through holistically. We can well break it down into individual aspects. We could do a quick fix to allow verification via recovery key extending the current flow - as you suggest.

This needs to have the right priority then. cc @VolkerJunginger

**Comment by stefanceriu** [comment]
Handled in https://github.com/element-hq/element-x-ios/pull/2483
