### ISSUE TITLE
self verification at login can take 30s

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2428]
### Steps to reproduce

1. log in on EX on matrix.org (using a large account, but unclear if that matters)
2. login is instant!
3. ask to verify against an existing login
4. verification appears immediately on EDR
5. …but then waiting for emoji to appear can take 20-30s to appear
6. …or confirming the emoji match.

#### What did you expect?

Instant verif

#### What happened instead?

Super slow verif. This (combined with https://github.com/element-hq/element-x-ios/issues/2417) means that I gave up on demoing instant login and backup restoration on stage at FOSDEM, given waiting 20s for verif != instant.

### Application version

513

### Will you send logs?

No

**Comment by ara4n** [comment]
i tried this twice, btw; it looked to be consistent on my account

**Comment by ara4n** [comment]
i haven't seen this in a while (but it might be because i keep logging in via QR these days...)

**Comment by manuroe** [comment]
Let's close it then. The 'to_device' stream speed got significantly improved with SSS.

For reference, last month, @bmarty made a [demo](https://www.youtube.com/watch?v=5q3njjtlaVU&t=693s) of incoming device verification with several self verifications. The flows were instant every time on matrix.org.
