### ISSUE TITLE
Polls cause stuck notif

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2439]
### Steps to reproduce

1. Start a poll in a room in EX
2. Someone answers it
3. Room has stuck green badge

#### What did you expect?

reading the room should clear the badge

#### What happened instead?

it doesn’t

### Application version

516

### Will you send logs?

No

**Comment by bnjbvr** [comment]
I expect this to be resolved with https://github.com/matrix-org/matrix-rust-sdk/pull/3119; so we'll need to wait for a SDK update in the app for this to be tested.

**Comment by Velin92** [comment]
The sdk has been updated, the issue should be fixed in the next nightly
