### ISSUE TITLE
Presence Status

### ISSUE THREAD

**Issue by kinchitg** [element-hq/element-x-ios#2451]
For any chat application to be successful, there are three most important features that all consumers need

**Presence Indicators** 
App should show if the person we are talking with is currently Online or not. If that person is offline, how long ago that person was online. Matrix and Element Presence API is very very accurate. All we need is to implement this feature sooner than later. Ofcourse, some people would not want this feature but we can put a toggle in setting to turn this ON or OFF. 

Similar to WhatsApp, Telegram, Teams
Please show Presence Status right below the user profile name in direct chat.

possible two statuses:
Active
Active/Offline 34 seconds ago

Typing Indicators
I believe this one is already in your task list

Read Receipts 
I believe this one is already in your task list

**Comment by pixlwave** [comment]
Thanks for the feedback @kinchitg. I'm going to close this issue as we have presence tracked on the roadmap, and the other 2 items are both already implemented.

**Comment by Unkn0wn-MDCLXIV** [comment]
Any news when the presence indicator will be implemented? This is the only reason I still prefer element classic over element x.
