### ISSUE TITLE
I'm using a custom tile server. But still see the MapTiller and OpenStreetMap copyright.

### ISSUE THREAD

**Issue by LutzLange** [element-hq/element-x-ios#2457]
### Steps to reproduce

I configured a custom tile server. Like this : 
    "m.tile_server": {
        "map_style_url": "https://sgx.geodatenzentrum.de/gdz_basemapde_vektor/styles/bm_web_col.json"
    },

2. And I logged in and shared a location.
![IMG_4206](https://github.com/element-hq/element-x-ios/assets/2788194/654900c1-3349-4ad5-8184-9cfe7261552c)

#### What did you expect?
My did expect to not see the maptiller and OpenStreetmap Copyright. The data comes from basemap.de not maptiller.

### Your phone model

iPhone Xs Max

### Operating system version

16.6.1

### Application version

1.5.5

### Homeserver

ESS 23.10.22

### Will you send logs?

Yes

**Comment by Velin92** [comment]
Hello! As of right now is not possible to configure through your matrix server the map provider.
You can do that in forks however by following this guide:
https://github.com/element-hq/element-x-ios/blob/develop/docs/FORKING.md
