### ISSUE TITLE
Maps not readable in dark mode

### ISSUE THREAD

**Issue by LutzLange** [element-hq/element-x-ios#2458]
### Steps to reproduce

1. Where are you starting? What can you see?

I did configure an alternative map tile server like this : 

    "m.tile_server": {
        "map_style_url": "https://sgx.geodatenzentrum.de/gdz_basemapde_vektor/styles/bm_web_col.json"
    },

I got the maps, but they are unreadable in dark mode. ( Which was the default for my phone ).
![IMG_4204](https://github.com/element-hq/element-x-ios/assets/2788194/ebef99ff-7e1a-4c7c-935b-5c23372fac50)

#### What did you expect?

readable maps.

### Your phone model

iPhone Xs Max

### Operating system version

16.6.1

### Application version

1.5.5

### Homeserver

ESS 23.10.22

### Will you send logs?

Yes

**Comment by Velin92** [comment]
As of right now in El-X map styles are hardcoded in the project, and can't be customised directly from the server configuration.
This is a guide on how to customise them in forks:
https://github.com/element-hq/element-x-ios/blob/develop/docs/FORKING.md

**Comment by stefanceriu** [comment]
Fixed in https://github.com/element-hq/element-x-ios/issues/2843
