### ISSUE TITLE
Using voice to text then inserting a word before the last word using Swipe causes garbled word

### ISSUE THREAD

**Issue by Avi0n** [element-hq/element-x-ios#2477]
### Steps to reproduce

1. Use voice to text to write some words
2. Without cancelling Voice to Text mode, place cursor somewhere before the last word
3. Using swipe, type something else
4. Send message
5. Observe what got sent is not what was in the composer before pressing send

Works especially well if you use swipe to type a word, then hit backspace where it deletes a full word at a time, then type some more.

Video Example 1:
https://github.com/element-hq/element-x-ios/assets/14863961/1f9b7460-ddf5-473c-978d-a7f86ce361b3

Video Example 2:
https://github.com/element-hq/element-x-ios/assets/14863961/0de393fe-d4bc-4745-b367-58cc11e206ef

#### What did you expect?
Message to send exactly as I see it in the composer

#### What happened instead?
In the first example a space was removed. In the second example letters that were deleted showed up and produced a garbled word that was not present in the composer.

### Your phone model

iPhone 15 Pro Max

### Operating system version

iOS 17.3.1

### Application version

1.5.7 (91)

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by Velin92** [comment]
fixed a long time ago
