### ISSUE TITLE
Ghost notification badge

### ISSUE THREAD

**Issue by Smexhy** [element-hq/element-x-ios#2555]
### Steps to reproduce

1. After using the other Element app, I installed this client, Element X
2. Logged in on my local matrix server, filled my crypting key for backups
3. Received notification from a person
4. It shows as 2 notifications badges on the app icon even though it’s from a single person
5. After reading it, 1 ghost notification badge still shows up on the app icon
6. Need to relog and it disappears until someone texts me again

#### What did you expect?

1 single notification badge which disappears after reading the unread message

#### What happened instead?

Got 2 notifications and after reading the only undread chat, it still shows 1 unread notification badge on the app icon, permanently. Force closing app doesn’t help, nor restarting phone.

### Your phone model

iPhone 15 Pro Max

### Operating system version

iOS 17.4

### Application version

1.5.10

### Homeserver

Synapse v1.98.0

### Will you send logs?

Yes

**Comment by pixlwave** [comment]
@Smexhy Please update to synapse v1.102.0, it contained a fix for notification counts (you will need to wait until you get a notification for it to update). I'm going to close this issue, but please re-open it if it doesn't fix your problem.
