### ISSUE TITLE
Filter bar ends up halfway down the room list

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2567]
### Steps to reproduce

Unsure what the repro steps are, but the filter bar often ends up at least one or two rooms too 'low' in the room list.  May be related to keybaord interactions when filtering the room list.

### Outcome

Filter bar to stay at the top, not go drifting down the page

### Your phone model

iPh

### Operating system version

iOS 17.4

### Application version

549

### Will you send logs?

Yes

**Comment by ara4n** [comment]
https://github.com/element-hq/element-x-ios/issues/2567

**Comment by Velin92** [comment]
It's very weird seems only to happen on some devices, it may be very well a swiftUI bug, however  in this PR we try to force the filter to be always at the top of the pinned header:
https://github.com/element-hq/element-x-ios/pull/2570

Let us know if the problem persists in the next nightly, in that case we are going to try a more "aggressive" approach for fixing it

**Comment by Velin92** [comment]
@ara4n @Hywan can you test again on the latest nightly? Is the issue still happening?
