### ISSUE TITLE
Horizontal Scrollbar overlays filters on macOS

### ISSUE THREAD

**Issue by domoritz** [element-hq/element-x-ios#2583]
### Steps to reproduce

Open ElementX on macOS

### Outcome

<img width="247" alt="Screenshot 2024-03-19 at 16 28 40" src="https://github.com/element-hq/element-x-ios/assets/589034/e7019a1f-cafe-499f-b5bb-d365d16a4485">

### Your phone model

macBook Pro

### Operating system version

macOS

### Application version

Version 1.5.12 (99)

### Will you send logs?

No

**Comment by pixlwave** [comment]
This requires a (non-magic) mouse to be connect to the Mac in order to reproduce.

**Comment by domoritz** [comment]
I see. I have the problem with the trackpad.

**Comment by pixlwave** [comment]
Oh interesting. What do you have this setting set to:
<img width="827" alt="Screenshot 2024-03-20 at 10 50 02 AM" src="https://github.com/element-hq/element-x-ios/assets/6060466/bacd12dc-73db-4abb-a3d2-ad5094efdd94">

**Comment by domoritz** [comment]
I have it set to always because I like to know when there is a scroll view and how far I am. Not a fan of hidden state. 

<img width="479" alt="Screenshot 2024-03-20 at 09 12 03" src="https://github.com/element-hq/element-x-ios/assets/589034/91cfda4b-ef98-4728-8dfb-0750775a21a7">

The design looks pretty out of place anyway. I think wrapping would be a better UX than horizontal scrolling.

**Comment by kostrykin** [comment]
<img width="297" alt="Bildschirmfoto 2024-11-16 um 11 04 06" src="https://github.com/user-attachments/assets/001d9034-7706-4c1f-a98f-404a4b7a2edc">

It's not just the horizontal scrollbar, it's also the vertical one. I think there is some padding missing for the content.

**Comment by domoritz** [comment]
Here is the design in the GitHub iOS app. It could be more space saving so that most of the time no scrolling is needed. ![image](https://github.com/user-attachments/assets/6f8b293e-6d48-4d5d-9822-07fae81f2f22)

**Comment by ssbarnea** [comment]
Not sure what is happening with Element X on MacOS Sonoma but it become totally broken, I am unable to click on any of the left channels and the right panel is empty. I have to go back to the old slow Element.app for a while. It was fun while it worked...
