### ISSUE TITLE
iOS 15 support

### ISSUE THREAD

**Issue by mak448a** [element-hq/element-x-ios#2584]
**Is your feature request related to a problem? Please describe.**
I have an older phone, which only supports up to iOS 15.8. I can't install the app.

**Describe the solution you'd like**
Could you please add iOS 15 support to Element X? From the description of the app, this will replace Element. This means that I won't be able to use the latest version of Element anymore when this happens.

**Describe alternatives you've considered**
Use the old element app

**Additional context**
N/A

**Comment by pixlwave** [comment]
@mak448a Sorry, this isn't going to be possible I'm afraid. The entirety of the app's navigation is based on APIs that were introduced in iOS 16. We do intend to make sure the old app is kept available on the store even once we're happy that Element X is ready to replace it though.

**Comment by mak448a** [comment]
Thank you for clarifying that the original app will be kept up! Thanks!
