### ISSUE TITLE
Settings are not accessible through menu on macOS

### ISSUE THREAD

**Issue by domoritz** [element-hq/element-x-ios#2586]
### Steps to reproduce

Open settings through the menu (no other settings are available). 

<img width="205" alt="Screenshot 2024-03-20 at 10 03 35" src="https://github.com/element-hq/element-x-ios/assets/589034/fe972690-80e7-434e-a49b-b6116a9392f1">

#### What did you expect?

Having access to these settings.

<img width="560" alt="Screenshot 2024-03-20 at 10 03 49" src="https://github.com/element-hq/element-x-ios/assets/589034/7054b9f6-1e12-48e7-9d1f-14a658ee81c6">

#### What happened instead?

This dialog opens

<img width="873" alt="Screenshot 2024-03-20 at 10 03 37" src="https://github.com/element-hq/element-x-ios/assets/589034/d9b339d3-f28f-48f7-97a2-7b45e3705123">

### Your phone model

macBook pro

### Operating system version

macOS

### Will you send logs?

No

**Comment by pixlwave** [comment]
As much as I would love for this to work (I really would!), this isn't possible to implement for a pure iOS app running on macOS. The settings in the screenshot are provided by macOS automatically. It would require us to build a Catalyst app (or native macOS app) which isn't on the roadmap so I'm going to close this issue. Sorry 😢

**Comment by domoritz** [comment]
I don't understand. I want a menu link to the element settings that are accessible through the UI. That should be possible with the existing APIs, no?
