### ISSUE TITLE
Can't copy links to messages from the public mautrix bridge discussion rooms

### ISSUE THREAD

**Issue by marwing** [element-hq/element-x-ios#2618]
### Steps to reproduce

1. Join [`#whatsapp:maunium.net`](https://matrix.to/#/#whatsapp:maunium.net) or [`#signal:maunium.net`](https://matrix.to/#/#signal:maunium.net)
2. Open room
3. Long-press a message
4. Select "Copy link to message" from sheet
5. See error message "Failed creating the permalink"

https://github.com/element-hq/element-x-ios/assets/29716248/ffebbd4f-7c3c-401c-ab5d-39fc0b7659f3

#### What did you expect?
A link being copied to the clipboard

#### What happened instead?
![Screenshot 2024-03-30 at 16 42 26](https://github.com/element-hq/element-x-ios/assets/29716248/b767a6c7-288c-4836-a6f4-5026d8e5b954)

The only weird thing about these rooms I know of is their room IDs, which are obviously custom-made (`!whatsapp-v10:maunium.net` and `!mautrix-signal-v6:maunium.net`).
Element Web can create these permalinks just fine.

### Your phone model

iPhone 13 mini / iPad Pro

### Operating system version

iOS/iPadOS 17.4.1

### Application version

1.6.1 (101)

### Homeserver

Synapse 1.103.0 / Proxy 0.99.15

### Will you send logs?

Yes

**Comment by stefanceriu** [comment]
Can easily reproduce this with a test

```
func testMautrixBridgePermalink() throws {
        let roomId = "!mautrix-signal-v6:maunium.net"
        
        do {
            let permalink = try PermalinkBuilder.permalinkTo(roomIdentifier: roomId, baseURL: appSettings.permalinkBaseURL)
            XCTAssertEqual(permalink, URL(string: "\(appSettings.permalinkBaseURL)/#/!mautrix-signal-v6%3Amaunium.net"))
        } catch {
            XCTFail("Room identifier must be valid: \(error)")
        }
    }
```

```-[UnitTests.PermalinkBuilderTests testMautrixBridgePermalink] : failed - Room identifier must be valid: invalidRoomIdentifier```

**Comment by stefanceriu** [comment]
Thanks for raising this. The PR linked above will take care of it in 2 different ways, but really, the correct solution is to migrate everything to using the RustSDK.
