### ISSUE TITLE
Crash when trying to `@` user in a group chat room on macOS

### ISSUE THREAD

**Issue by a-moreira** [element-hq/element-x-ios#2627]
### Steps to reproduce

1. Open Element X Version 1.6.1 (101) on MacOS Sonoma 14.2.1 (23C71).
2. Go to a chat room with multiple people.
3. Try to tag user using `@`.
4. Dropdown with user list will show in the chat box.
5. Click user
6. Application crashes

### Outcome

I expected to be able to tag an user with `@`. Instead, the application crashes when I click their name on the dropdown list that appears in the chat box.

### Your phone model

Macbook Air M1

### Operating system version

Sonoma 14.2.1 (23C71)

### Application version

Version 1.6.1 (101)

### Homeserver

matrix.org

### Will you send logs?

Yes, if possible.

**Comment by a-moreira** [comment]
I can provide logs, but not sure how to find them on the desktop app.

**Comment by Velin92** [comment]
> I can provide logs, but not sure how to find them on the desktop app.

just report the issue by using the "report a problem" option in the settings.
If you have enabled analytics it will give you an option to include crash logs.

**Comment by stefanceriu** [comment]
Seem to be related to https://github.com/element-hq/element-x-ios/issues/2070

`*** -[NSXPCEncoder _checkObject:]: This coder only encodes objects that adopt NSSecureCoding (object is of class 'ElementX.PillAttachmentViewProvider').`

**Comment by stefanceriu** [comment]
Right, the fix seems simple enough ^
