### ISSUE TITLE
[Task] Copy permalink for Event

### ISSUE THREAD

**Issue by bmarty** [element-hq/element-x-ios#2640]
Please see and discuss the details in the meta issue.

Note: it seems that the action already exists on iOS. Please check that the design / wording is up to date.

**Comment by stefanceriu** [comment]
The UI seems to already be correct, at least according to the [Android PR](https://github.com/element-hq/element-x-android/pull/2653/files#diff-39dc5c0e98792a61ff1a0d141f8cbc71209cbfa85a56189f9471bdcc611292a7), the ticket just mentions `a new "Permalink" action`.

As for the permalink, correct creation (including via parameters) has been handled in https://github.com/element-hq/element-x-ios/pull/2620
