### ISSUE TITLE
Missing timeline history (Scrollback getting completely lost)

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2650]
### Steps to reproduce

In build 566, view a room. Chances are that large hunks of history will go missing, and new messages may not arrive.  Going to room list and back again fixes it.

#### What did you expect?

Reliable timeline

#### What happened instead?

Deeply unreliable timeline

### Application version

566

### Will you send logs?

Yes

**Comment by bnjbvr** [comment]
So this is likely one instance of https://github.com/matrix-org/matrix-rust-sdk/pull/3312 that happens a lot for coincidental reasons: sliding sync || synapse sending duplicate fully read marker events, causing the event cache to forward one "update" per fully read marker, spamming the Rust channel the timeline is listening to, and the timeline concluding that it may have missed important info, and clearing itself.

While the long-term general fix will likely be something like the above PR, the short-term fix is to have the event cache ignore duplicate read marker events for a given room, which [this PR](https://github.com/matrix-org/matrix-rust-sdk/pull/3321) does, and that should avoid most instances of this bug for most people.

**Comment by stefanceriu** [comment]
Fixed in https://github.com/matrix-org/matrix-rust-sdk/pull/3321
