### ISSUE TITLE
Composer getting wedged in unsendable state

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2653]
### Steps to reproduce

1. Roughly once a day, start typing in the composer and discover it doesn’t remove the placeholder text and  doesn’t let you send:
![image](https://github.com/element-hq/element-x-ios/assets/1294269/0557cf7b-fe15-4bb7-abad-001c1101902a)

#### What did you expect?

a composer that works

### Application version

567

### Will you send logs?

No

**Comment by ara4n** [comment]
@stefanceriu this is still happening for me on 578 even with RTE turned offc, as frequently as ever

**Comment by stefanceriu** [comment]
All I can think of is that both editors use the same SwiftUI representable approach and that we might be missing something there. Attempted a fix [here](https://github.com/element-hq/element-x-ios/pull/2732), let's see how it goes.

**Comment by stefanceriu** [comment]
Disregard my previous comment, the real problem and fix is in
