### ISSUE TITLE
Editing message doesn't bring back markdown when RTE is disabled

### ISSUE THREAD

**Issue by marwing** [element-hq/element-x-ios#2655]
### Steps to reproduce

1. Make sure the RTE is disabled in advanced settings
2. Send a markdown formatted message
3. Long press the message
4. Tap Edit
5. See RTE formatted message in composer

https://github.com/element-hq/element-x-ios/assets/29716248/13b0b7b4-5a4a-4ca7-9cd0-7ef0e2b89232

#### What did you expect?
![IMG_3826](https://github.com/element-hq/element-x-ios/assets/29716248/b62bbe7c-3eed-4d5b-a661-4da62c3790c2)

#### What happened instead?
![IMG_3824](https://github.com/element-hq/element-x-ios/assets/29716248/a653ab58-077b-44d1-899c-2a259bcc0585)

### Your phone model

iPhone 13 mini / iPad Pro

### Operating system version

iOS/iPadOS 17.4.1

### Application version

1.6.1 (101)

### Homeserver

Synapse 1.103.0 / Proxy 0.99.15

### Will you send logs?

No

**Comment by Velin92** [comment]
This is technically fixed since we will restore either the markdown or the formatted text according to the state of the editor
