### ISSUE TITLE
Cursor stuck in middle of composer when aborting message editing

### ISSUE THREAD

**Issue by marwing** [element-hq/element-x-ios#2656]
### Steps to reproduce

1. Edit message
2. Tap x to stop editing
3. See cursor is not at beginning of composer
4. Tap backspace
5. See cursor is at beginning of composer

https://github.com/element-hq/element-x-ios/assets/29716248/0d72759a-6c7f-456c-acef-2eb1196ef86a

#### What did you expect?
![IMG_3829](https://github.com/element-hq/element-x-ios/assets/29716248/2d9660e3-0217-4611-a1b0-63a5761486b1)

#### What happened instead?
![IMG_3830](https://github.com/element-hq/element-x-ios/assets/29716248/2eed19cf-24e6-4d65-bcfb-de2a39054a21)

### Your phone model

iPhone 13 mini / iPad Pro

### Operating system version

iOS/iPadOS 17.4.1

### Application version

1.6.1 (101)

### Homeserver

Synapse 1.103.0 / Proxy 0.99.15

### Will you send logs?

No

**Comment by Velin92** [comment]
fixed on the latest version
