### ISSUE TITLE
Long tap on back button unexpectedly produces an ugly single item context menu

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2658]
### Steps to reproduce

1. View a room
2. Long tap on the back button by accident
3. See an unexpected single row context menu labelled “Chats”, which feels quite broken:

![IMG_5954](https://github.com/element-hq/element-x-ios/assets/1294269/57e0215d-ba13-4376-9862-7205b3235e7d)

Or is this a deliberate a11y thing of some kind, or a way to navigate a complex view stack better?

#### What did you expect?

no unexpected long tap eastereggs

#### What happened instead?

weird easteregg

### Operating system version

17.4.1

### Application version

568

### Will you send logs?

No

**Comment by pixlwave** [comment]
This is expected system behaviour in iOS. E.g. see Mail, Notes, Calendar etc.
