### ISSUE TITLE
[Mac] Doesn't start anymore since 1.6.1

### ISSUE THREAD

**Issue by dwt** [element-hq/element-x-ios#2673]
### Steps to reproduce

1. Open the app
2. Wait indefinitely
3. Report bug

#### What did you expect?
The app to start

#### What happened instead?
It blocks when starting

### Your phone model

MacBookPro18,3

### Operating system version

macOS 14.4.1 (23E224)

### Application version

1.6.1

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by stefanceriu** [comment]
When you say `3. Report bug` I assume that you do that through some sort of system dialog because the app is unsable, right? I can't find anything on AppStore connect, is this from a normal or nightly version of the app?

**Comment by dwt** [comment]
This is from the normal app version that is in the [App Store](https://apps.apple.com/de/app/element-x-secure-messenger/id1631335820)

**Comment by stefanceriu** [comment]
This is a shot in the dark but did you try just force quitting it? Apple Silicon iOS apps behave a bit differently than normal

**Comment by pixlwave** [comment]
> Looking for log messages yields these (sparse) results:

Out of interest, what does "blocks what starting" actually look like? Just a bouncing icon in the dock? You'll find the app logs inside `~/Library/Group Containers/group.io.element`, those will possibly have more information depending upon where it's getting stuck.

**Comment by dwt** [comment]
> This is a shot in the dark but did you try just force quitting it? Apple Silicon iOS apps behave a bit differently than normal

Multiple times, that did't seem to help.

What I've noticed though, is that it was able to receive notifications though. Just the UI seems to have blocked.

**Comment by dwt** [comment]
> > Looking for log messages yields these (sparse) results:
> 
> 
> 
> Out of interest, what does "blocks what starting" actually look like? Just a bouncing icon in the dock? You'll find the app logs inside `~/Library/Group Containers/group.io.element`, those will possibly have more information depending upon where it's getting stuck.

I'll have a look later, but since yesterday the app starts again normally. I didn't have time yet to check if that was an update, or my system that changed somehow.

**Comment by stefanceriu** [comment]
Good, then I'll close this ticket. Feel free to reopen if it starts happening again.
