### ISSUE TITLE
Stuck on generating recovery key

### ISSUE THREAD

**Issue by nisbet-hubbard** [element-hq/element-x-ios#2697]
### Steps to reproduce

1. Logging into the app, presented with the options of verify or set up recovery, tapping ‘generate recovery key, I ended up stuck on this screen. 
![IMG_3523](https://github.com/element-hq/element-x-ios/assets/87453615/68f32eb0-2eaf-4d00-bf63-bdb0f92b415d)

2. Because my other session shows exactly the same flow after updating to 1.6.1/2, it’s not possible to have them verify one another either. So one ended up not being able to enter the app at all. 

#### What did you expect?
An optional recovery setup, like before 1.6.1
#### What happened instead?
Mandatory recovery setup that's also broken, leading to app being unusable

### Your phone model

iPhone SE2

### Operating system version

17.2.1

### Application version

1.6.2

### Homeserver

Conduit

### Will you send logs?

No

**Comment by stefanceriu** [comment]
> An optional recovery setup, like before 1.6.1

That's most likely not going to happen. This is the direction the Crypto team is going towards and in the near future messages sent from unverified sessions will be ignored.

Mind reporting a bug through the app so we can have a look at your logs?

**Comment by stefanceriu** [comment]
Bah, of course. I guess your only choice here is to log in on the web app and try to setup recovery properly from there.

We're aware we need a logout button on that recovery screen but we didn't get around to it yet.

**Comment by stefanceriu** [comment]
My pleasure, happy it works now. It's still very weird that it didn't allow you to setup recovery so I would love to see your logs now that you have access to them.

> recovery key goes by the name of 'security key' in the UI
Yep, I think we're converging on recovery key and dropping security key, security passphrase and the rest.

**Comment by stefanceriu** [comment]
```
2024-04-15T21:55:38.897602Z ERROR elementx: Failed generating recovery key with error: BackupExistsOnServer | SecureBackupController.swift:149 | spans: root
2024-04-15T21:55:38.899768Z ERROR elementx: Failed generating recovery key with error: failedGeneratingRecoveryKey | SecureBackupRecoveryKeyScreenViewModel.swift:67 | spans: root
```

This seems to be the interesting bit but I'm not entirely sure what it means. You were trying to enable/setup recovery but a backup already existed on the server ¯\_(ツ)_/¯ Presumably the secrets you had locally (that were shared with you by the other client) weren't the right ones and resetting security fixed all of it.
