### ISSUE TITLE
EX sends read receipts whenever the app is open on a timeline, whether or not the user is present or active.

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2703]
### Steps to reproduce

1. Launch EXI on macOS, open a room, and background the window
2. Notice that whenever a message is sent into that room, it sends a RR
3. This feels spooky in the extreme; EW only sends RRs if the user is actively using the app (i.e. has interacted with the UI within the last N minutes).  So instead it feels like someone might have hijacked your account, given you know it's not you reading the msgs.  Or it makes other people think you're reading your msgs when you're not.

The same behaviour may be true on EXA (even if the app is backgrounded on Android), according to @kongo09 

#### What did you expect?

Only send RRs if the user has interacted with the UI of the app (i.e. touched the screen; moved a mouse; pressed the keyboard) in the last N minutes.  Also, to match EW, one should wait for 500ms (READ_RECEIPT_INTERVAL_MS) of user activity before actually sending an RR, just in case the user is just flicking through and hasn't had time to read.

See
https://github.com/matrix-org/matrix-react-sdk/blob/a0c8575113ac74119cd7841e956cc13463ff9244/src/UserActivity.ts#L63-L77 and
https://github.com/matrix-org/matrix-react-sdk/blob/193237f20457fd161c15068eb2825b2587379140/src/components/structures/TimelinePanel.tsx#L1026 for how EW does it.

#### What happened instead?

Spooky invisible people appear to be reading your msgs who aren't there.

### Application version

574

### Will you send logs?

No

**Comment by stefanceriu** [comment]
Guess this is the wrong check 🤔  https://github.com/element-hq/element-x-ios/blob/develop/ElementX/Sources/Screens/RoomScreen/RoomScreenViewModel.swift#L420

**Comment by pixlwave** [comment]
That one is correct for iOS but for macOS we also need to check the [activeAppearance](https://developer.apple.com/documentation/uikit/uitraitcollection/3618952-activeappearance/) trait (on the window) too.
