### ISSUE TITLE
[Task] Use display names instead of matrix ids for state events

### ISSUE THREAD

**Issue by manuroe** [element-hq/element-x-ios#2706]
Please see and discuss the details in the meta issue.

We will be able to close https://github.com/element-hq/element-x-ios/issues/1453 once done.

**Comment by giomfo** [comment]
@stefanceriu can you confirm this change is available since [v1.6.4](https://github.com/element-hq/element-x-ios/releases/tag/1.6.4)? I failed to find it in the changelog

**Comment by stefanceriu** [comment]
It's done in that commit linked above, together with disambiguation. Missed adding a changelog for it.
