### ISSUE TITLE
Disable automatic screen locking while recording a voice message

### ISSUE THREAD

**Issue by Dlurak** [element-hq/element-x-ios#2707]
**Is your feature request related to a problem? Please describe.**
Even when I'm recording a voice message the screen will still lock automatically, especially for users who's screens lock after just 30 seconds this is very annoying.

**Describe the solution you'd like**
I would like if the screen would stay unlocked while recording a voice message similar to the way it is done in Signal and WhatsApp.

**Describe alternatives you've considered**
I could not think of a good alternative

**Comment by stefanceriu** [comment]
Sounds reasonable to me, I'll see if I can make that happen 👍
