### ISSUE TITLE
Message senders are missing profile information in timeline

### ISSUE THREAD

**Issue by marwing** [element-hq/element-x-ios#2708]
### Steps to reproduce

1. Open room
2. Scroll up until you find a message for that you know that the author has a different display name and/or avatar and one or both are missing

#### What did you expect?
![IMG_3907](https://github.com/element-hq/element-x-ios/assets/29716248/4e7a9d96-7f9a-4702-b439-7d7792351db2)

#### What happened instead?
This seems to affect mostly one account ([@daedric:aguiarvieira.pt](https://matrix.to/#/@daedric:aguiarvieira.pt)), although in the first screenshot, another account is affected ([@nacorid:vengeful.eu](https://matrix.to/#/@nacorid:vengeful.eu)). According to this screenshot read receipts are also unaffected (see the RR from Nacorid).
![IMG_3905](https://github.com/element-hq/element-x-ios/assets/29716248/ce61bcdb-91e1-413f-afd0-515d66a2927f)

In this one, daedric and Ricardo are the same account:
![IMG_3910](https://github.com/element-hq/element-x-ios/assets/29716248/4150a100-c6e6-4483-9f5e-bd9ca119207d)

<details>
<summary>Event information from View Source for the relevant event in the above screenshot</summary>

```rust
EventTimelineItem {
    sender: "@daedric:aguiarvieira.pt",
    sender_profile: Ready(
        Profile {
            display_name: Some(
                "daedric",
            ),
            display_name_ambiguous: true,
            avatar_url: None,
        },
    ),
    timestamp: 2024-04-17T17:05:56.524,
    content: Message(
        Message {
            in_reply_to: Some(
                InReplyToDetails {
                    event_id: "$GiPGorJEb7mSTfecJmppQsQP5bdThzj1AMNYXW6y4zs",
                    event: Ready(
                        RepliedToEvent {
                            content: Message(
                                Message {
                                    in_reply_to: None,
                                    thread_root: None,
                                    edited: false,
                                    ..
                                },
                            ),
                            sender: "@toff26:matrix.org",
                            sender_profile: Ready(
                                Profile {
                                    display_name: Some(
                                        "toff2607",
                                    ),
                                    display_name_ambiguous: false,
                                    avatar_url: None,
                                },
                            ),
                        },
                    ),
                },
            ),
            thread_root: None,
            edited: false,
            ..
        },
    ),
    kind: Remote(
        RemoteEventTimelineItem {
            event_id: "$e2I6O_xNy9fSV56KMBEEJcJodvjUz4wBHEy06kAZcmo",
            reactions: {},
            read_receipts: {},
            is_own: false,
            is_highlighted: false,
            encryption_info: None,
            origin: Pagination,
            ..
        },
    ),
}
```

```json
{
  "sender" : "@daedric:aguiarvieira.pt",
  "content" : {
    "body" : "> <@toff26:matrix.org> Hi, can anyone point me to the nginx configuration for different resources that are available with workers?\n\nDont do this.",
    "formatted_body" : "<mx-reply><blockquote><a href=\"https:\/\/matrix.to\/#\/!ehXvUhWNASUkSLvAGP:matrix.org\/$GiPGorJEb7mSTfecJmppQsQP5bdThzj1AMNYXW6y4zs?via=matrix.org&via=matrix.breakpointingbad.com&via=dev.kyn.be\">In reply to<\/a> <a href=\"https:\/\/matrix.to\/#\/@toff26:matrix.org\">@toff26:matrix.org<\/a><br>Hi, can anyone point me to the nginx configuration for different resources that are available with workers?<\/blockquote><\/mx-reply>Dont do this.",
    "m.mentions" : {
      "user_ids" : [
        "@toff26:matrix.org"
      ]
    },
    "m.relates_to" : {
      "m.in_reply_to" : {
        "event_id" : "$GiPGorJEb7mSTfecJmppQsQP5bdThzj1AMNYXW6y4zs"
      }
    },
    "msgtype" : "m.text",
    "format" : "org.matrix.custom.html"
  },
  "origin_server_ts" : 1713373556524,
  "room_id" : "!ehXvUhWNASUkSLvAGP:matrix.org",
  "event_id" : "$e2I6O_xNy9fSV56KMBEEJcJodvjUz4wBHEy06kAZcmo",
  "user_id" : "@daedric:aguiarvieira.pt",
  "type" : "m.room.message",
  "unsigned" : {

  }
}
```
</details>

Here, the information was available and disappeared after syncing:

https://github.com/element-hq/element-x-ios/assets/29716248/a04e6a26-ebd6-43ec-ad52-16ec266cbb74

Replies are also affected, but mention bubbles apparently not:
![IMG_3904](https://github.com/element-hq/element-x-ios/assets/29716248/3172b208-8d91-40fd-9b26-a74aa1595332)

- As can be seen from the clock in the screenshots (and the video) this happens all the time. Note that I'm UTC+2 if you're looking for these events in the logs.
- Missing profiles was sometimes happening before, but this definitely got way worse with 1.6.3 (maybe 1.6.2).
- ~This appears to only happen for events that were received before the app was last started. This means messages received while the app is open show the correct profile information until the app is restarted.~

### Your phone model

iPhone 13 mini

### Operating system version

iOS 17.4.1

### Application version

1.6.3 (103)

### Homeserver

Synapse 1.105.0 / Proxy 0.99.15

### Will you send logs?

Yes

**Comment by stefanceriu** [comment]
@marwing I can no longer reproduce this although I did see it myself. Is it still a problem on your side?
