### ISSUE TITLE
Duplicate Rooms/People when leaving some

### ISSUE THREAD

**Issue by domoritz** [element-hq/element-x-ios#2735]
### Steps to reproduce

I left a few rooms.

### Outcome

Now I have duplicates in my home view. They don't disappear when I reload the app either. 

![IMG_8B369A5A0950-1](https://github.com/element-hq/element-x-ios/assets/589034/498562e4-92d8-4097-9afd-bd5221386571)

### Your phone model

iPhone 14 pro

### Operating system version

iOS

### Application version

1.6.3 (103)

### Will you send logs?

No

**Comment by Hywan** [comment]
Fixed by https://github.com/matrix-org/matrix-rust-sdk/pull/3585.
