### ISSUE TITLE
Chunks of history going missing when opening app from push

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2742]
### Steps to reproduce

1. Tap on an invite for a room you already accepted on another client (may not be relavent)
2. View room, with the most recent few msgs visible
3. They then animate away; replaced by a spinner
4. Stale history then appears instead
5. Rageshake
6. Go to roomlist and back again
7. History reappears

#### What did you expect?

Reliable timeline

### Application version

581

### Will you send logs?

Yes

**Comment by Hywan** [comment]
I wonder if that's not related to https://github.com/element-hq/element-x-ios/pull/2734?
