### ISSUE TITLE
Once you tap on a permalink, you can't tap on it again.

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2758]
### Steps to reproduce

1. Tap on a permalink
2. Scroll back to the link and tap on it again
3. Nothing happens.

#### What did you expect?

If you scroll the destination off the window, you should be allowed to jump back to that destination by tapping on the permalink again.

### Application version

584

### Will you send logs?

Yes

**Comment by bmarty** [comment]
This is working as expected on Android FWIW:

![ClickOnSameLinkAgain](https://github.com/element-hq/element-x-ios/assets/3940906/109253c5-171d-4fb5-8f02-5ed6facfd120)
