### ISSUE TITLE
“Copyright” in “Settings: About” links you to Element’s copyright policy

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2782]
### Steps to reproduce

1. Tap on copyright in Settings: About
2. Expect to see something about who owns Element X’s copyright (and perhaps third party licenses)
3. Instead get taken to a bunch of stuff about DMCA policies

#### What did you expect?

Have a “Licenses” section which lists our various licenses, both 1st and 3rd party where needed (without which we’re probably in violation of some of the 3rd party licenses which require notice of usage…)

Have a “Copyright policy” section which links to the DMCA stuff

Remove the wtfy “Copyright” link.

### Application version

592

### Will you send logs?

No

**Comment by stefanceriu** [comment]
Fixed in https://github.com/element-hq/element-x-ios/pull/3117
