### ISSUE TITLE
Permalink error handling - #netbsd:nil.im won’t open

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2825]
### Steps to reproduce

1. Click on a link to https://matrix.to/#/%23netbsd:nil.im
2. Loding spinner appears and then disappears
3. nothing happens

#### What did you expect?

Some sort of error message to be shown

### Application version

595

### Will you send logs?

Yes

**Comment by stefanceriu** [comment]
SDK error:
```
▿ ClientError
  ▿ Generic : 1 element
    - msg : "the server returned an error: [404 / M_NOT_FOUND] Room alias #netbsd:nil.im not found"
```

Element Web:
![Screenshot 2024-05-10 at 10 43 28](https://github.com/element-hq/element-x-ios/assets/637564/218a1a89-4568-428a-98db-bb975e436f57)
