### ISSUE TITLE
Invite had no accept button

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2840]
### Steps to reproduce

1. Tapped on a push notif, invite from the CVE bot
2. Saw this:

![IMG_6601](https://github.com/element-hq/element-x-ios/assets/1294269/18850f8e-4bee-4caf-afbd-cbb2d3be1bac)

#### What did you expect?

Accept/Reject style buttons

#### What happened instead?

No buttons. I went back to the roomlist; invite wasn't there (perhaps SS hadn't synced?); waited 

### Your phone model

iPhone 12 Pro Max

### Application version

597

### Will you send logs?

Yes

**Comment by ara4n** [comment]
arguably this is an improvement on https://github.com/element-hq/element-x-ios/issues/2773 but not much ;P

**Comment by manuroe** [comment]
We need to test first that `/room_summary` API is working on m.org.

**Comment by stefanceriu** [comment]
Okay, I have finally figure out what's happening
- the room summary API is indeed enabled on matrix.org and working fine for most rooms
- it is not however capable of giving us data about non-joined + private rooms
- the SDK addresses that by [first trying to use known rooms](https://github.com/matrix-org/matrix-rust-sdk/blob/main/crates/matrix-sdk/src/client/mod.rs#L999) before resorting to the preview endpoint
- that fails if it's a brand new room that the client doesn't know about yet i.e. a sync hasn't ran, which is exactly what's happening here
