### ISSUE TITLE
Impossible to send a voice message

### ISSUE THREAD

**Issue by hermitoff** [element-hq/element-x-ios#2845]
### Steps to reproduce

1. Start to record the voice message
2. Stop the record by clicking on the square button
3. The square button is not replaced by the send button 

#### What did you expect?
Be able to send the voice message

#### What happened instead?
See the video

https://github.com/element-hq/element-x-ios/assets/82811865/8421bcf5-ad35-4ce1-9dfa-37bbe3af5c26

### Your phone model

iPhone 8 +

### Operating system version

iOS 16.7.8

### Application version

1.6.7 (106)

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by stefanceriu** [comment]
Introduced in https://github.com/element-hq/element-x-ios/commit/1e810f91ff012fc34d88655600153dfcb8ad413f#diff-d729d369327d21c304cf5d4172893d64a394c0a3b4b0a696b030e06b114149d0R413

**Comment by stefanceriu** [comment]
This has now been fixed and we will push a hotfix version of the app to the store asap. Thank you very much for reporting it!
