### ISSUE TITLE
Room list refuses to open rooms on being tapped

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2887]
### Steps to reproduce

1. Launch app
2. Immediately open a room while it's syncing (precise repro steps unclear)
3. Wait for scrollback to load; it doesn't
4. Go back to room list
5. Tap on rooms
6. They flash, but don't open

#### What did you expect?

Room list that works (and scrollback that loads)

#### What happened instead?

Some kind of deadlock. I'm not sure what the precise repro steps are, but i've had it a few times.

### Application version

608

### Will you send logs?

Yes

**Comment by stefanceriu** [comment]
Haven't seen this in a while, I think it's fixed
