### ISSUE TITLE
MacOS: Select text and copy. 

### ISSUE THREAD

**Issue by wrjlewis** [element-hq/element-x-ios#2924]
**Is your feature request related to a problem? Please describe.**
I often need to copy and paste text from messages I receive in Element, for example code snippets, or email addresses, or quoting messages. 

On MacOS, I can't seem to do that on ElementX. You can not select portions of text, nor can you copy even the whole message. 

**Describe the solution you'd like**
The ability to select snippets of text, in a message, with your cursor. Additionally the ability to copy that text to clipboard.

**Comment by stefanceriu** [comment]
Not entirely sure how that fell through the cracks but [2925](https://github.com/element-hq/element-x-ios/pull/2925) should take care of it (and more). Thanks for the ticket!

**Comment by wrjlewis** [comment]
Thanks! 🚀
