### ISSUE TITLE
Cannot delete spam invite from bridged service 

### ISSUE THREAD

**Issue by nisbet-hubbard** [element-hq/element-x-ios#2948]
### Steps to reproduce

Spam invites on WhatsApp that got blocked there still appear in this app. Scrolling to these Decline/Accept generates log like:
```
07:31:39 WRN GlobalCache.LoadRoom: no metadata for this room, returning stub room=!gghJuRkqWmaFFkyGlK:tchncs.de
```
Trying to decline them throws errors.

### Outcome

Is this to be reported here or to the mautrix bridge?

### Your phone model

SE2

### Operating system version

17.5.1

### Application version

1.6.9 (108)

### Homeserver

conduwuit

### Will you send logs?

Yes

**Comment by stefanceriu** [comment]
I don't recognize that log line or the components it refers to, is that from Conduit? Can you interact with them from any other client? If not that would point to a homeserver issue

**Comment by stefanceriu** [comment]
Hmm okay, so ElementX is requesting roon info SS doesn't know about and the server knows that's no longer an invite. I wonder if this is another case of our "duplicated rooms" issue in which diff operations are not propagated to the client in between sessions and the offline cache goes out of sync. 

On quick way to check it would be to invoke the developer options menu (7 taps on the app version in the settings screen) and then reset your cache. If the invites go away then we have our culprit.

**Comment by stefanceriu** [comment]
Okay, that means SlidingSync is sending back down those invites event though they're not valid, case in which there's really nothing for the app to do.

Probably best to move this to the sliding-sync repo now. I also found this ticket that might or might not be related https://github.com/matrix-org/sliding-sync/issues/261.

**Comment by stefanceriu** [comment]
Thank you too, do please reopen it if there's anything we need to do or you need further assistance.
