### ISSUE TITLE
Inbound call failed to ring

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2951]
### Steps to reproduce

1. I called EXI from ED+EC
2. EXI was running in bg; phone unlocked
3. No notification of any kind on EXI
4. Opening the app showed a green join button in the top right, which worked.

#### What did you expect?

Phone to ring.

The notify event was:
```json
{
    "content": {
        "application": "m.call",
        "call_id": "",
        "m.mentions": {
            "room": true,
            "user_ids": []
        },
        "notify_type": "ring"
    },
    "event_id": "$17188820765322OKgrs:matrix.org",
    "origin_server_ts": 1718882076263,
    "sender": "@matthew:matrix.org",
    "type": "org.matrix.msc4075.call.notify",
    "unsigned": {
        "membership": "join",
        "age": 283,
        "transaction_id": "m1718882075950.101"
    },
    "room_id": "!WiNqiCWGdeBLKcQdkZ:matrix.org"
}
```

#### What happened instead?

No ring.

### Application version

628

### Will you send logs?

Yes

**Comment by ara4n** [comment]
https://github.com/element-hq/element-x-ios-rageshakes/issues/1904

**Comment by stefanceriu** [comment]
There is no trace of that even ID anywhere in the NSE logs, without it the app can't start the ringing.
