### ISSUE TITLE
If you lock the phone while EX+EC is on a call, you don't get CallKit controls.

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2959]
### Steps to reproduce

1. Join EC call in EX
2. Lock the phone
3. Expect to see something like this on the lockscreen:

![IMG_7140](https://github.com/element-hq/element-x-ios/assets/1294269/b28f8604-a858-4e54-8b85-f1fcdf8245d6)

4. Instead, if you're lucky, you see UI for playing media in the background - although i can't even reproduce that currently.

#### What did you expect?

CallKit style UI for managing calls when on lockscreen.

#### What happened instead?

No UI really at all.

Dunno if this is a bug or a feature at this point?

### Operating system version

628

### Will you send logs?

No

**Comment by stefanceriu** [comment]
https://github.com/element-hq/element-x-ios/pull/2967 should take care of it but I wouldn't be surprised there are still problems, that API is horrendous to use and to test. Closing for now.
