### ISSUE TITLE
Joining a room you don't have permission to join gives an ugly error

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2961]
### Steps to reproduce

1. Click on a permalink to a private room you're not invited to
2. Observe generic "error occurred" error msg.

#### What did you expect?

Nice error message

#### What happened instead?

Ugly error msg

### Application version

628

### Will you send logs?

No

**Comment by manuroe** [comment]
We need to synchronise what Android is doing in this case.

**Comment by bmarty** [comment]
This is how clicking on a link to an other account private room renders on EXA:

<img width="180" alt="image" src="https://github.com/element-hq/element-x-ios/assets/3940906/418484b0-b1e8-4379-af9d-53b903c44d2a">

and the code to get in this state: https://github.com/element-hq/element-x-android/blob/develop/features/joinroom/impl/src/main/kotlin/io/element/android/features/joinroom/impl/JoinRoomPresenter.kt#L105

And the Figma: https://www.figma.com/design/Ni6Ii8YKtmXCKYNE90cC67/Timeline-(new)?node-id=570-35734&t=rdrljKGGGM6OkvD6-0

<img width="300" alt="image" src="https://github.com/element-hq/element-x-ios/assets/3940906/1038c70a-6062-43c1-a7d7-4600b1d8f86e">
