### ISSUE TITLE
Remove the plain text mode of the timeline

### ISSUE THREAD

**Issue by manuroe** [element-hq/element-x-ios#2964]
aka the Modern Message layout in the Advanced settings of the app.

We made this timeline layout to help the UX transition from the legacy app but we spent all of efforts (design, implementation, tests) on the bubbles layout. The plain text mode is now suffering of maintenance issues. We should just remove it. We may add it back later seriously if a strong demand appears. We will then build with the same quality standards as the rest of the app.

Element X Android does not have it for the record.

For reference, we are aware of the following possible problems on the plain text layout:
- No specific UI for replies and replies in thread
- RRs
- Permalinks highlight rendering
- Display name disambiguation not supported
- Message timestamps
- "Advanced" HTML message rendering: quotes, code block, etc

**Comment by Velin92** [comment]
The code is still there but now the plain mode has been fully disabled, in the next days we will also cleeanup the code, but in the meantime the plain mode is inaccessible to users.
