### ISSUE TITLE
State events appear inconsistently in room previews

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2979]
### Steps to reproduce

@pixlwave says:

> If I scroll down my list now, every room has the correct last message, but then I open any room that Amsha is in, pop back and it’s changed to show the state event for her away message.

It sounds like the all_rooms list ignores the most recent state event when updating the room preview cache, but visible_rooms doesn't? (or back-paginated history doesn't)?

Eitherway, it should be consistent.

#### What did you expect?

The room preview should show a text preview of the most recent visible message in a room, or nothing at all.

### Application version

631

### Will you send logs?

No

**Comment by pixlwave** [comment]
Closing this as looks like it was fixed following the room list sorting update.
