### ISSUE TITLE
App icon shows unread messages although there are none

### ISSUE THREAD

**Issue by kostrykin** [element-hq/element-x-ios#2993]
### Steps to reproduce

The app icon shows that there are unread messages:
![IMG_2801](https://github.com/element-hq/element-x-ios/assets/6557139/4cd394fe-fe19-44a5-846b-d66254de4a26)

However, after opening the app, there are no unread messages:
![IMG_2800](https://github.com/element-hq/element-x-ios/assets/6557139/dc0b8e9f-d283-493a-85f3-8883b23fa13f)

Restarting the app does not solve issue.

I cannot send logs because nothing happens when I shake the phone with the app open.

#### What did you expect?

I expect the app icon to stop indicating falsely that there were unread messages.

#### What happened instead?

The app icon keeps indicating that there are two unread messages.

### Your phone model

iPhone 13 mini

### Operating system version

iOS 17.5.1

### Application version

Version 1.6.11 (112)

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by pixlwave** [comment]
@kostrykin Do you see unread messages if you use the old app, Element Web or another matrix client?

**Comment by kostrykin** [comment]
@pixlwave I see unread messages when using the old Element for iOS, but not when using Element on the desktop (macOS).

**Comment by pixlwave** [comment]
Ok, and if you read all of those does the EX badge drop to zero?

**Comment by kostrykin** [comment]
There are no unread messages which I could read when I open the app. It’s only shown on the app icon. So I guess the answer is _no_.

**Comment by morguldir** [comment]
Same as https://github.com/element-hq/element-x-ios/issues/2066, basically the counts are from your server and synapse still rarely returns an incorrect badge count

Element Web doesn’t use push so it won't be affected

**Comment by pixlwave** [comment]
> There are no unread messages which I could read when I open the app. It’s only shown on the app icon. So I guess the answer is _no_.

On the old iOS app?

**Comment by kostrykin** [comment]
> > There are no unread messages which I could read when I open the app. It’s only shown on the app icon. So I guess the answer is _no_.
> 
> On the old iOS app?

Yes, it’s the same on both iOS apps. Only reason that I switched to the new one was that I hoped it would fix the wrong badges.

**Comment by pixlwave** [comment]
Ah ok yes, then it seems its similar to the previous one linked but less obvious. Until we have all the data locally to compute unread counts properly. For now this is caused by either
- A bug in Synapse where it is reporting to us that there are unreads when there are not.
- You have some rooms with events that aren't displayable on mobile (but that sounds less likely)

**Comment by ara4n** [comment]
this really is a dup of #2066...

**Comment by ara4n** [comment]
dup https://github.com/element-hq/element-x-ios/issues/3151
