### ISSUE TITLE
Stale room previews are worse with local roomlist sorting

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#3007]
### Steps to reproduce

1. Open the app and let it sync
2. Observe that there are some really stale messages turning up in the room previews in the room list:

![image](https://github.com/element-hq/element-x-ios/assets/1294269/273daa83-48b8-4c62-88bf-96ae3710981f)

3. Open the 'solid' room (in this instance) to see why it's showing a message from 3 days ago
4. The room loads fairly rapidly, revealing that:
  * the last visible message is something totally different from a few hours ago
  * the most recent event in the room was a membership change.

In other words, it is showing some random old cached event in the room preview.

#### What did you expect?

Room previews should not show spurious old cached events. They should:
 * Show the Latest Visible Event
 * Be ordered by the timestamp of the Latest Visible Event (to avoid weird out-of-order timestamps where the server didn't know what the correct Latest Visible Event was)

#### What happened instead?

A feeling of brokenness and flakiness due to showing a spurious old event in the preview, which doesn't actually match the LVE once you open the room.

### Application version

642

### Will you send logs?

No

**Comment by pixlwave** [comment]
Context: Currently local room list sorting is only syncing with a limit of `1`. I've got a WIP branch where we subscribe to rooms when they appear in the list which returns us back to the behaviour of visible rooms syncing with `20`.

This behaviour is expected until that work is merged (I'm trying to rationalise the best way to track subscribing/unsubscribing to prevent needlessly spamming `/sync`.
