### ISSUE TITLE
MacOS: Clicking on the room list can select the wrong room

### ISSUE THREAD

**Issue by wrjlewis** [element-hq/element-x-ios#3013]
### Steps to reproduce

1. Open the app
2. Click on a room in the room list
3. An unexpected room opens, always the one above the room you clicked

#### What did you expect?
The room you clicked is opened

#### What happened instead?
The room above the one in the list you clicked, opens. Like the room list and mouse click is skewed vertically somehow. 

Only happens on MacOS

### Operating system version

MacOS

### Application version

643

### Homeserver

Synapse latest 

### Will you send logs?

No

**Comment by ara4n** [comment]
this happens on iOS too

**Comment by manuroe** [comment]
Dup of https://github.com/element-hq/element-x-ios/issues/2386.
