### ISSUE TITLE
Rageshake fails with 502(?) error from cloudflare, presumably because logs are too large.

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#3020]
### Steps to reproduce

1. Turn on roomlist debugging or something else which generates lots of logs
2. Try to rageshake
3. Wait 10 minutes for the upload to happen
4. See a cloudflare error flash up - i think it was a 502.

#### What did you expect?

Rageshake to truncate my logfiles so it can upload them without hitting limits.

#### What happened instead?

An inability to QA.

### Application version

644

### Will you send logs?

No

**Comment by pixlwave** [comment]
@ara4n did you figure out what went wrong/can we close this?
