### ISSUE TITLE
Queued messages unexpectedly get sent at 2am.

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#3025]
### Steps to reproduce

1. I tried to send a message using my `@matthew:element.io` account (which I use infrequently, uses OIDC, and has push turned off)
2. It must have got queued - perhaps OIDC had expired and the app was stuck doing a resync, or perhaps i was just on bad data.
3. Two days later, at 02:23am, the message suddenly got sent.

Looks like the reason it got sent is that the app (appstore release of EXI) autoupgraded itself to the latest release, and apparently this is enough to kick the send queue to flush.

#### What did you expect?

Send queue should flush in the background rather than waiting for the app to get relaunched somehow.  This could be by using [BGAppRefreshTask](https://developer.apple.com/documentation/backgroundtasks/bgapprefreshtask), or doing so when receiving push (not that push would have worked here), as well as when launching the app.

#### What happened instead?

The queue didn't flush for 2 days, and then suddenly the message appeared out the blue, which could have been *very* surprising and confusing, as there's no way of telling that it was delayed by days. "Why on earth was Matthew awake at 2am sending weird messages, even for him?!".   This could seriously undermine faith in the app.

Another possible mitigation could be to include an authoring timestamp on the message, separate to the origin_server_ts, so receiving clients can somehow warn that the message is delayed to avoid extreme confusion.

### Application version

642

### Will you send logs?

No

**Comment by pixlwave** [comment]
We have a BGAppRefreshTask that is woken up whenever iOS wants to allow so that we can do incremental syncs. Need to double check that this is linked to the send queue, but aiui the frequency of the background tasks is based upon your usage of the app, so that lines up.

**Comment by ara4n** [comment]
not running a bg task for 2d seems pretty harsh... seems more likely that the bg task isn't flushing the send queue?

**Comment by pixlwave** [comment]
I've just had a look through some rageshakes and can confirm that when a background task is running it enables the send queues which should be all that is needed to let them do their thing.

**Comment by pixlwave** [comment]
I just found the rageshake for this issue, there are plenty of these lines in it:

> Successfully scheduled background app refresh task

I don't see a single instance of the task being launched though. Going to close this issue as we don't have much control beyond asking the OS to run the app in the background.
