### ISSUE TITLE
Big blank gaps in the room list (even with local sorting)

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#3026]
### Steps to reproduce

1. Switch to the roomlist
2. About 5% of the time, observe it looking like this:

![image](https://github.com/element-hq/element-x-ios/assets/1294269/669d183c-dc05-4fa4-a353-45b051afbe62)
Scrolling the roomlist infinitessimally makes the missing rooms render again.

#### What did you expect?

Robust room list which doesn't have blanks in it.

#### What happened instead?

Weird blanks

### Application version

644

### Will you send logs?

No

**Comment by manuroe** [comment]
It is a UI problem with SwiftUI.
We add it before SSS, since at least 1y. Removing the SSS label.
