### ISSUE TITLE
Opening a room whilst the app is syncing takes you to the JoinRoomScreen.

### ISSUE THREAD

**Issue by pixlwave** [element-hq/element-x-ios#3031]
### Steps to reproduce

1. Force quit the app.
2. Tap a notification to re-launch

Alt:
1. Force quit the app
2. Enable the network link conditioner with 100% loss
3. Open the app and see it is stuck on syncing.
4. Tap any room in the room list.

#### What did you expect?
For the room to open

#### What happened instead?
The JoinRoomScreen is opened.

https://github.com/user-attachments/assets/a216f201-e260-40ca-a117-d9dd28ddff42

### Your phone model

iPhone 12

### Operating system version

iOS 17.5.1

### Application version

1.6.14 (Nightly)

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by Hywan** [comment]
Should be fixed by https://github.com/matrix-org/matrix-rust-sdk/pull/3702. Can you check @pixlwave please?

**Comment by pixlwave** [comment]
Yep, can confirm, thanks @Hywan 🙇‍♂️, will get that integrated before closing this PR.

**Comment by Hywan** [comment]
Nice thanks!
