### ISSUE TITLE
Video and voice call stops working after updating from 1.6.11(112) to 1.6.13(115)

### ISSUE THREAD

**Issue by aki-mizu** [element-hq/element-x-ios#3033]
### Steps to reproduce

1. Where are you starting? What can you see?
Tapping video call button from the chat screen, I can see the other party joining the video call.
2. What do you click?
Tapping the voice and video button to turn on voice and video.

#### What did you expect?
The other party can see mute mark becomes unmuted, and video started after turning on video.
#### What happened instead?
For voice, after tapping voice button to unmute, the other party still sees the mute icon unchanged, and no voice can be heard.
For video, after tapping video button to turn on video, the video turns black or white, depends on the situation. Sometimes the other party could see the video.
This issue does not occur on the previous version 1.6.11(112).

### Your phone model

iPhone 11

### Operating system version

iOS 17.5.1

### Application version

1.6.13(115)

### Homeserver

conduit 0.8.0

### Will you send logs?

No

**Comment by stefanceriu** [comment]
Fixed in #2975
