### ISSUE TITLE
Rooms don’t get marked as unread reliably

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#3034]
### Steps to reproduce

I haven’t spotted this myself, but there is lots of anecdata from inside & outside the team that since local roomlist sorting landing unread state is unreliable in EXI and EXA. Filing as i don’t see a bug tracking it otherwise.

#### What did you expect?

Enter room; room should be seen in roomlist as read.

#### What happened instead?

Room still seen as unread

### Application version

645

### Will you send logs?

Yes

**Comment by bnjbvr** [comment]
Fixed with https://github.com/matrix-org/matrix-rust-sdk/pull/3705. Will be fixed in the next SDK bump in the app. Thanks for the issue!
