### ISSUE TITLE
Room list scroll stutters since local roomlist sorting

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#3035]
### Steps to reproduce

1. Use a big test account
2. Scroll around the room list
3. Notice that it stutters down to 10fps or so at points, probably while subscribing to rooms or updating based on subscription results

#### What did you expect?

Silky smooth roomlist scrolling, like we had before

#### What happened instead?

Intermittent stuttering (at least on my phone & log level)

### Your phone model

12 pro max

### Application version

646

### Will you send logs?

No

**Comment by Hywan** [comment]
Can we close this one now?

**Comment by ara4n** [comment]
it seems to have got better anecdotally, but this might be because SSS wasn't subscribing correctly? (i think it got better when we switched from SS to SSS)

**Comment by ara4n** [comment]
i.e. no, i'd keep this open until subscriptions work in SS

**Comment by Hywan** [comment]
I am not sure it is related to room subscriptions at all. Since they do not work with SSS for the moment, can you try with the proxy and see if your performance issue is fixed? If yes, then we can close this bug report.

**Comment by manuroe** [comment]
@ara4n can we close it now? https://github.com/matrix-org/matrix-rust-sdk/issues/3827 should fix it.
