### ISSUE TITLE
Opening room immediately after launch takes you to join page even if you’re already joined

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#3036]
### Steps to reproduce

1. launch app from cold
2. search for room immediately
3. tap on it
4. get join page, despite already being joined
5. hit back
6. tap on it again
7. this time it works

#### What did you expect?

presumably the app was doing a paginated initial sync and hadn’t yet synced the room in question. it should have blocked until it got the room, either via sync or subscription, rather than assumed i wasn’t a member of it.

#### What happened instead?

confused flakiness where it returned the room from the room cache(?) in search results and then behaved as if i wasn’t in it.

### Application version

651

### Will you send logs?

Yes

**Comment by manuroe** [comment]
Dup of https://github.com/element-hq/element-x-ios/issues/3031
