### ISSUE TITLE
Element Call embedded in a self chat doesn’t show video

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#3037]
### Steps to reproduce

1. Have a room with just you in it
2. Hit the call button
3. Unmute video
4. See no video - just black
5. Check you’re on the right camera
6. No difference

#### What did you expect?

I expect to see my local video when placing a video call

#### What happened instead?

https://github.com/user-attachments/assets/fb2f0ca7-50b8-47e8-adee-60d3a178b042

### Application version

651

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by stefanceriu** [comment]
Handled in #3041
