### ISSUE TITLE
Recent history doesn't decrypt on login

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#3045]
### Steps to reproduce

1. Login to an OIDC account (don't use QR login)
2. Verify the login from EW to get E2EE working
3. Open an E2EE room and discover it full of UTDs for the recent history it's synced
4. Scroll back a few pages and discover that history then starts working.
5. Later on, roughly 10 minutes later, notice that the recent history is now decrypted too.

#### What did you expect?

Recent history is decryptable as soon as you've verified your new login.

#### What happened instead?

It feels like the SDK is caching the fact that it couldn't decrypt the history after the initial sync, and not retrying to decrypt once E2EE is verified.

### Your phone model

iPhone 12 Pro Max

### Application version

1.6.13

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by richvdh** [comment]
Let's close this in favour of #3055, which seems to be the same thing but slightly better described.
