### ISSUE TITLE
Regressed room list invites

### ISSUE THREAD

**Issue by stefanceriu** [element-hq/element-x-ios#3047]
- invites are no longer sorted properly and they all appear at the bottom
- accepting an invite doesn't not update the room list
    - using the room list filters or searching for the room will force it to update
    - even after appearing the room will be in the old position
    - ~sending a message in the room will not move it in the list~
    - ~any sent messages in this room will be lost after leaving the room and re-entering it (they to get sent over the network)~

<details>
<summary> No longer relevant </summary>
https://github.com/user-attachments/assets/15e9b7ee-25ef-40df-9016-d0834008b04e

![Screenshot 2024-07-16 at 11 29 41 AM](https://github.com/user-attachments/assets/478fa3ac-ebc1-46e2-9ca2-15feb40a98c3)
</details>

**Comment by manuroe** [comment]
Fixed in https://github.com/matrix-org/matrix-rust-sdk/issues/3707.
