### ISSUE TITLE
Redacted message shown in room list

### ISSUE THREAD

**Issue by wrjlewis** [element-hq/element-x-ios#3068]
### Steps to reproduce

There was an image posted to a room, but removed / redacted, and you could still see the image filename in the room list. For some time.  

Gave me the impression the room list preview doesn't stay up to date with events in the timeline. 

I've seen a lack of complete parity between preview in the room list and latest message in the room before (for instance when the preview fails to show at all until you click the room), but since this was on a redacted/removed event it seems more significant. 

#### What did you expect?
The room list preview to show 'Message removed' or the next valid message. 
#### What happened instead?
The room list preview showed the filename of a removed message. 

### Your phone model

iPhone 12 pro

### Application version

654

### Homeserver

Synapse latest 

### Will you send logs?

No

**Comment by manuroe** [comment]
Tested on EXI 1.9.6 nightly and EXA 0.7.4 nightly. This is no more a bug.
