### ISSUE TITLE
SSS: Room list doesn't update after initial sync

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#3089]
### Steps to reproduce

1. Enable SSS
2. Initial sync happens rapidly (yay!)
3. Participate in rooms
4. The roomlist ordering doesn't get updated (presumably related to https://github.com/element-hq/element-x-ios/issues/3088)
5. Force-quit app, and relaunch
6. App *immediately* shows more up-to-date roomlist & previews (and then spasms as it updates)

#### What did you expect?

Responsive roomlist

### Application version

662

### Will you send logs?

No

**Comment by manuroe** [comment]
@erikjohnston can it be an issue on backend?
Else @Hywan will have a look at it.

**Comment by erikjohnston** [comment]
@manuroe I don't think so, I believe the app is receiving the updates and then not updating the room previews. The backend may not be sending the right info, but I think this needs someone client side to dig into and figure out what is going on,

**Comment by Hywan** [comment]
Do you still experience this?

**Comment by ara4n** [comment]
i just tried to repro and can confirm it's fixed (although remote echo takes a while to arrive, and local echos aren't shown in the room preview, making the roomlist feel broken and sluggish).

instead i hit https://github.com/element-hq/element-x-ios/issues/3165.
