### ISSUE TITLE
SSS: Timeline reloads every time you open a room

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#3091]
### Steps to reproduce

1. Enable SSS
2. Open room from room list
3. See most recent msg, and then a spinner as the rest of the timeline loads
4. Go back to roomlist
5. Open room again
6. See that it's forgotten the timeline; it shows the most recent msg and then a spinner again as it loads the rest of the timeline.

#### What did you expect?

* The timeline for a room should be cached once loaded
* The timeline for a room which is visible in the roomlist should be preloaded by subscriptions (thanks to being visible in the roomlist)

#### What happened instead?

* Unexpectedly reloading timelines + associated spinners

### Application version

662

### Will you send logs?

No

**Comment by manuroe** [comment]
Maybe an issue with another subcription to the room or with sticky parameters. @Hywan will look at it.

**Comment by Hywan** [comment]
cc https://github.com/matrix-org/matrix-rust-sdk/issues/3647

**Comment by ara4n** [comment]
i no longer see this every time you open a room. honestly, i think this can be closed - the only timeline resets i've been seeing are being tracked by https://github.com/element-hq/element-x-ios/issues/3087
