### ISSUE TITLE
SSS: lots of UTDs 

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#3103]
### Steps to reproduce

1. I’ve been trying to use EX+SSS as my only client for the last few hours
2. Lots of UTDs. It feels like we’re entirely dropping todevice msgs
3. Even after waiting for ages and restarting the app, they are still UTD

#### What did you expect?

no utds

#### What happened instead?

lots of utds on new msgs.

If I launch another client i suspect they will resolve via online backup

### Application version

666

### Will you send logs?

Yes

**Comment by pixlwave** [comment]
@ara4n Did you toggle SSS before the automatic sign-out implementation was added? If you did, have you signed out and back in again?

**Comment by ara4n** [comment]
this was it.
