### ISSUE TITLE
Profiles often don’t load in timeline.

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#3110]
### Steps to reproduce

1. open a room for the first time in a session
2. about 30% of the time, no profiles load - just raw mxids:

![IMG_7912](https://github.com/user-attachments/assets/e2f79a9e-64e2-42a5-b910-7c305f333b57)

3. go back to roomlist and reenter room
4. profiles now appear

#### What did you expect?

reliable profiles everywhere

#### What happened instead?

racey flakiness

### Application version

667

### Will you send logs?

No

**Comment by ara4n** [comment]
(this is with SSS)

**Comment by ara4n** [comment]
...although i think it was also happening pre-SSS

**Comment by stefanceriu** [comment]
This indeed has nothing to do with SSS. I can easily reproduce it by dropping the connection after loading timeline items/backpaginating. 

It does also fix itself when the timeline item in question re-appears on screen.

Both of these are expected per https://github.com/element-hq/element-x-ios/blob/develop/ElementX/Sources/Services/Timeline/TimelineController/RoomTimelineController.swift#L400 and https://github.com/element-hq/element-x-ios/blob/develop/ElementX/Sources/Services/Timeline/TimelineController/RoomTimelineController.swift#L143

What would the new desired behavior be, should I additionally re-fetch all of them when the network conditions change?
