### ISSUE TITLE
Copying a message is not working.

### ISSUE THREAD

**Issue by mannymoo5** [element-hq/element-x-ios#3111]
### Steps to reproduce

IOS Element version 1.11.16

Unable to copy message text to clipboard. Need to do it several times to succeed.

### Outcome

Text needs to be on the clipboard of ios.

### Your phone model

iphone 14

### Operating system version

ios version 17.6

### Application version

1.11.16

### Will you send logs?

Yes

**Comment by pixlwave** [comment]
Duplicate of https://github.com/element-hq/element-ios/issues/7087 (and in the wrong repo)
