### ISSUE TITLE
SSS: timelines get stuck, showing stale contents without any spinner.

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#3130]
### Steps to reproduce

1. Open a room
2. See stale content
3. See no spinner telling you that it's stale.

#### What did you expect?

Either a sync spinner, or no missing msgs.

#### What happened instead?

Missing msgs, which eventually fix themselves at some point in the later.

### Application version

669

### Will you send logs?

Yes

**Comment by manuroe** [comment]
@Hywan can you check this issue and the logs, please?

**Comment by ara4n** [comment]
i haven't seen this in the last few days

**Comment by manuroe** [comment]
> i haven't seen this in the last few days

let's close it then. This is issue is too old in the SSS world.
