### ISSUE TITLE
[ElementCall] Pressing the lock button while a call is ongoing promply ends the call

### ISSUE THREAD

**Issue by stefanceriu** [element-hq/element-x-ios#3136]
This happens no matter the location app, springboard or lockscreen.

**Comment by stefanceriu** [comment]
- CallKit decides what action to to take when pressing the hardware lock button based on where the audio is routed to. Using the speaker will make it lock the phone while using the headset will make it end the call.
- Before the introduction of CallKit we had to manually setup the AudioSession to keep the audio live in the background. This is now clashing with CallKit making it bevelie the audio is not routed to the speaker and causing the call be terminated when pressing the lock button.

**Comment by fkwp** [comment]
https://github.com/element-hq/element-x-ios/pull/3338
