### ISSUE TITLE
Room list: "No chats yet" texts overlap when switching tabs

### ISSUE THREAD

**Issue by manuroe** [element-hq/element-x-ios#3144]
### Steps to reproduce

1. Use an account with no room
2. Select a filter like People

<details>
<summary>People "No chats yet" description overlaps the "No chats yet" main list. The effect varies on language</summary>
<img src="https://github.com/user-attachments/assets/05b9c2c7-227b-49a7-b5d4-00f4333a101b"/>
</details> 

#### What did you expect?
No overlap so that the description is easy to ready.

#### What happened instead?
Different types of overlaps that dependson the selected tab and  language. First I thought there was a UI bug because I was seeing a vertical lign. Actually, it was the bottom of the "Start chat" button of the main view.

**Comment by manuroe** [comment]
should we display tabs when there is no room?

**Comment by stefanceriu** [comment]
> should we display tabs when there is no rooms?

We should not, no. #3156 will takes care of that.
