### ISSUE TITLE
SSS: room previews can be very inconsistent

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#3148]
### Steps to reproduce

1. Launch app
2. Look at room list
3. Some room previews are very stale

It seems that if the most recent event in the room is not visible, it shows a stale cache of the room preview, causing the timestamps to jump around unpredictably.

This was previously worked around by subscribing to visible rooms with limit=20, making the chance of a stale cache much less. But it no longer seems to be working in build 674

#### What did you expect?
reliable room previews
#### What happened instead?
see rageshake

### Application version

674

### Will you send logs?

Yes

**Comment by ara4n** [comment]
This is apparently because synapse SSS doesn't yet return history when you subscribe to rooms.

**Comment by manuroe** [comment]
probably fixed with https://github.com/element-hq/element-x-ios/pull/3220.
