### ISSUE TITLE
SSS: After clearing cache, slightly old rooms (4 days old) take minutes to show up when searching the room list.

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#3165]
### Steps to reproduce

1. I cleared cache to test https://github.com/element-hq/element-x-ios/issues/3089
2. The app took a surprisingly long time to sync (~10s or so)
3. Then, i kept searching the roomlist for a test room which is about 4 days idle. In practice, this means that it's probably 100-200 rooms down my room list.
4. The room didn't show up in the roomlist search results though.
5. I kept searching about 6 times, until eventually it showed up a few minutes after the cache clear.

#### What did you expect?

1. the roomlist search results should warn you if they're incomplete because the list is still being paginated from the server, and avoid the user thinking that the room they're looking for doesn't exist.  Shoving a spinner in the search results could be enough.
2. The roomlist should paginate in more rapidly. I'd have expected the first 100-odd rooms to load in a few seconds, not a few minutes.

### Application version

679

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by ara4n** [comment]
Is it possible that the results only turned up once the whole roomlist had been paginated? Which might explain why it took so long.

**Comment by Hywan** [comment]
It is dynamic. As soon as the room is created, it will appear in your search results. Maybe the server is just slow to give the rooms back: that's the only sane explanations. I'll investigate.

**Comment by erikjohnston** [comment]
@Hywan is this because when we're growing the room list we set a `timeout=30000`? As even if you grow the range, if nothing new has happened then the server will still block the request on new data? I could easily imagine it taking minutes to finish growing the list

**Comment by ara4n** [comment]
if the list has grown, shouldn't it return immediately with the new rooms, despite the timeout?

**Comment by erikjohnston** [comment]
> if the list has grown, shouldn't it return immediately with the new rooms, despite the timeout?

If there are no updates for the rooms now in the range, no we don't. We could try and track changes to the ranges and immediately return if they do, though the clients can also just not set a `timeout` when growing the lists

**Comment by Hywan** [comment]
@erikjohnston We can tweak the timeout if that helps. Your suggestion is to lower the timeout or to remove it entirely when the range doesn't cover all the rooms?

**Comment by erikjohnston** [comment]
@Hywan I would suggest setting `timeout=0` whenever the app expects a quick response (e.g. when it would show a spinner, waiting to update the UI, etc). So yeah, I'd probably say that `timeout=0` should be set in all states other than `Running` maybe?
