### ISSUE TITLE
Benign alignment issues when displaying images without supplied resolution metadata

### ISSUE THREAD

**Issue by jjj333-p** [element-hq/element-x-ios#3173]
### Steps to reproduce

- be on an iphone 13 mini (perhaps 12 mini as well)
- have a bot or otherwise send an image without supplying resolution metadata
Example event as seen in outcome section
```json
{
  "content": {
    "body": "inspiration.jpg",
    "info": {
      "agency.pain.image-origin": "https://generated.inspirobot.me/a/b5eAjxOKJl.jpg"
    },
    "m.mentions": {
      "user_ids": [
        "@rss:envs.net"
      ]
    },
    "m.relates_to": {
      "m.in_reply_to": {
        "event_id": "$Dxz0W1apqg1fRiW96anvPvnpqgnPvgoVcStRYVRsWDc"
      }
    },
    "msgtype": "m.image",
    "url": "mxc://matrix.org/mezAkwjdssRyiSfoUMJxwdcQ"
  },
  "event_id": "$-y3cScC0Sy_LSdfIkTSX1AYt4VPAKd_owAu8uoQX880",
  "origin_server_ts": 1723789606687,
  "room_id": "!odwJFwanVTgIblSUtg:matrix.org",
  "sender": "@inspirobot-disruptor:matrix.org",
  "type": "m.room.message"
}
```
- view the image in the timeline
- profit(???)

#### What did you expect?

as seen in element web:
![image](https://github.com/user-attachments/assets/18a6bb50-31eb-4f2e-911f-bf2bd70a56b6)

#### What happened instead?

as seen in element x ios:
![image](https://github.com/user-attachments/assets/f8280ccf-57e6-407c-88b5-6d803f51e813)

### Your phone model

Iphone 13 mini

### Operating system version

IOS 18.0 dev beta 5

### Application version

TestFlight 1.7.2 & 1.7.3 (and prior versions)

### Homeserver

Dendrite 1.13.7

### Will you send logs?

~~Yes~~ no, i forgot how to submit logs without having rage shake enabled, and im not sure its necessary for a gui defect? i can if needed.

**Comment by jjj333-p** [comment]
looping back to add now that auth media doesnt load on my homeserver, it seems to be even more broken before the media loads, like it doesnt know the size of its own placeholder

![image](https://github.com/user-attachments/assets/8bc5466f-f4b2-4d3b-81ba-b0f6e4a5063d)

**Comment by stefanceriu** [comment]
Hi, thank you for reporting this. Took me a while to reproduce and the trick is that it needs to be missing sizing info **as well as** be in reply to another message. I can reproduce it just fine on multiple devices and OS versions.
