### ISSUE TITLE
Unexpected logout with MAS

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#3175]
### Steps to reproduce

1. @wrjlewis had an unexpected logout on his element.io acct on MAS

`2024-08-16T17:28:46.608741Z ERROR matrix_sdk_ui::sync_service: Error while processing encryption in sync service: Something wrong happened in sliding sync: 400 Bad Request: Some(ErrorBody { error: InvalidGrant, error_description: Some("The provided access grant is invalid, expired, or revoked.") }) | crates/matrix-sdk-ui/src/sync_service.rs:237 | spans: root`

#### What did you expect?

No random logouts

### Will you send logs?

Yes

**Comment by ara4n** [comment]
cc @sandhose

**Comment by ara4n** [comment]
might be related to https://github.com/matrix-org/matrix-authentication-service/issues/2795

**Comment by manuroe** [comment]
With https://github.com/element-hq/matrix-authentication-service/pull/3650, we should not have the problem anymore.
