### ISSUE TITLE
Images not loading

### ISSUE THREAD

**Issue by maltejk** [element-hq/element-x-ios#3176]
### Steps to reproduce

1. Where are you starting? What can you see?
I shared some pictures with a contact, but cant see them after sending. Older picture are shown as "Loading..." with a spinner spinning forever. Text is fine

2. What do you click?
Nothing else actually. If I tap the picture, I can see another line with 404 in the server log.

3. More steps…
None.

#### What did you expect?

The picture should be shown.

#### What happened instead?

The "Loading..." with spinner just stays there.

I have extracted some server logs:

Server logs below. Note the different unser agents requesting different URL

```
212.53.0.0 - - [16/Aug/2024:20:21:50 +0000] "GET /_matrix/client/v1/media/download/kadse.xyz/YTlPNGubBorNMzOpaiZgTqly HTTP/1.1" 404 86 "-" "Element X/1.7.1 (Mac; macOS Version 14.6.1 (Build 23G93); Scale/2.00)"
212.53.0.0 - - [16/Aug/2024:20:21:50 +0000] "GET /_matrix/client/v1/media/download/kadse.xyz/WRuobPDJnDvIMmvxkQzzffWN HTTP/1.1" 404 86 "-" "Element X/1.7.2 (iPhone 12 Pro; iOS 17.5.1; Scale/3.00)"
212.53.0.0 - - [16/Aug/2024:20:21:50 +0000] "GET /_matrix/media/v3/download/kadse.xyz/WRuobPDJnDvIMmvxkQzzffWN?allow_redirect=true HTTP/2.0" 200 186305 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Element/1.11.74 Chrome/126.0.6478.185 Electron/31.3.1 Safari/537.36"
212.53.0.0 - - [16/Aug/2024:20:21:50 +0000] "GET /_matrix/client/v1/media/download/kadse.xyz/WRuobPDJnDvIMmvxkQzzffWN HTTP/1.1" 404 86 "-" "Element X/1.7.1 (Mac; macOS Version 14.6.1 (Build 23G93); Scale/2.00)"
212.53.0.0 - - [16/Aug/2024:20:21:50 +0000] "GET /_matrix/client/v1/media/download/kadse.xyz/WRuobPDJnDvIMmvxkQzzffWN HTTP/1.1" 404 86 "-" "Element X/1.7.2 (iPhone 12 Pro; iOS 17.5.1; Scale/3.00)"
212.53.0.0 - - [16/Aug/2024:20:21:50 +0000] "GET /_matrix/media/v3/download/kadse.xyz/aWBfchyvovlTGaBHXhtFrGce?allow_redirect=true HTTP/2.0" 200 1207831 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Element/1.11.74 Chrome/126.0.6478.185 Electron/31.3.1 Safari/537.36"
212.53.0.0 - - [16/Aug/2024:20:21:58 +0000] "GET /_matrix/client/v1/media/download/kadse.xyz/aWBfchyvovlTGaBHXhtFrGce HTTP/1.1" 404 86 "-" "Element X/1.7.2 (iPhone 12 Pro; iOS 17.5.1; Scale/3.00)"
```

### Your phone model

iPhone 12 Pro

### Operating system version

iOS 17.5.1

### Application version

1.7.2 (118)

### Homeserver

Synapse 1.95.1-1~bpo12+1 

### Will you send logs?

No

**Comment by pixlwave** [comment]
Have you signed into the app within the last week? There was a bug where we were caching the server version from matrix.org and so the app would attempt to use the wrong API to download media. This is fixed in 1.7.3 for a new login (or should fix itself when the cache expires in 7 days on 1.7.2).
