### ISSUE TITLE
sss: chunks of my roomlist have lost room name

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#3178]
### Steps to reproduce

1. scroll down roomlist
2. discover hunks of roomlist no longer show a room name but a raw room id
3. 
see rageshake & screenshot

#### What did you expect?

working roomlist

### Application version

683

### Will you send logs?

Yes

**Comment by Velin92** [comment]
Seems that the display name of the rooms is returned as nil, is this happening on SSS or on SS?

**Comment by ara4n** [comment]
this is SSS (as per the bug title).

I'm still getting it a lot. Here's #webrtc:matrix.org having got name amnesia right now: ![image](https://github.com/user-attachments/assets/d17f1014-9d9a-49e0-a263-5a1b03390bb8)

**Comment by rwjack** [comment]
I'm not part of many rooms, but this only happened on that same exact room for me

**Comment by ara4n** [comment]
bleurgh, the original bug here is that we were showing raw room IDs - not missing m.room.names. i'll close this and open a new one.
