### ISSUE TITLE
sss: old invites keep rising to the top

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#3198]
### Steps to reproduce

1. open app
2. stale spammy invites from months ago are shown in the first 20 odd rooms in the room list
3. be confused

#### What did you expect?

i expected invites to appear sorted by time they were received in the room list

#### What happened instead?

something keeps bumping them towards the top. perhaps if there’s activity in the underlying room, the invite is ordered based on that activity rather than the timestamp when the invite was issued? (or perhaps somebody is reissuing spam invites to these rooms)?

### Application version

686

### Will you send logs?

No

**Comment by ara4n** [comment]
(similar but different to https://github.com/element-hq/element-x-ios/issues/3096 ftr)

**Comment by stefanceriu** [comment]
Haven't seen this in a while, have you?

**Comment by ara4n** [comment]
i have it constantly. abusive invites which sit at the top of my todo list thanks to the invited room being active in the bg.

**Comment by manuroe** [comment]
@ara4n can you share a rageshake with room ids for invites. It will help us to debug the issue that may be in Synapse. @erikjohnston will have a look.

**Comment by ara4n** [comment]
done - see rageshake.

**Comment by ara4n** [comment]
should be fixed by https://github.com/element-hq/synapse/pull/17674
