### ISSUE TITLE
Autocorrect of last word has different behavior from other apps

### ISSUE THREAD

**Issue by clokep** [element-hq/element-x-ios#3216]
In Messages, Slack, Element iOS and other apps on iOS if you typo the last word and hit send it applies the currently highlighted autocorrect and then sends the message.

Element X iOS doesn't do this -- it sends the last word as is (without the autocorrect applied). This causes me to send lots of typoed messages due to the difference in behavior. It happens with both the plaintext and rich text editors (although I only care about the plaintext editor).

This is on version 1.7.3 (119).

**Comment by stefanceriu** [comment]
Nice one, thanks Patrick. A bit ridiculous to fix but #3216 should take care of it 👍

**Comment by clokep** [comment]
Woo! Thank you so much!
