### ISSUE TITLE
SSS: slow incremental sync when an event backlog builds up (i.e. if you're offline for a while)

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#3223]
### Steps to reproduce

1. Go offline for a few hours/days/weeks in a busy account
2. Launch EX
3. Observe incr sync takes tens of seconds, proportional to the time spent offline.

#### What did you expect?

Incremental sync should be O(1) not O(N) with time spent offline.

Specifically, the server should reset the SSS connection after 30m offline (or after 2000 events stack up in the backlog) to force the client to do a paginated initial sync when it next launches rather than a slow unpaginated incr sync.

In future, we should probably paginate the incr sync instead so it syncs rapidly (to avoid overloading the server with lots of unnecessary full initial syncs after every 30m of idleness), but that's a separate MSC.

#### What happened instead?

Slow incr sync. (In theory, although I haven't actually had a chance to spot & check this in practice - this is a theoretical vuln)

### Application version

697

### Will you send logs?

No

**Comment by erikjohnston** [comment]
From backend point of view we should add logic to reset the connection if it looks like there are "a lot" of updates to send in response to a request. It's sub-optimal to have to do this, as we end up sending down all the old rooms all over again, wasting server and client resources and bandwidth. Though its a good stop-gap.

From a client/SDK point of view I think it'd be good to reduce the range back down to `[0-19]` after some time of inactivity (but *not* reset the connection), like we do when we see a connection error/timeout. This will then allow the server to (hopefully) respond quickly to the first request and for the client to fetch the rest of the updates in when the list grows. I don't think it really matters too much if we reduce `[0,19]` relatively quickly, so I'd probably suggest a 30m timer would be a good first try.

**Comment by erikjohnston** [comment]
Sounds like since the SDK doesn't persist the `pos` tokens, we think this case will unlikely to be hit in practice, though we should still something here.

**Comment by erikjohnston** [comment]
Reduce range issue: https://github.com/matrix-org/matrix-rust-sdk/issues/3935
Persist position across restart issue: https://github.com/matrix-org/matrix-rust-sdk/issues/3936

Reset connection server side: https://github.com/element-hq/synapse/issues/17653

**Comment by alexander-potemkin** [comment]
From what I was able to observe via the server logs and UI, it seems like first sync on the app cold start takes 30 seconds. Is there any specific reason for that?

Shouldn't cold sync request takes a few seconds - to speed up the app warming process?

I understand there are both limits on time and amount of messages, but on a relatively empty server that leads to 'Sync' hanging for 30 seconds initially (and sometimes, when fails due to the token issue, [seems like display](https://github.com/element-hq/element-x-ios/issues/4786#issuecomment-3626635163) 'Server offline' message).
