### ISSUE TITLE
Signing into a server with Native Sliding Sync doesn't present the Analytics prompt

### ISSUE THREAD

**Issue by pixlwave** [element-hq/element-x-ios#3231]
### Steps to reproduce

1. Log out of Element X using a SS proxy.
2. Log in with using the latest EX and Synapse using native SS.
3. Verify the session.

#### What did you expect?
To see the analytics consent prompt.

#### What happened instead?
I was taken directly to the home screen. Backgrounding the app and then foregrounding it did then nudge the onboarding flow to ask if I wanted to opt into analytics.

### Your phone model

11-inch iPad Pro

### Operating system version

iPadOS 17.6.1

### Application version

1.7.5 (121)

### Homeserver

Synapse 1.114.0

### Will you send logs?

No

**Comment by stefanceriu** [comment]
🤔  Might be related to https://github.com/element-hq/element-x-ios/pull/3224
