### ISSUE TITLE
EX didn't get the memo about a new device, via SSS

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-x-ios#3235]
* Andrew logged in on a new device
* later, Matthew sent a message to an encrypted room which included Andrew
* Andrew's new device didn't get the keys

The logs indicate that
 * Matthew's homeserver (matrix.org) received the memo that Andrew had a new device
 * But Matthew's *client*, syncing via simplified sliding sync, doesn't seem to have received that memo.

Unclear if the problem is on the server side or the client side.

**Comment by ara4n** [comment]
(possibly related, given it concerns devices which don't exist: https://github.com/element-hq/element-x-ios/issues/3207?)

**Comment by erikjohnston** [comment]
Likely due to: https://github.com/matrix-org/matrix-rust-sdk/issues/3959

**Comment by manuroe** [comment]
The underlying SDK issue is fixed
