### ISSUE TITLE
Can't swipe down to dismiss photo on iOS/iPadOS 18

### ISSUE THREAD

**Issue by Avi0n** [element-hq/element-x-ios#3243]
### Steps to reproduce
- Tap on any photo. Attempt to swipe down to dismiss the photo. See that you are unable to do so.

This bug can make you have to force close ElX:
1. Tap the room header
2. Tap the room's chat image
3. Attempt to swipe down to dismiss the photo
4. See that you are unable to do so
5. See that you must force close ElX in order to get rid of the photo as there is no other way to close the room's photo

#### What did you expect?
Photo to dismiss on swipe down
#### What happened instead?
Photo unable to be dismissed via swipe down

### Your phone model

iPhone 15 Pro Max

### Operating system version

iOS 18.0

### Application version

1.7.5 (121)

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by pixlwave** [comment]
Note: For now we've made sure there's a Done button to dismiss. There's a small tweak still to make that will restore swipe down to dismiss when the project is built using Xcode 16.
