### ISSUE TITLE
iOS 18 - Can't log in to OIDC server

### ISSUE THREAD

**Issue by cschmittiey** [element-hq/element-x-ios#3244]
### Steps to reproduce

Hi, on the iOS 18 RC I am unable to log into my homeserver that supports OIDC. I believe it is related to #1936 

Here is a screen recording of my latest attempt:

https://github.com/user-attachments/assets/572a59c7-0cdb-49e0-a40c-324d22c28224

Let me know if there's any other information that you need.

#### What did you expect?
to get a webview or "Element X wants to use Safari to log in" prompt
#### What happened instead?
nothing.

### Your phone model

iPhone 13 Pro Max

### Operating system version

iOS 18.0 (22A3354) RC

### Application version

Version 1.7.5 (121) from testflight

### Homeserver

devhack.net

### Will you send logs?

Yes

**Comment by cschmittiey** [comment]
Just submitted logs through the app as well.

**Comment by pixlwave** [comment]
Thanks for opening this issue. We need to go through and add introspection support for iOS 18 as the window is missing.

**Comment by cschmittiey** [comment]
I'm now able to successfully log in after grabbing the latest TestFlight build. Thanks so much for taking care of this!
