### ISSUE TITLE
rooms don’t use m.room.canonical_alias and show a list of members if the m.room.name is not set

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#3262]
### Steps to reproduce

1. Open app on SSS
2. view room list
3. some rooms (specific rooms - e.g. #webrtc:matrix.org and #dendrite:matrix.org) quite consistently show the right avatar, but don't use m.room.name to display the name.

Theory: this is a backend bug where state confusion means the synapse isn't sending the m.room.name to the client at all.

#### What did you expect?

Reliable room names

#### What happened instead?

![image](https://github.com/user-attachments/assets/3de04f2e-f16b-4b37-a013-df6fcc5ab3b9)

This was previously misfiled at https://github.com/element-hq/element-x-ios/issues/3178

### Application version

704

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by ara4n** [comment]
![IMG_9210](https://github.com/user-attachments/assets/34055296-7985-4353-8148-11131d2de4ea)

as an example for #dendrite:matrix.org being mangled

**Comment by ara4n** [comment]
another one:

![IMG_9249](https://github.com/user-attachments/assets/20c17bb0-dace-421b-8dcc-91af8dbf9580)

https://matrix.to/#/!lCKPFDQCcNzeYHQUfd:matrix.org?via=sw1v.org&via=matrix.org&via=envs.net

**Comment by ara4n** [comment]
the problem here is that rust sdk should present the canonical alias a room name if a room has no explicit room name (but does have a canonical alias set). and it doesn’t.

**Comment by ara4n** [comment]
could also cause some of https://github.com/element-hq/element-x-ios/issues/3365

**Comment by pixlwave** [comment]
I believe this has been fixed in the SDK.
