### ISSUE TITLE
No OAuth login button

### ISSUE THREAD

**Issue by MartinDelille** [element-hq/element-x-ios#3263]
### Steps to reproduce

I have a server were the only way my users can connect is by using our OAuth provider. Unfortunately after entering my server address, I have the following login screen:
![B9BB6522-C624-412A-878D-CC181C2B1648_1_102_o](https://github.com/user-attachments/assets/2ce268d9-8002-4051-9953-9d0015c8eb4a)

I should have button opening the OAuth url in a browser instead, like in https://github.com/element-hq/element-ios

#### What did you expect?

A proper button for opening the OAuth provider url.

#### What happened instead?

A user/password

### Your phone model

iPhone 11 pro

### Operating system version

iOS 17.6.1

### Application version

Current apple store version

### Homeserver

matrix.atelier-medias.org

### Will you send logs?

Yes

**Comment by MartinDelille** [comment]
Here is an additional info regarding my server version:

```
dpkg -l | grep matrix-synapse

ii  matrix-synapse-py3                    1.114.0+bullseye1                                  amd64        Open federated Instant Messaging and VoIP server
```

**Comment by pixlwave** [comment]
Have you set up MAS to provide authentication via OIDC for your server? Element X only supports native OIDC or password login and not the old m.login.sso flows

**Comment by MartinDelille** [comment]
I installed matrix-synapse using apt-get. When I look at the [Matrix Authentification Service (MAS) installation](https://element-hq.github.io/matrix-authentication-service/setup/installation.html), it looks like it is an external module without apt installer. Using the provided method would make my server maintenance painful so I'll probably wait until an easier setup will be available. Do I have a chance to see this module incorporated into the matrix-synapse package ?

**Comment by pixlwave** [comment]
I believe that is the intention yes, although you might want to check in [#matrix-auth:matrix.org](https://matrix.to/#/#matrix-auth:matrix.org) to be sure if this will work for your setup :)

I'm going to close this issue as there isn't anything to do on the app side.

**Comment by birbowirbo** [comment]
> Have you set up MAS to provide authentication via OIDC for your server? Element X only supports native OIDC or password login and not the old m.login.sso flows

Hi, I have matrix setup with Authentik as my OIDC provider and it works perfectly on web and on Element but not Element X -- I believe I've implemented it exactly as the docs suggest, does Element X not support Authentik? is there plans for it to do so?
