### ISSUE TITLE
Tapping alternating rooms can lead to ElX displaying a "Join Room" screen

### ISSUE THREAD

**Issue by Avi0n** [element-hq/element-x-ios#3270]
Unsure if this related to SSS or not. Didn't try it before enabling SSS.

### Steps to reproduce

1. On iPad, rapidly tap between two different rooms
2. See that you will get a "Preview is not available...Join Room" screen

#### What did you expect?
To see my room's contents
#### What happened instead?
Got a "Join Room" screen

### Your phone model

iPad Air 4th gen

### Operating system version

iPadOS 18.0 RC

### Application version

1.8.0 (122)

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by ara4n** [comment]
this sounds very similar to https://github.com/element-hq/element-x-ios/issues/3031

**Comment by wrjlewis** [comment]
Also hitting this issue, posted a video internally (let me know if you want a link to it)

I don't need to tap rapidly for the issue to occur, and I generally see a noticeable delay when clicking into certain rooms. 

I'm on build 709

**Comment by manuroe** [comment]
I think I have a way to reproduce it:
- Clear the cache
- Kill the app before all the whole room list is loaded
- Go offline
- Restart the app

The app displays room ids instead of room names for some and if you top one of them, you will get the "Join Room" screen.

This may be the same root race conditionon state events that leads to this particular bug on iOS. @ganfra and @Hywan are working on a batch for room id display bug, which translates into rooms with no name on Android.

**Comment by ganfra** [comment]
This is not the same issue than the "no name" one. 
This one happens in non encrypted room where we need encryption info to create the timeline.
@jmartinesp is working on a fix in the rust sdk.

**Comment by ara4n** [comment]
had something very similar to this this morning; rageshaked

**Comment by jmartinesp** [comment]
This should be fixed by https://github.com/matrix-org/matrix-rust-sdk/pull/4021, once merged.

**Comment by Hywan** [comment]
PR has been merged. Should we wait on an update of EX before closing this issue?

**Comment by Avi0n** [comment]
I ran into this issue again today on 1.8.5 (128) and sent logs.
Steps I took:
- Background EX
- Open EX and open Synapse Admins room
- Before it finishes loading all events, go back to room list
- Open Synapse Admins room again
- See "Join Room" screen
