### ISSUE TITLE
Images with long alt text can't be viewed fullscreen

### ISSUE THREAD

**Issue by Jaffex** [element-hq/element-x-ios#3278]
### Steps to reproduce

When receiving images with a long alt text, trying to zoom in on the image will only show the full alt text.

Let's imagine I received 2 messages of type `m.image` that also contain a body as depicted here:
![IMG_5967](https://github.com/user-attachments/assets/3752e2f5-3441-4813-9dc5-a3ffbabf7331)

The first image has a very short alt text - tapping on it opens the image in fullscreen and the alt text ("hello") is shown above:
![IMG_5968](https://github.com/user-attachments/assets/402bc052-4559-4b6a-8d08-0c5ec123246e)

But now let's tap on the second image with a longer alt text.

#### What did you expect?
I would have expected a full screen version of the tapped image, so I could potentially zoom in on the image or simply look at it in a bigger version.

#### What happened instead?

An image with a longer alt text when tapped on, will show both an abbreviated version of the alt text at the top as well as the alt text in full instead of the image:

![IMG_5969](https://github.com/user-attachments/assets/68ef2063-2c97-46d2-9c71-9dc297ad55c7)

### Your phone model

iPhone 12 mini

### Operating system version

iOS 17.6.1

### Application version

1.8.0 (122)

### Homeserver

Synapse 1.114.0

### Will you send logs?

No

**Comment by Jaffex** [comment]
Slightly related to https://github.com/element-hq/element-meta/issues/2370 (?)

**Comment by wrjlewis** [comment]
I have a similar issue to this one, but the image fails to show full screen and I don't get alt text either. The body of the image is fairly huge and it causes a filename too long os error in ElementX.
