### ISSUE TITLE
Render image captions as per MSC2530

### ISSUE THREAD

**Issue by frebib** [element-hq/element-x-ios#3285]
**Is your feature request related to a problem? Please describe.**
As per MSC2530, and Matrix 1.10 spec https://spec.matrix.org/v1.10/client-server-api/#mimage
some images have captions and should be rendered next to the image when present.

**Describe the solution you'd like**
Something similar to what EXA does: https://github.com/element-hq/element-x-android/pull/2570

**Describe alternatives you've considered**
Use ~the superior (😛) mobile operating system 🤖~ Android

**Additional context**
N/A

**Comment by pixlwave** [comment]
Closed by #3429.
