### ISSUE TITLE
Permalink support

### ISSUE THREAD

**Issue by manuroe** [element-hq/element-x-ios#33]
We need to be able to:

- \[ \] open a particular room from a permalink
- \[ \] be able to join said room if not already joined
- \[ \] back and forward paginate
- \[ \] navigate through several permalinks

Rust SDK issue: https://github.com/matrix-org/matrix-rust-sdk/issues/638

https://github.com/pointfreeco/swift-url-routing seems like a very good fit

**Comment by kittykat** [comment]
@Velin92 says:
> Implementing a system to translate permalinks into routes that can be used to navigate through the app
> 
> https://github.com/pointfreeco/swift-url-routing

**Comment by ara4n** [comment]
we have this! :)
