### ISSUE TITLE
Stuck on syncing with SSS

### ISSUE THREAD

**Issue by clokep** [element-hq/element-x-ios#3300]
### Steps to reproduce

1. Opened the application
2. Saw the "Syncing..." icon
3. Nothing updated

----

I attempted to "clear cache" to see if that would fix it. After the app restarted my avatar was no longer there and it was still stuck in a syncing/broken state.

Eventually my avatar appeared, but nothing else?

#### What did you expect?

The app to update with new messages

#### What happened instead?

The app was stuck on syncing.

### Your phone model

iPhone 14

### Operating system version

iOS 18 (although it was happening yesterday with 17.x)

### Application version

1.81 (123)

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by clokep** [comment]
I submitted logs both before and after clearing cache. Can do so again if it is helpful.

**Comment by kegsay** [comment]
```
  File "/home/synapse/src/synapse/handlers/sliding_sync/room_lists.py", line 1882, in sort_rooms
    await self.store.bulk_get_last_event_pos_in_room_before_stream_ordering(
  File "/home/synapse/src/synapse/storage/databases/main/stream.py", line 1472, in bulk_get_last_event_pos_in_room_before_stream_ordering
    if stream <= min_token:
       ^^^^^^^^^^^^^^^^^^^
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
```

**Comment by clokep** [comment]
Thanks for fixing this so quickly!

**Comment by devonh** [comment]
> Thanks for fixing this so quickly!

It might be a little bit before we get this deployed on matrix.org. But I'm hoping to do that today. :crossed_fingers:

**Comment by clokep** [comment]
This seems to still be happening to me. (From @wrjlewis pinging me this morning I'm assuming we were hoping that element-hq/synapse#17727 would be the full fix and that it was deployed.) I did another clear cache and submitted logs.

**Comment by clokep** [comment]
Looks like updating to v1.8.2 fixed this for me? Anyway, stuff is working again. 🎉
