### ISSUE TITLE
Package Resolution Failed

### ISSUE THREAD

**Issue by LegSho** [element-hq/element-x-ios#3305]
Trying to add element as a package dependency (SPM), by "Up To Next Major Version", "Exact Version" or by commit SHA tag, always returns "Failed to resolved dependencies Dependencies could not be resolved because package 'element-x-ios' is required using a stable-version but 'element-x-ios' , unexpectedly did not find the new dependency in the package graph: sourceControl(identity: element-x-ios, location: SwiftPM.SPMPackageDependency.Sour....

After all, is it even possible to add element-x-ios client as the dependency for our own app and what should all be done in that way, so we don't have to write our own matrix client?

Thank you

<img width="1125" alt="Screenshot 2024-09-18 at 23 10 05" src="https://github.com/user-attachments/assets/4e0e3272-ba85-4120-9dc0-93da8f9149b0">

<img width="1077" alt="Screenshot 2024-09-18 at 23 09 36" src="https://github.com/user-attachments/assets/8e247c2e-c124-4fd6-a052-8a541897326a">

**Comment by stefanceriu** [comment]
Well SPM is correct, `element-x-ios` is not a valid package that you can import into another project. 

What you're looking for is https://github.com/matrix-org/matrix-rust-components-swift
