### ISSUE TITLE
Room topics not visible with SSS

### ISSUE THREAD

**Issue by marwing** [element-hq/element-x-ios#3312]
### Steps to reproduce

1. Force quit the app
2. reopen
3. open room info for room with topic
4. search for the topic

### Outcome

| Expected (iPhone, SS) | Actual (iPad, SSS) |
| - |-|
|![2024-09-22 02 51 52](https://github.com/user-attachments/assets/fdb9845e-d718-44aa-a062-41a014313963)|![2024-09-22 02 51 47](https://github.com/user-attachments/assets/98830d64-d3ee-4101-8045-3a4b80d8be79)|

Some rooms have their topic displayed, but I haven't found a pattern yet.

### Your phone model

iPad Pro (11-inch) (2nd gen)

### Operating system version

iPadOS 18.0

### Application version

1.8.3 (126)

### Homeserver

Synapse 1.115.0

### Will you send logs?

Yes

**Comment by stefanceriu** [comment]
I believe this is caused by https://github.com/element-hq/synapse/issues/17698

**Comment by stefanceriu** [comment]
i.e. the initial required state https://github.com/matrix-org/matrix-rust-sdk/blob/main/crates/matrix-sdk-ui/src/room_list_service/mod.rs#L148 is different than the subscription one https://github.com/element-hq/element-x-ios/blob/develop/ElementX/Sources/Services/Client/ClientProxyProtocol.swift#L43

**Comment by stefanceriu** [comment]
Right, yes, the sdk change moved it to the initial required state so it's fetched as soon as setting up the lists. The synapse fix is just the cherry on top. Thanks for following up!
