### ISSUE TITLE
Provide a way to explicitly deselect a room on iPad

### ISSUE THREAD

**Issue by marwing** [element-hq/element-x-ios#3313]
**Is your feature request related to a problem? Please describe.**
When selecting any room, there is (to my knowledge) no way to deselect all again without force quitting the app. This has repeatedly made me accidentally mark a room as read when foregrounding the app because a room was still visible.

**Describe the solution you'd like**
Add a way to deselect a selected room. As an example, Nheko does this when clicking a selected room again. Alternatively a "back" button could be used, similar to the UI when the screen gets too narrow (like on iPhones), although that would probably feel rather out of place on iPadOS.

**Describe alternatives you've considered**
| Alternative | Problem |
|-|-|
|Force quit the app every time.| Slow and annoying |
| Have an empty room marked as favorite (so it's easily accessible) and always open that before backgrounding the app | Even more annoying |
| Ignore and always manually mark accidentally marked rooms as unread | Also annoying, looses the notification count and sends a read receipt that can't be retracted (in any "normal" client I know) |

**Additional context**
Element Web technically has a similar issue for rooms that aren't in any spaces, so this should maybe be in element-meta?

**Comment by pixlwave** [comment]
This isn't something we're going to look into I'm afraid. Normal iOS behaviour isn't to clear the detail when tapping a row in the primary column a second time. You can long press on the room to mark it as unread if you need to. If the unread count doesn't update, it might be worth an issue on the Synapse side noting that it doesn't affect the count.
