### ISSUE TITLE
Presence Availibility

### ISSUE THREAD

**Issue by kinchit-gauswami** [element-hq/element-x-ios#3314]
Hello Element X team,

My ORG is planning to move from Slack to Element Hosted solution.  We were thinking to buy your Enterprise Plan for 1200 users on fully managed instance. The first most requirement is Presence Availability.

Currently Slack doesnt support this, that is the only reason we are moving from Slack to something else. 

Do you have any plan to launch the Presence feature. 

Example: On WhatsApp, Telegram, WebEx even Matrix Client FluffyChat also shows Presence. For example: Active 34 Seconds Ago or Time Stamp.

**Comment by kongo09** [comment]
> Do you have any plan to launch the Presence feature.

Presence is an important feature and we would like to work on this, but ideally across all our clients including Web and Desktop, not just Element X. However, the outlook is currently for 2025. If you'd like to get more details, let's take that to a DM.

For transparency: I'm Chief Product Officer at Element.
