### ISSUE TITLE
Media Display Controll is not intuitive

### ISSUE THREAD

**Issue by domrim** [element-hq/element-x-ios#3321]
### Steps to reproduce

The Viewer for images and videos is easy to open but hard to close 

1. Select a image/video on the timeline to display it.
2. Image is shown in large with black borders.
3. Try to swipe the image/video "upwards" to remove it.

#### What did you expect?
The Image disapears

#### What happened instead?
Nothing

### Your phone model

iPhone 13 Pro

### Operating system version

iOS 18.0

### Application version

1.8.3 (126)

### Homeserver

synapse 1.115.0+bookworm1

### Will you send logs?

No

**Comment by pixlwave** [comment]
This will be fixed by #3274 & #3303.
