### ISSUE TITLE
Crypto: Rename Invisible Crypto lab flag

### ISSUE THREAD

**Issue by BillCarsonFr** [element-hq/element-x-ios#3322]
Follow up on https://github.com/matrix-org/matrix-js-sdk/issues/4428
Part of https://github.com/element-hq/element-meta/issues/2536

CryptoMode / Invisible Crypto isn't very descriptive.

We want to switch to `DeviceIsolationMode`, so the config flag should be name `Enable OnlySigned Device isolation mode` (description could be `Ignore unverified devices when sending/receiving messages`)

**Comment by richvdh** [comment]
> Follow up on https://github.com/matrix-org/matrix-js-sdk/issues/4428

wrong link, I think? EX iOS does not use the js-sdk.

**Comment by mxandreas** [comment]
> Ignore unverified devices when sending/receiving messages

The new [terminology](https://github.com/matrix-org/matrix-spec-proposals/blob/andybalaam/crypto-terminology/proposals/4161-crypto-terminology.md) suggest using only "not secure" devices (and specifically not using any other similar terms). I think we should be role models in following that terminology? I also see that we have not adopted this new terminology in many other parts of our work - tickets, documents, etc.

Adding one editorial note, I would suggest: _Exclude not secure devices when sending/receiving messages_
