### ISSUE TITLE
Intermittent fault: Trying to send a message to a room which contains a verified user with an unverified device (including ourself) fails badly with “Send failed”

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#3354]
### Steps to reproduce

1. find a verified user
2. get them to login on an unverified device
3. send them a msg
4. msg fails bluntly with “send failed”
5. try to upload a file: similarly fails with “error, failed to upload” or so.
6. bg & fg app
7. send another msg
8. this time get the nice snazzy “do you want to send anyway?” bottomsheet

#### What did you expect?

go straight to the nice snazzy bottomsheet

#### What happened instead?

cryptic horrible ugly errors with no retry button

### Application version

722

### Will you send logs?

Yes

**Comment by richvdh** [comment]
Is this maybe related to https://github.com/matrix-org/matrix-rust-sdk/issues/3973 ?
