### ISSUE TITLE
Mention pills in the composer sometimes turn into file icons

### ISSUE THREAD

**Issue by morguldir** [element-hq/element-x-ios#3369]
### Steps to reproduce

1. Open the app
2. Click one of the rooms
3. Open the composer
4. Start mentioning a user, e.g. @stefan
5. Click one of the users

#### What did you expect?

The mention to display as a pill with the display name

#### What happened instead?

It shows a file icon instead

![IMG_1255](https://github.com/user-attachments/assets/02581a8e-b3a2-4815-9511-2403b5eeac57)

### Your phone model

iPhone 13 Pro

### Operating system version

iOS18.0

### Application version

1.8.4 (127)

### Homeserver

sulian.eu

### Will you send logs?

Yes

**Comment by Velin92** [comment]
Seems to only happen in non RTE composer
