### ISSUE TITLE
[Element Call] Call Kit controls on the lock screen

### ISSUE THREAD

**Issue by stefanceriu** [element-hq/element-x-ios#3372]
Ideally starting and Element Call should integrate with CallKit and use the following behaviors:
* lock screen button would lock the screen if the audio is redirected through the speakers
* lock screen button would end the call if the audio is going through the headpiece
* if audio is on the headpiece covering the "ear" area should turn off the display
* lock screen controls should be available to mute the call, end it etc.
* and all the other behaviors somebody would expect by default in a call on iOS

This was mostly working previously but, unfortunately, it changed with iOS 18 and ElementCall audio is no longer redirecting to the speaker, making the system believe the other behaviors are available e.g. ending the call when locking the screen.

The only solution we found for this to start working again was to **correctly** setup a CallKit session, something we weren't able to do previouly because of https://github.com/element-hq/element-x-ios/issues/3041 and the workarounds needed for that.

As such, the only option we have at our disposal at the moment is to remove the lock screen controls entirely and revisit them after we find out why the web side can't handle CallKit media sessions properly.

**Comment by ara4n** [comment]
@stefanceriu what happens if you use a trivial widget that runs getUserMedia() with callkit enabled media, rather than full element call? In other words, is this going wrong at the webrtc or livekit layer?

**Comment by ara4n** [comment]
well, arse. does it fail on all possible AV settings? (e.g. is there any chance this is a MediaTrackConstraint problem?)

**Comment by stefanceriu** [comment]
Closing as per the excelent insights from https://developer.apple.com/forums//thread/767949?answerId=812951022#812951022
