### ISSUE TITLE
Trust & Decoration | Do not report UTDs from insecure devices to posthog, these are expected UTD

### ISSUE THREAD

**Issue by BillCarsonFr** [element-hq/element-x-ios#3380]
Part of https://github.com/element-hq/element-meta/issues/2541
iOS variation of https://github.com/element-hq/element-x-android/issues/3626

**Comment by andybalaam** [comment]
Removing from Crypto project because this is already tracked as part of https://github.com/element-hq/element-meta/issues/2541

**Comment by BillCarsonFr** [comment]
Done as part of https://github.com/element-hq/element-x-ios/pull/3442/commits/424dbd79ca7437270068a840daf54e398574cbc8
