### ISSUE TITLE
Registration helper CSS is broken when signing up with email

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#3384]
### Steps to reproduce

1. Shouldersurf someone trying to sign up on matrix.org using EX
2. They got as far as trying to enter their email address, but the CSS somehow truncated the bottom of the page (overflow: none; height: 100% or something meaning that the email address entry form was clipped off, so they were typing blind).
3. Had to give up and register on beta.matrix.org instead.

This was on whatever was live on Sat Sept 29th 2024

#### What did you expect?

Mobile CSS not to truncate the page on the registration helper app.

#### What happened instead?

Half the registration form went missing.

### Your phone model

iPhone 15 Pro

### Operating system version

iOS 18.0

### Application version

1.8.4 (127)

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by pixlwave** [comment]
Pinging @langleyd for help! 😇

**Comment by langleyd** [comment]
Fix incoming here -> https://github.com/element-hq/matrix-react-sdk/pull/137

**Comment by langleyd** [comment]
Fix deployed to develop, tested it on the device.

**Comment by pixlwave** [comment]
Thank you!
