### ISSUE TITLE
Can’t copy user or room ids from profile screen (again)

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#3405]
### Steps to reproduce

1. Open a user profile, or room settings screen
2. Try to copy the user’s mxid, display name, or the room’s alias name or displayname
3. Discover nothing is copyable
4. Feel frustrated

#### What did you expect?

Make data fields copyable so users can grab them for use in moderation tools etc

#### What happened instead?

No way to copy, short of grabbing the url from the share function and reformatting it (but doesn’t help on display names)

### Operating system version

18.0.1

### Application version

730

### Will you send logs?

No

**Comment by ara4n** [comment]
see also https://github.com/element-hq/element-x-ios/issues/2546

**Comment by morguldir** [comment]
![image](https://github.com/user-attachments/assets/19d4a6d0-3826-4803-9c3e-d3bd68420764)

Since this has been happening for a while, i work around it by just taking a screenshot and using OCR to copy it

**Comment by stefanceriu** [comment]
This basically https://stackoverflow.com/questions/78993710/swiftui-textselection-enabled-not-working-in-list-on-ios-18

**Comment by morguldir** [comment]
https://stackoverflow.com/a/79135453

Can confirm that updating to ios 18.1 fixed it

**Comment by pixlwave** [comment]
Nice, it works again on my side too. Closing this issue 👍
