### ISSUE TITLE
On small screens (iPhone SE), you can't cancel edits in rooms with pinned msgs

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#3411]
### Steps to reproduce

[sm says](https://matrix.to/#/!amwlFMejXQcoCxNYHH:matrix.org/$soDI_OAx8KOfBeLRU5OSbKoklggSeYAWhRcH-zHUx2M?via=matrix.org&via=element.io&via=beeper.com):
> EXI devs: on a small screen (iPhone SE), when editing a long message, the pinned messages banner overlays the X button, so you can’t cancel the edit (only accept it)

#### What did you expect?

UI should still work on small screens.

Perhaps "if editing or replying to message, hide pinned msgs" would do it?

#### What happened instead?

UI became unusable due to small screen.

### Your phone model

iPhone SE of some kind

### Will you send logs?

No

**Comment by pixlwave** [comment]
Screenshot of this happening:

![Image](https://github.com/user-attachments/assets/ab573266-d1ac-4023-be85-3e509821eed0)
