### ISSUE TITLE
Proximity sensor should be enabled when video is muted on an EC+EX call.

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#3431]
### Steps to reproduce

1. Get on a video call via EC in EX
2. Mute video
3. Raise phone to your ear
4. Discover your ear has hung up the call and/or logged you out of EX

#### What did you expect?

Raising phone to ear, when video is off, should engage proximity sensor and disable the screen.

#### What happened instead?

No proximity disablage and @lampholder managed to log himself out with his ear.

### Will you send logs?

No

**Comment by stefanceriu** [comment]
In this case the proximity sensor will be controlled by CallKit based on where the audio is routed to (the same as the lock button). As it happens, because of the buggy behavior from #3372, it is always enabled on iOS 18+ and should always lock the screen.

**Comment by stefanceriu** [comment]
The proximity sensor is no longer in play (see https://github.com/element-hq/element-x-ios/issues/3372). Let's revisit this when we build a native version of ElementCall.
