### ISSUE TITLE
Slow first connect after reopening app

### ISSUE THREAD

**Issue by nisbet-hubbard** [element-hq/element-x-ios#3432]
### Steps to reproduce

Closing and reopening app without using VPN

#### What did you expect?
`Syncing` appears briefly 
#### What happened instead?
Stuck at `Syncing` for 8 minutes. Potentially related to #3316.

### Application version

1.9.1

### Homeserver

conduwuit

### Will you send logs?

Yes

**Comment by pixlwave** [comment]
Heads up that #3316 has zero effect when a user is already logged in.

**Comment by pixlwave** [comment]
Looking at your logs, they're filled with `TimedOut` errors on `/_matrix/client/unstable/org.matrix.msc3575/sync` and other endpoints like `/_matrix/client/v3/room_keys/keys/…`, `/_matrix/client/v3/keys/query` etc. Closing this as a backend issue.

**Comment by pixlwave** [comment]
There's a chance this is in some way related to https://github.com/element-hq/element-x-ios/issues/3478
