### ISSUE TITLE
UTD event was not decrypted after keys were received

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-x-ios#3449]
In two ~~one particular~~ rageshakes, the keys to a given event arrived a few seconds after the event, but there doesn't appear to have been any attempt to retry the decryption.

**Comment by andybalaam** [comment]
@poljar will look at the logs and see whether he can find any clues

**Comment by richvdh** [comment]
See also element-x-android issue: https://github.com/element-hq/element-x-android/issues/3747

**Comment by richvdh** [comment]
Since this seems common to EXI and EXA, and likely a problem in the rust layer, I have pulled out a common issue to track fixing this in the rust layer: https://github.com/matrix-org/matrix-rust-sdk/issues/4189

**Comment by stefanceriu** [comment]
iOS has implemented a workaround in https://github.com/element-hq/element-x-ios/pull/3628 and the rest is tracked on the rust side
