### ISSUE TITLE
Not all TLDs are recognized when not prefixed with http:// or https://

### ISSUE THREAD

**Issue by composite9239** [element-hq/element-x-ios#3475]
### Steps to reproduce

1. Send or receive a message like "test.moe" or "test.ninja"

#### What did you expect?

For such links to be formatted as links despite no http:// prefix

#### What happened instead?

Links are not formatted like common TLDs such as .com, .net, etc.

### Will you send logs?

No

**Comment by pixlwave** [comment]
Hey, thanks for opening this issue.

We're using the system's [`NSTextCheckingResult.CheckingType.link`](https://developer.apple.com/documentation/foundation/nstextcheckingresult/checkingtype/1411725-link) detection for this, so this is more of a bug with iOS than Element X I'm afraid. As there is an easy fix (including the scheme in the link), I would suggest you open a feedback with Apple and hopefully they'll add support for the missing TLDs: https://www.apple.com/feedback/
