### ISSUE TITLE
Ability for user to change their password

### ISSUE THREAD

**Issue by mileoresko** [element-hq/element-x-ios#3492]
**Is your feature request related to a problem? Please describe.**
As is, Element X does not provide the logged-in user any way to change their password. This is a fundamental requirement, especially for use case where the homeserver does not utilize OIDC/OAuth.

**Describe the solution you'd like**
Allow the user to change their password from the Account Settings, in a similar way Element (not X) makes it possible.

**Describe alternatives you've considered**
Alternatively, would be great if one-time passwords would be a thing in Synapse/Matrix, but as far as I am aware, that is currently not possible. Also in case I am oblivious to this option existing on the server side, I would also not be aware if Element X supports it (if it hypothetically exists).

**Additional context**
<img width="689" alt="image" src="https://github.com/user-attachments/assets/17748c5e-6350-4a0e-9315-44ed4e5e329f">

**Comment by pixlwave** [comment]
As we move towards Matrix 2.0, all servers will become OIDC capable. We have added enough features to perform a password based login so that EX is compatible with (some) existing servers, however we're not planning on expanding any further for legacy auth I'm afraid.

**Comment by mileoresko** [comment]
Fair enough, thank you for the clarification and fast response @pixlwave
