### ISSUE TITLE
Order of messages is sometimes jumbled

### ISSUE THREAD

**Issue by Jaffex** [element-hq/element-x-ios#3583]
### Steps to reproduce

I can't always reproduce the issue, but it seems it mostly occurs when entering a room via a notification.

I was able to reproduce it by sending messages to myself from another account and tapping on the notification from the lockscreen or the notification banner at the top of my screen.

It does not happen every time, but maybe once every ten messages.

#### What did you expect?
I expected the messages in the room to be ordered correctly, as they were the last time I looked at the room.

#### What happened instead?
The messages get reordered by no obvious order (at least not to me).

More recent messages get thrown in somewhere way up in the message history.

Once you scroll upwards a bit, the view refreshes and reorders the messages in the correct order.

The messages also get reordered in the correct order if you go back to the room list and back into the room again.

When opening the room via the notification, you can see that that there's messages from october shown as the more recent ones along with the message I just received.
![Wrong order](https://github.com/user-attachments/assets/a74b6f0d-1ef2-471e-a27a-c03ac8067b86)

After scrolling or re-opening the room however, you can see that there were more recent messages that were not at the right position before:
![Right Order](https://github.com/user-attachments/assets/2fcdb0ea-f7ac-4157-8596-102d144e49fd)

### Your phone model

iPhone 12 mini

### Operating system version

18.1.1

### Application version

1.9.8(139)

### Homeserver

1.120.0

### Will you send logs?

Yes

**Comment by stefanceriu** [comment]
Fixed through the SDK PR linked above.
