### ISSUE TITLE
No most recently used emojis in reaction picker

### ISSUE THREAD

**Issue by Jaffex** [element-hq/element-x-ios#3620]
### Steps to reproduce

1. Update system to iOS 18.2
2. use the reaction picker on a message

#### What did you expect?
The most recently used emojis to be shown in the reaction picker

#### What happened instead?
Only the default reaction emojis get shown

Might need confirmation from other users that this happens after upgrading to iOS18.2

### Your phone model

iPhone 12 mini

### Operating system version

iOS18.2

### Application version

1.9.9(140)

### Homeserver

irrelevant

### Will you send logs?

No

**Comment by Jaffex** [comment]
Issue still persists for me after update to 1.9.10(141)

**Comment by pixlwave** [comment]
As you start sending reactions within EX, the list will be populated.
