### ISSUE TITLE
Encrypt local databases

### ISSUE THREAD

**Issue by manuroe** [element-hq/element-x-ios#441]
We have to replace `None` in the [code](https://github.com/matrix-org/matrix-rust-sdk/blob/badacdcaa668988b6b08d29177913db14b32f796/bindings/matrix-sdk-ffi/src/client_builder.rs#L77) with a secret.

We should manage this secret like on EI where we have a protocol and different implementations to manage secrets.

**Comment by manuroe** [comment]
The key management must be compatible with ElementR-iOS. EIX needs to be able decrypt and use the crypto DB used in EIR.

**Comment by pixlwave** [comment]
We're going to wait to implement this until the SQLite support is available for the state store in the SDK.

**Comment by manuroe** [comment]
Let's try it on nightlies first.
