### ISSUE TITLE
Password field doesn't behave like a password field

### ISSUE THREAD

**Issue by kittykat** [element-hq/element-x-ios#508]
**Describe the bug**
Password field is missing key password field features

**To Reproduce**
1. Install Element X and start logging in
2. Type in a bad password
3. Submit
4. Try to fix the typo in password

**Expected behavior**
I can preview my password before I try logging in and I can navigate to half way through it and change one character after I get it wrong

**What happened**
I cannot preview my password
If I navigate back to a character mid-password to change it, the backspace deletes the whole password instead of one character

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 13.6
 - Version: today's nightly

**Comment by pixlwave** [comment]
Marking as occasional - most users will see this once, some won't see it at all if their homeserver uses OIDC.

Also downgrading to minor as it is a system native password field and behaves *exactly* like one, which doesn't feel like a huge issue to me.
