### ISSUE TITLE
App should remember unsent msgs

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#517]
I just sent a long msg; the app crashed while it was sending. On relaunch, the app has lost the unsent msg, and the composer had forgotten it too.

Additional case:

- Sent a message whilst on bad connectivity.
- Wait for encryption to do its thing
- Lose connectivity entirely before the message has sent
- See a (!) logo on the message
- Go to the roomlist and back into the room
- Watch as the message flickers and disappears forever.

From #1530 

### Steps to reproduce

1. Send a message on bad data
2. Switch room before you get the remote echo
3. Go back to the room
4. Discover the message has been completely lost.

As a really simple demo, here’s an send failure on airplane mode getting lost - but it also happens when not on airplane mode and makes the app feel very unreliable if it silently drops sent msgs.

https://github.com/vector-im/element-x-ios/assets/1294269/cf9ccb51-9d98-4bdd-a0a6-cc0b6c76d9a7

**Comment by jplatte** [comment]
This should probably be a Rust SDK issue / part of https://github.com/matrix-org/matrix-rust-sdk/issues/1194.
