### ISSUE TITLE
Make all TLDs highlight links

### ISSUE THREAD

**Issue by germain-gg** [element-hq/element-x-ios#568]
**Is your feature request related to a problem? Please describe.**

Not all TLDs are highlighting links

- example.org works ✅
- tokens.studio doesn't ❎

**Describe the solution you'd like**

Make it work with all the fancy new TLDs that are around 

**Describe alternatives you've considered**

N/A

**Comment by VolkerJunginger** [comment]
@manuroe Is this something we could fix together w. permalinks?
