### ISSUE TITLE
Presence stuck in "Online" mode until logged out.

### ISSUE THREAD

**Issue by Secnotica** [element-hq/element-x-ios#726]
### Steps to reproduce

Logged in. Nothing else.

### Outcome

My user account seems to be stuck as "Online" in presence, even when the app is not open. Only goes offline when I log out of my account.

### Homeserver

Synapse 1.79.0

### Will you send logs?

No

**Comment by kittykat** [comment]
@NeonMinnen Thank for you filing this issue. We do not have support from presence at this time, so the behaviour is expected for now. Please note that the app is under active development and there will be many more features coming in the next few months!

I will close this issue for now :+1:

**Comment by manuroe** [comment]
After chatting with @pixlwave, I am reopening it. EX does not display presence but it should not corrupt it.
We think this is a proxy issue where the proxy is continuously pinging synapse in the background.

@kegsay what do you think about this analysis? Should we move this issue to the proxy?

**Comment by pixlwave** [comment]
Closing this, it is not an issue with SSS (and I think may possibly have been fixed with SS too).
