### ISSUE TITLE
Room pushes not animating

### ISSUE THREAD

**Issue by stefanceriu** [element-hq/element-x-ios#913]
We have noticed that pushing into a room is sometimes not animated after foregrounding the app. 
We have tracked this down to an iOS bug which we've reproduced on a completely separate test project.

We can't do much about it at the moment so raising this ticket in order to track it.

https://github.com/vector-im/element-x-ios/assets/637564/a72f55ac-4ed2-4516-ad15-32c889dbdec3

**Comment by pixlwave** [comment]
This was fixed by SwiftUI on iOS 17, we're not going to come back to it for iOS 16 (now that 18 is out).
